fix(AWS Comprehend Node): Add paired item support
n8n-io/n8n pull request #10015
Opened 2024-07-11 13:31 UTC by ShireenMissi

## Summary

This PR Adds support for paired items to The AWS Comprehend Node

## Related Linear tickets, Github issues, and Community forum posts

[](https://linear.app/n8n/issue/NODE-1459/aws-comprehend-add-paired-item-support)

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [x] Tests included. <!--
   A bug is not considered fixed, unless a test is added to prevent it from happening again.
   A feature is not complete without tests.

2024-07-12 07:38 UTC, michael-radency requested changes
`pairedItems` fix looks good, but test need an update

2024-07-12 07:38 UTC, michael-radency commented on packages/nodes-base/nodes/Aws/Comprehend/test/AwsComprehend.node.test.ts
> +	});
you do not have test case in your workflow, `testWorkflows`  helper compares result of execution to a pinned data in nodes
![image](https://github.com/user-attachments/assets/75e5e70b-ee61-449b-9ca2-c88d523fd5c3)

2024-07-12 09:43 UTC, michael-radency approved these changes
LGTM

2024-07-12 10:11 UTC, merged

2024-07-17 12:11 UTC, janober commented
Got released with [`n8n@1.51.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.51.0)