refactor(editor): Move a few components to script setup(no-changelog)
n8n-io/n8n pull request #10029
Opened 2024-07-12 08:55 UTC by mutdmour

## Summary

Move a few components to composable

## Related Linear tickets, Github issues, and Community forum posts

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-07-12 11:03 UTC, OlegIvaniv requested changes

2024-07-12 12:24 UTC, mutdmour commented on packages/editor-ui/src/components/NDVDraggablePanels.vue
> +	return get(this, 'nodeType.parameterPane') === 'wide';
good catch

2024-07-12 12:24 UTC, mutdmour commented on packages/editor-ui/src/components/SaveButton.vue
> +				:type="props.type"
ah you are right. I think I got confused with some other issue I ran into

2024-07-12 12:42 UTC, OlegIvaniv approved these changes

2024-07-12 13:03 UTC, merged

2024-07-17 12:11 UTC, janober commented
Got released with [`n8n@1.51.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.51.0)