Migrate WorkflowExecutionsView.vue to composition API
n8n-io/n8n pull request #10198
Opened 2024-07-26 00:50 UTC by RicardoE105

## Summary

## Related Linear tickets, Github issues, and Community forum posts

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-07-26 00:54 UTC, RicardoE105 commented on packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsList.vue
> +		execution?: ExecutionSummary;
Can the execution be optional? that messes up the watch typing

2024-07-26 08:09 UTC, alexgrozav requested changes, later dismissed
Thank you for doing this! I've made some suggestions on how we can make the events flow better, as well as a fix for the @ts-ignore.

2024-07-26 08:09 UTC, alexgrozav commented on packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsList.vue
> +	});
There's no need to provide `confirm` and `cancel`. What you wrote here is the default behaviour in `promptSaveUnsavedWorkflowChanges`.

2024-07-26 08:09 UTC, alexgrozav commented on packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsList.vue
> +	(value: ExecutionSummary) => {
```suggestion
	() => props.execution,
	(value) => {
```

The type of `value` is actually `ExecutionSummary | undefined`, that's why you were getting a type error here

2024-07-26 08:09 UTC, alexgrozav commented on packages/editor-ui/src/views/WorkflowExecutionsView.vue
> +
This change is not needed after you make the other changes.

2024-07-26 08:09 UTC, alexgrozav commented on packages/editor-ui/src/views/WorkflowExecutionsView.vue
> +
This change is not needed after you make the other changes.

2024-07-26 08:09 UTC, alexgrozav commented on packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsList.vue
> +};
```suggestion
const onDeleteCurrentExecution = () => {
  if (!props.execution) return;
  
	emit('execution:delete', props.execution.id);
};
```

Add a guard here to fix emit types.

2024-07-26 08:09 UTC, alexgrozav commented on packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsList.vue
> +};
```suggestion
const onStopExecution = () => {
  if (!props.execution) return; 

	emit('execution:stop', props.execution.id);
};
```

Same here.

2024-07-26 08:09 UTC, alexgrozav commented on packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsList.vue
> +	'execution:stop': [value?: string];
```suggestion
	'execution:delete': [value: string];
	'execution:stop': [value: string];
```

After making the other changes.

2024-07-31 04:53 UTC, cstuncsik approved these changes

2024-07-31 11:11 UTC, merged

2024-07-31 13:13 UTC, janober commented
Got released with [`n8n@1.53.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.53.0)