Fix(Postgres Node): expressions in query parameters for Postgres executeQuery operation
n8n-io/n8n pull request #10217
Opened 2024-07-26 15:39 UTC by ShireenMissi

## Summary

This PR fixes using expressions in query parameters for Postgres executeQuery operation, the query parameters field is expected as comma separated string or an expression that can be evaluated to a comma separated string.
the issue was splitting based on ' , ' before evaluating the expression. 

## Related Linear tickets, Github issues, and Community forum posts
https://linear.app/n8n/issue/NODE-1431/postgres-expressions-in-query-params-broken
https://community.n8n.io/t/postgres-node-in-operator-with-parameters/47801/9

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-07-30 03:42 UTC, michael-radency requested changes
@ShireenMissi  
LGTM, but since we are changing logic here and to avoid potentially breaking existing workflows I would suggest to put this change under minor version and to extract code into utils

2024-07-30 03:42 UTC, michael-radency commented on packages/nodes-base/nodes/Postgres/v2/actions/database/executeQuery.operation.ts
> +					);
I would suggest to extract some common logic
```
			const stringToArray = (str: NodeParameterValueType | undefined) => {
				if (!str) return [];
				return String(str)
					.split(',')
					.filter((entry) => entry)
					.map((entry) => entry.trim());
			};

			if (rawReplacements) {
				const rawValues = rawReplacements.replace(/^=+/, '');
				const resolvables = getResolvables(rawValues);

				if (resolvables.length) {
					for (const resolvable of resolvables) {
						const evaluatedValues = stringToArray(this.evaluateExpression(`${resolvable}`, i));
						if (evaluatedValues.length) values.push(...evaluatedValues);
					}
				} else {
					values.push(...stringToArray(rawValues));
				}
			}
```

2024-07-31 06:25 UTC, michael-radency approved these changes
LGTM :+1:

2024-07-31 06:25 UTC, michael-radency commented on packages/nodes-base/nodes/Postgres/v2/actions/database/executeQuery.operation.ts
> +						.replace(/^=+/, '')
You could use ` stringToArray(rawReplacements.replace(/^=+/, '')) `

2024-07-31 07:39 UTC, merged

2024-07-31 13:13 UTC, janober commented
Got released with [`n8n@1.53.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.53.0)