feat(core): Create GitHub organization repository
n8n-io/n8n pull request #10220
Opened 2024-07-28 13:51 UTC by bdsoha

## Summary

Create GitHub organization repository

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-07-28 13:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/n8n-io/n8n?pullRequest=10220) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/n8n-io/n8n?pullRequest=10220) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/n8n-io/n8n?pullRequest=10220) it.</sub>

2024-08-07 09:38 UTC, Joffcom requested changes

2024-10-09 10:43 UTC, Joffcom commented
Hey @bdsoha,

Looks like there are some linting issues that need to be resolved.

2026-05-04 13:38 UTC, garritfra commented
Thanks for the contribution, and apologies this sat without a response for so long. We're triaging stale PRs and this one has been inactive for an extended period, with the surrounding code having evolved significantly since it was opened. Closing as stale to keep the queue manageable.

If this is still relevant to you, please feel free to reopen with a rebase against `master` (or open a fresh PR) and we'll take a look. 🙏

2026-05-04 13:38 UTC, closed without merging