feat(core): Add project-related params to Public API workflows endpoints
n8n-io/n8n pull request #10231
Opened 2024-07-29 14:59 UTC by ivov

WIP

https://linear.app/n8n/issue/PAY-1788

2024-07-30 12:06 UTC, valya requested changes

2024-07-30 12:06 UTC, valya commented on packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
> +			}
Transferring workflows should probably be it's own endpoint

2024-07-30 12:06 UTC, valya commented on packages/cli/src/PublicApi/v1/handlers/workflows/workflows.service.ts
> +	});
Should probably call `EnterpriseWorkflowService.transferOne`, since more things need done to transfer a workflow

2024-07-30 12:06 UTC, valya commented on packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
>  			);
We need to check the user's scopes on the project for `workflow:create` first

2024-07-30 14:53 UTC, valya approved these changes

2024-07-30 15:05 UTC, merged

2024-07-31 13:13 UTC, janober commented
Got released with [`n8n@1.53.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.53.0)