feat(Postgres PGVector Store): Add PGVector vector store node
n8n-io/n8n pull request #10517
Opened 2024-08-22 14:33 UTC by jeanpaul

## Summary
Add support for the postgres PGVector extension as a vector store. This works similarly to other vector store nodes.

## Related Linear tickets, Github issues, and Community forum posts
https://linear.app/n8n/issue/AI-222/add-support-for-pg-vector-store

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-08-30 15:21 UTC, burivuhster commented on packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePGVector/VectorStorePGVector.node.ts
> +			useCollection?: boolean;
Shall we create a type definition for that?

2024-08-30 15:23 UTC, burivuhster commented on packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePGVector/VectorStorePGVector.node.ts
> +			idColumnName: string;
Let's create a type for this as well

2024-08-30 15:26 UTC, burivuhster requested changes
Looks good, only two minor notes

2024-09-02 06:03 UTC, luizeof commented
Can't wait to use PgVector

2024-09-02 13:54 UTC, burivuhster approved these changes
LGTM! Thanks for addressing my comments

2024-09-03 08:08 UTC, OlegIvaniv approved these changes
Re-approved to trigger E2Es

2024-09-03 09:20 UTC, merged

2024-09-05 10:42 UTC, janober commented
Got released with [`n8n@1.58.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.58.0)