fix(core): Update zod to the latest version (no-changelog)
n8n-io/n8n pull request #10516
Opened 2024-08-22 13:26 UTC by burivuhster

## Summary

Making the zod version consistent with the one used in nodes-langchain.

## Related Linear tickets, Github issues, and Community forum posts

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-08-22 13:46 UTC, OlegIvaniv approved these changes, later dismissed

2024-08-23 09:29 UTC, netroy requested changes
Considering that `zod` is used in multiple packages, and we want to keep the versions in sync, I think we should move the zod version to [pnpm catalog](https://github.com/n8n-io/n8n/blob/master/pnpm-workspace.yaml#L7)

2024-08-23 11:05 UTC, netroy approved these changes

2024-08-23 12:25 UTC, merged

2024-08-28 11:48 UTC, janober commented
Got released with [`n8n@1.57.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.57.0)