unify ConnectionType and NodeConnectionTypes
n8n-io/n8n pull request #10562
Opened 2024-08-26 17:54 UTC by RicardoE105

## Summary

## Related Linear tickets, Github issues, and Community forum posts

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-08-27 01:18 UTC, RicardoE105 commented
@alexgrozav, it looks like somehow I broke the Webhook node connection, but I have not been able to pinpoint the issue. It must be something small that I'm overlooking. If you have any pointers, they will be highly appreciated 🙏 

<img width="934" alt="image" src="https://github.com/user-attachments/assets/31cd2737-2a51-4ca8-8a2e-8b8baf6e6c36">

2024-08-27 09:03 UTC, alexgrozav requested changes
Listed a few things that I think we should fix.

2024-08-27 10:16 UTC, RicardoE105 commented on packages/editor-ui/src/components/RunDataAi/useAiContentParsers.ts
> +			([NodeConnectionType.AiChain, NodeConnectionType.Main] as string[]).includes(endpointType)
Without it 
<img width="1259" alt="image" src="https://github.com/user-attachments/assets/6ba4dd7c-c607-4258-af1c-26c7bc8aa0a3">

2024-08-27 17:23 UTC, RicardoE105 commented
@OlegIvaniv figured out the issue: Changing from enum to const caused the issue. We were using the enum in the expression in the nodes-base package, specifically in some of the node properties. Within the expressions, the enums work because they are resolved at build time. When using const the expressions do not have access to the reference (the object) because they run in a sandbox.

See conversation below:

> Oleg -> We're using NodeConnectionType in several places as const enum to get the appropriate connection key, but it's no longer exported
-> Ricardo -> but I updated it all the places with the new type
-> Oleg -> Yeah but you've changed it from const enum
-> Ricardo -> but it's the same you can do NodeConnectionType.AiAgent, and it s the same with the enum or with the object, both are going to return the string value.
-> Oleg -> Not in the expressions, though; those are not compiled. The as const would preserve the reference of an object during run-time while const enum would replace it inline during build. And when resolving expressions we don't have access to that reference
-> Oleg -> And some inputs/outputs are expressions
-> Oleg -> So when they're resolved, it looks like this:
You can see that there's a reference to n8n_workflow and window but again, those are not available in the sandbox when resolving expressions


<img width="1492" alt="image" src="https://github.com/user-attachments/assets/8a998819-a59b-4b83-b705-f87db24ce013">

2024-08-28 18:25 UTC, RicardoE105 commented
closing in favor of https://github.com/n8n-io/n8n/pull/10595/files

2024-08-28 18:25 UTC, RicardoE105 commented
closing in favor of https://github.com/n8n-io/n8n/pull/10595

2024-08-28 18:25 UTC, closed without merging