build: Add nuke script
n8n-io/n8n pull request #10627
Opened 2024-08-30 14:04 UTC by tomi

## Summary

We often face situations where a build will fail because some cache somewhere is messing up with the build. This PR adds a `nuke` script that can be used to delete all files that might be out of date (i.e. node_modules, dist files, .turbo cache, tsbuildinfo files, etc). It is a more destructive version from `clean`, which doesn't touch e.g. node_modules.

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-09-03 07:35 UTC, netroy reviewed
instead of maintaining a list of purgable files/folder in every package, could we use `git clean -xd` instead (with `--exclude `to skip deleting certain files/folders)?

2024-09-03 09:28 UTC, tomi commented
> instead of maintaining a list of purgable files/folder in every package, could we use `git clean -xd` instead (with `--exclude `to skip deleting certain files/folders)?

@netroy I updated the script to be a bit more sophisticated. Added`.vscode/settings.json` and `.env` files to exclude. Anything else?

2024-09-03 09:30 UTC, netroy requested changes

2024-09-03 10:32 UTC, netroy reviewed
this should work, but has one minor issue that if someone runs `pnpm reset` before running `pnpm i`, this script will error out.

2024-09-03 10:32 UTC, netroy commented on scripts/reset.mjs
> +// Resets the repository by deleting all untracked files except for few exceptions.
maybe we should add `process.env.FORCE_COLOR='1'` to pipe [subprocess TTY colors correctly](https://google.github.io/zx/known-issues#colors-in-subprocess)

2024-09-03 11:08 UTC, tomi commented
> this should work, but has one minor issue that if someone runs `pnpm reset` before running `pnpm i`, this script will error out.

Fixed this by ensuring zx is available. Not necessary ideal to run `pnpm install` to just delete the node_modules and run `pnpm install` again, but it works

2024-09-03 11:31 UTC, netroy approved these changes

2024-09-03 12:35 UTC, merged

2024-09-05 10:42 UTC, janober commented
Got released with [`n8n@1.58.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.58.0)