docs: Add 'benchmark' scope to PR Title Conventions documentation
n8n-io/n8n pull request #10624
Opened 2024-08-30 11:42 UTC by csuermann

Adds 'benchmark' scope and improves some of the markdown formatting.

2024-08-30 13:53 UTC, tomi requested changes

2024-08-30 13:53 UTC, tomi commented on .github/pull_request_title_conventions.md
> +| `ci` | Changes to CI configuration files and scripts (e.g. Github actions) | ❌ |
😍

2024-08-30 13:53 UTC, tomi commented on .github/pull_request_title_conventions.md
>  - `benchmark` - changes to the Benchmark cli
Remove the duplicate

2024-08-30 14:50 UTC, tomi approved these changes
🚀

2024-08-30 15:01 UTC, merged

2024-09-05 10:42 UTC, janober commented
Got released with [`n8n@1.58.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.58.0)