fix(core): Allow license:clear command to be used for licenses that failed renewal
n8n-io/n8n pull request #10665
Opened 2024-09-04 13:46 UTC by csuermann

The `license:clear` command attempts to renew the license before deleting the license information from the database to free up any floating entitlements. However, if the renewal fails (e.g., due to a device fingerprint mismatch), the command errors out before the database record is deleted. This PR addresses the issue by handling errors from the renewal attempt without interrupting the deletion process.

2024-09-04 13:51 UTC, netroy requested changes
Can we please also update `packages/cli/test/integration/commands/license.cmd.test.ts` to include the case where `license.init` or `license.shutdown` throws?

2024-09-04 13:51 UTC, netroy commented on packages/cli/src/commands/license/clear.ts
> +		} catch {}
```suggestion
		const license = Container.get(License);
		await license.init();
		try {
			await license.shutdown();
		} catch {}
```

2024-09-04 13:52 UTC, tomi commented on packages/cli/src/commands/license/clear.ts
> +		} catch {}
IMO we should at least log the error. Swallowing errors is not a good practice

2024-09-05 14:30 UTC, netroy approved these changes
🙏🏽

2024-09-05 14:42 UTC, merged

2024-09-11 17:52 UTC, Joffcom commented
Got released with [`n8n@1.59.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.59.0)