feat(Text Classifier Node): add fixing parser
n8n-io/n8n pull request #10667
Opened 2024-09-04 13:56 UTC by burivuhster

## Summary

This PR adds an option to enable auto-fixing model's output using `OutputFixingParser`. The auto-fixing is enabled by default.

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/AI-281/text-classifier-unexpected-non-whitespace-character

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-09-04 15:42 UTC, jeanpaul requested changes
I think it looks good, but one quick comment about the description; we might need a bit more explanation that this will call the LLM again when the output is broken.

2024-09-04 15:42 UTC, jeanpaul commented on packages/@n8n/nodes-langchain/nodes/chains/TextClassifier/TextClassifier.node.ts
> +						description: 'Whether to enable auto-fixing for the output parser',
Is this enough for people to understand that we will call the original model again if there's a parsing error?

2024-09-05 07:21 UTC, jeanpaul approved these changes
Awesome!

2024-09-05 07:39 UTC, merged

2024-09-05 10:43 UTC, janober commented
Got released with [`n8n@1.58.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.58.0)