Fix: Cross-platform build for @n8n/chat, add custom fork changelog
n8n-io/n8n pull request #10676
Opened 2024-09-05 07:44 UTC by Yasemo

### Fixed

- Build process for @n8n/chat package on Windows environments
  - Modified the build:bundle script in packages/@n8n/chat/package.json to use cross-env
  - Added cross-env as a devDependency in packages/@n8n/chat/package.json
  - This change allows the INCLUDE_VUE environment variable to be set correctly across different operating systems

### Added

- cross-env dependency to facilitate cross-platform environment variable setting

### Changed

- Updated build process to ensure compatibility across different operating systems

### Dev Operations

- Improved build script to work consistently across Windows, macOS, and Linux

## [1.0.0] - 2024-09-05

- Initial fork from n8n official repository

2024-09-05 07:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/n8n-io/n8n?pullRequest=10676) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/n8n-io/n8n?pullRequest=10676) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/n8n-io/n8n?pullRequest=10676) it.</sub>

2024-09-05 08:00 UTC, Joffcom commented
Hey @Yasemo,

Thanks for the PR, We have created "GHC-205" as the internal reference to get this reviewed.

One of us will be in touch if there are any changes needed, in most cases this is normally within a couple of weeks but it depends on the current workload of the team.

2024-11-06 09:09 UTC, netroy requested changes

2024-11-06 09:09 UTC, netroy commented on packages/@n8n/chat/package.json
> +    "build:bundle": "cross-env INCLUDE_VUE=true vite build",
this line is the only change that should be in this PR to be approved. can you please revert all other changes?

2024-11-06 12:03 UTC, netroy commented
Since the CLA isn't signed, I'm closing this in favor of #11589

2024-11-06 12:03 UTC, closed without merging