Pay 1840 follow up fixes and improvements to project viewer role
n8n-io/n8n pull request #10684
Opened 2024-09-05 11:13 UTC by r00gm

## Summary

## Related Linear tickets, Github issues, and Community forum posts

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-09-09 12:31 UTC, cstuncsik requested changes

2024-09-09 16:08 UTC, r00gm commented on packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsPreview.test.ts
> +		const { getByTestId } = render(WorkflowExecutionsPreview, {
i'll try tomorrow first thing

2024-09-10 06:45 UTC, r00gm commented on packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsPreview.test.ts
> +		const { getByTestId } = render(WorkflowExecutionsPreview, {
done!

2024-09-10 07:33 UTC, cstuncsik approved these changes

2024-09-10 07:33 UTC, cstuncsik commented on packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsPreview.test.ts
> +		const { getByTestId } = render(WorkflowExecutionsPreview, {
Thanks

2024-09-10 09:06 UTC, merged

2024-09-11 17:53 UTC, Joffcom commented
Got released with [`n8n@1.59.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.59.0)