feat(core): Introduce worker metrics
n8n-io/n8n pull request #10850
Opened 2024-09-17 10:47 UTC by ivov

https://linear.app/n8n/issue/PAY-1734

2024-09-17 16:51 UTC, despairblue requested changes
I only found one issue in a test, the rest looks good 🚀

2024-09-17 16:51 UTC, despairblue commented on packages/cli/src/metrics/__tests__/prometheus-metrics.service.test.ts
> +			config.set('executions.mode', 'regular');
```suggestion
			config.set('executions.mode', 'queue');
```

2024-09-18 07:48 UTC, ivov commented on packages/cli/src/metrics/__tests__/prometheus-metrics.service.test.ts
> +			config.set('executions.mode', 'regular');
Thank you, good catch!

2024-09-18 08:56 UTC, despairblue approved these changes

2024-09-18 09:16 UTC, merged

2024-09-18 13:05 UTC, janober commented
Got released with [`n8n@1.60.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.60.0)