feat(editor): Overhaul document title management
n8n-io/n8n pull request #10999
Opened 2024-09-27 15:44 UTC by netroy

## Summary
This PR overhaul the code that updates `document.title`, and also updates most of the views to set relevant titles.

## Related Linear tickets, Github issues, and Community forum posts

Fixes #8861
CAT-78

## Review / Merge checklist

- [x] PR title and summary are descriptive
- [x] Tests included

2024-09-30 06:43 UTC, alexgrozav requested changes
Looking good! One small remark regarding the release channel

2024-09-30 06:43 UTC, alexgrozav commented on packages/editor-ui/src/composables/useDocumentTitle.ts
> +		!releaseChannel || releaseChannel === 'stable' ? 'n8n' : `[${releaseChannel.toUpperCase()}]`;
AFAIK, even when we add the release channel, `n8n` should still be part of the title.

```suggestion
		!releaseChannel || releaseChannel === 'stable' ? 'n8n' : `[${releaseChannel.toUpperCase()}] n8n`;
```

2024-09-30 08:42 UTC, alexgrozav approved these changes
Thanks for addressing the suggestions!

2024-09-30 08:57 UTC, merged

2024-10-02 15:04 UTC, janober commented
Got released with [`n8n@1.62.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.62.1)