Facebook trigger webhooks
n8n-io/n8n pull request #1106
Opened 2020-10-28 00:11 UTC by RicardoE105

Improvements to #1051

2020-10-30 13:42 UTC, krynble requested changes

2020-10-30 13:42 UTC, krynble commented on packages/nodes-base/nodes/Facebook/FacebookTrigger.node.ts
> +						value: 'addAccount',
There is a typo here, use adAccount instead of addAccount

2020-10-30 13:42 UTC, krynble commented on packages/nodes-base/nodes/Facebook/FacebookTrigger.node.ts
> +				//compare hub.verify_token with the saved token
I tried making this work but webhookData.veryfyToken is always empty. Maybe it's an async call?
Anyway, no idea how to fix this right now.

2020-11-04 11:25 UTC, merged

2020-11-04 11:26 UTC, janober commented
Thanks a lot. Got merged.

2020-11-04 15:39 UTC, janober commented
Got released with n8n@0.92.0