feat: Add tracking for node errors and update node graph
n8n-io/n8n pull request #11060
Opened 2024-10-02 11:57 UTC by mutdmour

## Summary

1. Add runs and items_count to node graph
2. Add tracking for node errors for manual runs

## Related Linear tickets, Github issues, and Community forum posts

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-10-02 19:53 UTC, RicardoE105 requested changes

2024-10-02 19:53 UTC, RicardoE105 commented on packages/workflow/test/TelemetryHelpers.test.ts
> +		const workflow: IWorkflowBase = {
Should we move the JSON to a helper? The helper will create this whole json and override any parameter provided by default. Same for RunData. Will make much easier to read the tests as half of the file is just JSON

2024-10-02 19:53 UTC, RicardoE105 commented on packages/editor-ui/src/stores/workflows.store.spec.ts
> +			id: '1',
Same as below.

2024-10-02 19:53 UTC, RicardoE105 commented on packages/workflow/test/TelemetryHelpers.test.ts
> +	test.only('should add run and items count', () => {
Remove only

2024-10-02 19:53 UTC, RicardoE105 commented on packages/editor-ui/src/stores/workflows.store.spec.ts
`let nodeTypesStore: ReturnType<typeof useNodeTypesStore>;`

2024-10-02 19:53 UTC, RicardoE105 commented on packages/workflow/src/TelemetryHelpers.ts
> +			nodeItem.items_total = runs.reduce((total, run) => {
We have 365 lines of code in this function. Should we move this part to a helper so we do not make matters worst? Maybe something like:

`
	nodeItem.items_total = getNumberOfItemsInRun(runs)
`

2024-10-15 10:25 UTC, RicardoE105 approved these changes

2024-10-15 10:38 UTC, merged

2024-10-16 11:43 UTC, janober commented
Got released with [`n8n@1.64.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.64.0)