chore: Fix dev setup on windows machines (no-changelog)
n8n-io/n8n pull request #11065
Opened 2024-10-02 12:58 UTC by tomi

## Summary

Fix dev setup on windows machines

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-10-07 14:09 UTC, valya approved these changes

2025-01-02 12:03 UTC, netroy commented on scripts/prepare.mjs
> +execSync(`${executablePath} install`, { stdio: 'inherit' });
Could this just be 

```suggestion
execSync('pnpm lefthook install', { stdio: 'inherit' });
```

2025-01-08 10:58 UTC, netroy requested changes

2025-01-08 10:58 UTC, netroy commented on scripts/prepare.mjs
> +import path from 'node:path';
unused
```suggestion
```

2025-01-08 10:59 UTC, netroy approved these changes

2025-01-08 11:24 UTC, merged

2025-01-09 17:28 UTC, janober commented
Got released with [`n8n@1.74.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.0)