refactor(Structured Output Parser Node): Refactor Output Parsers and Improve Error Handling
n8n-io/n8n pull request #11148
Opened 2024-10-07 20:15 UTC by OlegIvaniv

## Summary
This PR refactors our output parser implementation, extracting them into individual classes and improving error handling, particularly for structured output parsers. These changes should improve our ability to provide user-friendly error messages while maintaining the functionality of the auto-fixing parser.

- The `N8nStructuredOutputParser` now includes a `context` property to handle execution context and supports custom error mapping.
- `N8nOutputFixingParser` integrates with the structured parser to attempt fixing invalid outputs.
- `N8nItemListOutputParser` retains its functionality but is now part of the new parser structure.
- Updated `getOptionalOutputParsers` utility to work with the new parser types.

## Changes

1. Extracted output parsers into separate classes:
   - `N8nStructuredOutputParser`
   - `N8nOutputFixingParser`
   - `N8nItemListOutputParser`

2. Implemented error mapping in `N8nStructuredOutputParser` to allow for both user-friendly error messages and proper error handling in the auto-fixing parser.

3. Removed proxy wrapping from `logWrapper` and instead manually populate input/output data from each parser class.

4. Updated relevant nodes and utility functions to use the new parser classes.

5. Adjusted test files to reflect the new structure and functionality and added tests for `N8nOutputFixingParser` and `N8nItemListOutputParser` nodes.
## Related Linear tickets, Github issues, and Community forum posts

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-10-10 13:56 UTC, burivuhster commented on packages/@n8n/nodes-langchain/nodes/output_parser/OutputParserAutofixing/test/OutputParserAutofixing.node.test.ts
> +	});
Does this test really checks the attempt to fix? Probably it should emulate exception on the first parse call, and provide valid mock on a second.

2024-10-10 14:26 UTC, burivuhster commented on packages/@n8n/nodes-langchain/utils/output_parsers/N8nStructuredOutputParser.ts
> +		errorMapper?: (error: Error) => Error,
Are second and third parameters here actually supplied by callers?

2024-10-10 14:36 UTC, burivuhster requested changes
Awesome job! And kudos for writing tests.
I have only one comment about auto-fixing parser test case, could you please check?

2024-10-22 06:54 UTC, burivuhster submitted a review, later dismissed

2024-10-22 08:32 UTC, burivuhster approved these changes

2024-10-22 08:46 UTC, merged

2024-10-24 10:46 UTC, janober commented
Got released with [`n8n@1.65.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.65.0)