fix(Switch Node): Maintain output connections when changing number of outputs
n8n-io/n8n pull request #11162
Opened 2024-10-08 11:53 UTC by michael-radency

## Summary

remove connection if rule for this connection was removed
if fallback set to extra preserve connected node and do not attach it to added rule output
if using expression for setting number of outputs trim connections if their number was reduced

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/NODE-1669/switch-node-adding-routing-rule-reconnects-fallback-route

2024-10-16 10:37 UTC, ShireenMissi reviewed
I tested locally and on test instance, the only issue is when you add a new rule and create a new connection then reorder the new output doesn't maintain its connection
on test instance it works once I save the workflow
locally I had to save and refresh the page to get it to work

2024-10-16 10:37 UTC, ShireenMissi commented on packages/editor-ui/src/components/NodeSettings.vue
> +// import { useToast } from '@/composables/useToast';
if this is not needed let's just delete it

2024-10-28 14:50 UTC, elsmr requested changes
Found a bug when the workflow is not saved.

In general I think it's an OK solution for the Switch node, but it would be great if connections were saved by ID instead of by index to avoid all this complexity. But not clear to me how to do it without a breaking change.

I think you could have similar bugs in other nodes with dynamic outputs such as the Webhook node.

2024-10-28 14:50 UTC, elsmr commented on packages/editor-ui/src/stores/workflows.store.ts
> +		if (updateCashedWorkflow) {
cashed -> cached

2024-11-01 10:54 UTC, elsmr approved these changes, later dismissed

2024-11-13 10:46 UTC, elsmr commented on packages/editor-ui/src/utils/nodeSettingsUtils.ts
> +		console.log(error.message);
Could maybe be `captureException` from `@sentry/vue` instead of a log?

2024-11-13 10:59 UTC, elsmr approved these changes

2024-11-13 11:30 UTC, merged

2024-11-13 17:11 UTC, janober commented
Got released with [`n8n@1.68.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.68.0)