Replace duplicate Pushover Timestamp field with the missing TTL field
n8n-io/n8n pull request #11287
Opened 2024-10-16 19:26 UTC by AndyHazz

## Summary

Fixing the duplicate `timestamp` field, by swapping it for the missing `ttl` field described in the api documentation: https://pushover.net/api#ttl

## Related Linear tickets, Github issues, and Community forum posts

https://github.com/n8n-io/n8n/issues/10984

2024-10-16 19:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/n8n-io/n8n?pullRequest=11287) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/n8n-io/n8n?pullRequest=11287) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/n8n-io/n8n?pullRequest=11287) it.</sub>

2024-10-16 19:31 UTC, Joffcom commented
Hey @AndyHazz,

Thanks for the PR, We have created "GHC-326" as the internal reference to get this reviewed.

One of us will be in touch if there are any changes needed, in most cases this is normally within a couple of weeks but it depends on the current workload of the team.

2024-10-16 19:33 UTC, Joffcom commented
@AndyHazz thanks for the PR, there is a tricky bit with this one as it involves a field rename so may break users workflows.

A better option would be to implement a light version 1.1 and show the new option on that that way existing workflows will work as they do now and if you add a new node to the canvas you will be able to use the TTL field.

Let me know what you think or if you have any questions.

2024-10-16 20:00 UTC, AndyHazz commented
The original `timestamp` will still be there, it's not really being renamed - currently it's _duplicated_ in `Pushover.node.ts` with an identical name and the same field is shown twice - in the UI no matter which you pick from the dropdown, it adds two fields. Any value you enter, shows in both Timestamp fields.

Removing the duplicate timestamp field shouldn't affect any existing workflows, they can still have a timestamp, it'd just be shown once instead of twice - fixing a bug in the duplicated `timestamp` field, and adding the missing `ttl` field.

2024-10-16 20:15 UTC, AndyHazz commented
The untouched `timestamp` is here:
https://github.com/n8n-io/n8n/pull/11287/commits/d531caf9bf720e8deb5116632bb154ce6058a4f6#diff-a0e5a1096c7a5721a42b3ea7622c15780b7e8172f61ca0669b703ac836faa52cL239

2024-10-21 10:37 UTC, Joffcom commented
@AndyHazz That sounds good, I will get this tested this week.

2024-10-30 19:54 UTC, aalmenar commented
@Joffcom have you been able to test it?

2025-09-12 17:47 UTC, ZsBT commented
Any news on this? Is there an obstacle? This PR still could be merged. 
@Joffcom did you have a chance to review this change?

2026-04-08 13:51 UTC, garritfra approved these changes

2026-04-08 13:53 UTC, garritfra commented
Fixes https://github.com/n8n-io/n8n/issues/26973

2026-04-08 14:20 UTC, garritfra requested changes

2026-04-08 14:20 UTC, garritfra commented on packages/nodes-base/nodes/Pushover/Pushover.node.ts
> +							"Time to Live in seconds, after which the message will be automatically deleted from the devices it was delivered to.",
```suggestion
							'Time to Live in seconds, after which the message will be automatically deleted from the devices it was delivered to.',
```

2026-04-08 14:20 UTC, garritfra commented on packages/nodes-base/nodes/Pushover/Pushover.node.ts
> +						displayName: 'TTL',
```suggestion
						displayName: 'TTL (Seconds)',
```

2026-04-08 14:23 UTC, garritfra submitted a review, later dismissed

2026-04-08 14:31 UTC, garritfra commented on packages/nodes-base/nodes/Pushover/Pushover.node.ts
> +							'Time to Live in seconds, after which the message will be automatically deleted from the devices it was delivered to.',
```suggestion
							'Time to Live in seconds, after which the message will be automatically deleted from the devices it was delivered to',
```

2026-04-08 14:32 UTC, garritfra approved these changes

2026-04-08 15:12 UTC, merged