fix(editor): When cloud users click on "How to update your n8n version"  auto-login them before redirecting to the dashboard (no-changelog)
n8n-io/n8n pull request #11378
Opened 2024-10-23 19:00 UTC by RicardoE105

## Summary

Title self explanatory.

PR also migrates upgradePanel component to composition API.

![image](https://github.com/user-attachments/assets/0d55d645-417d-4068-a3be-d4e14b67376a)

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/ADO-2616/bug-when-cloud-users-click-on-update-info-url-they-dont-get-auto

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-10-24 08:32 UTC, mutdmour commented on packages/editor-ui/src/stores/ui.store.ts
> +const generateCloudDashboardAutoLoginLink = async (data: {
nice refactor. Could we also refactor `redirectToDashboard` in cloud plans store to use this?

2024-10-24 08:32 UTC, mutdmour commented on packages/editor-ui/src/components/UpdatesPanel.vue
> +	uiStore.goToVersions();
lint issue here

2024-10-24 11:13 UTC, netroy requested changes
Can we please make the composition API migration a separate PR 🙏🏽?
That way it's much easier to understand what the actual fix is in this PR.

2024-10-29 23:09 UTC, RicardoE105 commented
Dropping in favor of https://github.com/n8n-io/n8n/pull/11467

2024-10-29 23:09 UTC, closed without merging