fix(core): Improve model sub-nodes error handling
n8n-io/n8n pull request #11418
Opened 2024-10-25 13:54 UTC by burivuhster

## Summary

### Problem
The current error handling in LLM sub-nodes has two main issues:
1. Model sub-nodes sometimes appear as "running" even after failing
2. n8n incorrectly indicate that errors originated in the root node, when they actually occurred in Model sub-nodes

### Context
The error handling relies on custom exception classes (e.g., `NodeOperationError`). However, there's no straightforward mechanism to wrap model exceptions before they propagate to the root node.

### Solution Approaches Explored
1. Using `N8nLlmTracing` (callback handler passed to the LangChain model's contructor). Using `handleLLMError` callback handler allows to add proper error info to the sub-node and fix the infinite running issue. But it can not be used for wrapping the exception for the root node.
2. `onFailedAttempt` callback can be provided during each model's LangChain class instantiation. It allows to intercept the retry logic built into LangChain, and re-throw the wrapped exceptions.

### Implementation
To use the second approach, the new helper function `makeN8nLlmFailedAttemptHandler` was implemented. It catches LLM errors, wrap them with our custom error classes, provides some default error handling logic (interrupt running if it does not make sense to retry for the specific error), and also allows to customize error handling for the specific cases (for example to use a custom error message for the OpenAI's insufficient quota error).

### Known issues
Couple of LangChain model classes do not use the `AsyncCaller` for their calls. It means, that the common retry logic built into LangChain does not work in such cases. The `onFailedAttempt` callback is not being called as well.
Thus, the described error wrapping logic does not work yet for the following models:
* `LMChatOllama`
* `LmChatAwsBedrock`
* `LmChatGoogleVertex`

Example 1. Insufficient quota error (OpenAI)
Before:
<img width="938" alt="image" src="https://github.com/user-attachments/assets/ad19473e-0e94-4951-abb8-c397256dfe34">

After:
<img width="929" alt="image" src="https://github.com/user-attachments/assets/83dfd97a-06ca-4e05-99ce-ce1503c96385">

Example 2. Empty prompt (Anthropic)
Before:
<img width="910" alt="image" src="https://github.com/user-attachments/assets/c2f8841e-21fa-4aef-8925-ba6ca417e9b4">

After:
<img width="815" alt="image" src="https://github.com/user-attachments/assets/20e97126-d290-48c4-ae30-60fa271146c6">

Example 3. Nested sub-node error
Before:
<img width="523" alt="image" src="https://github.com/user-attachments/assets/8afb67ff-5977-4bed-a453-834eec3b1251">

After:
<img width="517" alt="image" src="https://github.com/user-attachments/assets/bb22b005-59e4-4309-9eaa-9d4f8f7ac707">

Example 4. Nested sub-node error
Before:
<img width="793" alt="image" src="https://github.com/user-attachments/assets/8c5f16fc-fefa-451e-b13c-867b83e86e3e">

After:
<img width="872" alt="image" src="https://github.com/user-attachments/assets/708353cc-1fff-4d34-90b3-32fe9db9063c">

## Related Linear tickets, Github issues, and Community forum posts

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-11-01 08:50 UTC, jeanpaul commented
One thing I noticed, that's a difference now is that I don't really get a sense for what's wrong with my credential, whereas on master I do:

<img width="358" alt="image" src="https://github.com/user-attachments/assets/47a1a575-8404-4ec3-b8fc-495896b83bac">

Why did that change?

2024-11-01 08:53 UTC, jeanpaul commented
Also, the error toast still says "Problem in node 'Basic LLM Chain'", not "OpenAI Chat Model"

2024-11-01 10:18 UTC, jeanpaul commented
> One thing I noticed, that's a difference now is that I don't really get a sense for what's wrong with my credential, whereas on master I do:
> 
> <img alt="image" width="358" src="https://private-user-images.githubusercontent.com/65866/382233528-47a1a575-8404-4ec3-b8fc-495896b83bac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTYwMzEsIm5iZiI6MTczMDQ1NTczMSwicGF0aCI6Ii82NTg2Ni8zODIyMzM1MjgtNDdhMWE1NzUtODQwNC00ZWMzLWI4ZmMtNDk1ODk2YjgzYmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDEwMDg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMjE2Y2E2ZjgzZGY3Nzg4YzE4ZTA4NDc5YWFjYTQ5YmZlZTkzMTg5MDVkM2JiMmJlZDc4N2FiNzc0MGMzZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yp9fX26-8Qes41MeeX2MlnYkJZf58X34yyG1dbpZYvo">
> Now it just says something is wrong with my credentials:
> 
> <img alt="image" width="354" src="https://private-user-images.githubusercontent.com/65866/382233775-c2bae2ce-2297-4cea-955c-d3d863347b33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTYwMzEsIm5iZiI6MTczMDQ1NTczMSwicGF0aCI6Ii82NTg2Ni8zODIyMzM3NzUtYzJiYWUyY2UtMjI5Ny00Y2VhLTk1NWMtZDNkODYzMzQ3YjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDEwMDg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjZWQ2YmQ1ZTQ1YTA4YzBkZTIwNDUwZjFjMDFjMTgwNzhkYTUyODA0ZGRiYWI5NDAzY2UwZTNkOGJkMjJkMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RRZdpQr_dnt1bsfnyWvlYRakN-0MXuBBAgpWs1HQWUI">
> Why did that change? I think getting the things to check directly in the toast is a better experience.

I don't know why, but now I cannot reproduce this anymore.

2024-11-01 10:32 UTC, jeanpaul requested changes

2024-11-01 10:32 UTC, jeanpaul commented on packages/editor-ui/src/composables/usePushConnection.ts
On line 326 is another occurrence of `context.functionality` -- can you check if that needs to change too?

2024-11-01 10:32 UTC, jeanpaul commented on packages/editor-ui/src/composables/usePushConnection.ts
And same for `packages/editor-ui/src/utils/expressions.ts` line 63.

2024-11-01 10:32 UTC, jeanpaul commented on packages/@n8n/nodes-langchain/nodes/llms/N8nLlmTracing.ts
> +		const runDetails = this.runsMap[runId] ?? { index: Object.keys(this.runsMap).length };
why do you take the number of keys as the index if `runId` is not in `runsMap`?

2024-11-04 16:55 UTC, burivuhster commented on packages/editor-ui/src/composables/usePushConnection.ts
Should be fine as this is for another case, when nodes use "pairedItem" feature (e.g. referencing previous node's item value when the pairedItem connection was interrupted)

2024-11-05 14:40 UTC, burivuhster commented on packages/editor-ui/src/composables/usePushConnection.ts
It's being set in `n8nLlmFailedAttemptHandler.ts` when we wrap the error into NodeApiError. For the paired item exceptions – nothing changes, I guess it's being set in `WorkflowDataProxy.ts` and should not be affected by this PR.

2024-11-05 14:46 UTC, burivuhster commented on packages/editor-ui/src/composables/usePushConnection.ts
Ahh, I see your point now. I found that setting `context.functionality` to `configuration-node` on NodeApiError does nothing, as it checks for the functionality on the exception object itself. Now I see that the checks are different for the `configuration-node` functionality and `pairedItem`. Good catch, thank you!

2024-11-08 08:23 UTC, jeanpaul approved these changes
Looks good! thanks for addressing the issues with `context.functionality`, and for adding the extra tests! 👍

2024-11-08 09:17 UTC, merged

2024-11-13 17:11 UTC, janober commented
Got released with [`n8n@1.68.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.68.0)