fix: Update required node js version in CONTRIBUTING.md
n8n-io/n8n pull request #11437
Opened 2024-10-28 15:10 UTC by ShireenMissi

## Summary
in contribution guides we mention 18.10 as the minimum required Node js version, however pnpm 9.x requires 18.12 as the minimum 
here is the error you get by running pnpm on 18.10 
```
pnpm build
ERROR: This version of pnpm requires at least Node.js v18.12
The current version of Node.js is v18.10.0
``` 
This PR updates contribution.md to avoid confusion

## Related Linear tickets, Github issues, and Community forum posts
https://linear.app/n8n/issue/NODE-1932/update-contributingmd-with-minimum-node-version
https://github.com/n8n-io/n8n/issues/10002

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-10-28 15:13 UTC, netroy requested changes
For development, [we already require versions above 20.15](https://github.com/n8n-io/n8n/blob/master/package.json#L6)

2024-10-28 15:29 UTC, ShireenMissi commented on CONTRIBUTING.md
> +[Node.js](https://nodejs.org/en/) version 18.12 or newer is required for development purposes.
@netroy should this be changed to 20.15 then?

2024-10-29 08:40 UTC, netroy approved these changes
Thanks

2024-10-29 08:54 UTC, merged

2024-10-31 15:27 UTC, janober commented
Got released with [`n8n@1.66.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.66.0)