fix(core): Don't send a `executionFinished` event to the browser with no run data if the execution has already been cleaned up
n8n-io/n8n pull request #11502
Opened 2024-11-01 13:44 UTC by despairblue

## Summary

We've been sending multiple `executionFinished` events to the browser when an execution is stopped/cancelled.
We've been doing this for quiet a while now. I've checked at least 6 months back.

The reason for this is that we send the event as soon as the `POST executions/:id/stop` route is called.
But if there is a node currently executing that does not support cancellation it will continue to run and finish. When it finishes we send another `executionFinished` event with the run data of that node added.

Since this [PR](https://github.com/n8n-io/n8n/pull/9992/files) we're sending a third `executionFinished` event with no run data.
That is because the execution is cleaned up while it's still running, which causes a `ExecutionNotFoundError` which is then handled and will send another `executionFinished` event with no data, because the run data has already been cleaned up.

A proper fix would be to not clean up the execution until it finished properly. This here is only a quick fix to alleviate the pain this causes.

Before
TODO add video

After
TODO add video

## Related Linear tickets, Github issues, and Community forum posts

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] ~[Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.~
- [x] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-11-04 09:53 UTC, netroy requested changes

2024-11-04 09:53 UTC, netroy commented on packages/core/src/WorkflowExecute.ts
> +				e.message === 'Workflow has been canceled or timed out')
We should create a new error type, use that on [this line](https://github.com/n8n-io/n8n/blob/master/packages/core/src/WorkflowExecute.ts), and then update this check to not use `e.message`.

2024-11-04 11:45 UTC, netroy approved these changes

2024-11-04 12:04 UTC, merged

2024-11-06 16:24 UTC, janober commented
Got released with [`n8n@1.67.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.67.0)