refactor(editor): Migrate FixedCollectionParameter to composition API
n8n-io/n8n pull request #11555
Opened 2024-11-05 10:17 UTC by ShireenMissi

## Summary
This PR migrates FixedCollectionParameter to composition API

## Related Linear tickets, Github issues, and Community forum posts

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-11-05 10:57 UTC, elsmr requested changes

2024-11-05 10:57 UTC, elsmr commented on packages/editor-ui/src/components/FixedCollectionParameter.vue
> +const props = defineProps<{
use `withDefaults` here to set the same default values as before. Just to be sure the component behaves exactly the same as before.

2024-11-05 10:57 UTC, elsmr commented on packages/editor-ui/src/components/FixedCollectionParameter.vue
> +	isReadOnly: boolean | undefined;
values and isReadOnly should be optional (they don't have required=true in defineComponent)

2024-11-05 10:57 UTC, elsmr commented on packages/editor-ui/src/components/FixedCollectionParameter.vue
> +	if (multipleValues && isINodePropertyCollectionList(props.parameter.options)) {
multipleValues.value

2024-11-05 10:57 UTC, elsmr commented on packages/editor-ui/src/components/FixedCollectionParameter.vue
> +	valueChanged: [value?: any];
Specify a type for `value`. From usage I think it should be something like
```ts
type ValueChangedEvent = { path: string; value: NodeParameterValueType; type?: 'optionsOrderChanged'; }
```

2024-11-05 10:57 UTC, elsmr commented on packages/editor-ui/src/components/FixedCollectionParameter.vue
> +	let newValue;
If possible set a type for newValue, maybe `NodeParameterValueType`

2024-11-05 10:57 UTC, elsmr commented on packages/editor-ui/src/components/FixedCollectionParameter.vue
> +	if (multipleValues) {
multipleValues.value

2024-11-05 10:57 UTC, elsmr commented on packages/editor-ui/src/components/FixedCollectionParameter.vue
> +	return (props.parameter.options as INodePropertyCollection[]).filter((option) => {
I think this type cast is avoidable by doing `props.parameter.options ?? []`, would be safer too 😄

2024-11-06 10:47 UTC, ShireenMissi commented on packages/editor-ui/src/components/FixedCollectionParameter.test.ts
> +	let props: any;
```suggestion
	let props = {};
```

2024-11-06 14:18 UTC, elsmr approved these changes

2024-11-06 14:40 UTC, merged