fix(editor): Make repo preparation cross-platform (no-changelog)
n8n-io/n8n pull request #11628
Opened 2024-11-07 14:06 UTC by mpoc

## Summary

The repository preparation script fails on Windows (cmd and PowerShell) due to cmd incompatible path when using `execSync` in the `prepare.mjs` script.

When running `pnpm install`, the preparation script fails with the following error:

```
. prepare$ node scripts/prepare.mjs
│ '.' is not recognized as an internal or external command,                                                                                                                                    
│ operable program or batch file.
│ node:internal/errors:983
│   const err = new Error(message);                                                                                                                                                            
│               ^                                                                                                                                                                              
│ Error: Command failed: ./node_modules/.bin/lefthook install                                                                                                                                  
│     at genericNodeError (node:internal/errors:983:15)                                                                                                                                        
│     at wrappedFn (node:internal/errors:537:14)                                                                                                                                               
│     at checkExecSyncError (node:child_process:888:11)                                                                                                                                        
│     at execSync (node:child_process:960:15)                                                                                                                                                  
│     at file:///C:/Users/mpoc/src/n8n/scripts/prepare.mjs:10:1                                                                                                                            
│     at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
│     at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
│     at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5) {
│   status: 1,
│   signal: null,
│   output: [ null, null, null ],
│   pid: 17852,
│   stdout: null,
│   stderr: null
│ }
│ Node.js v22.11.0
└─ Failed in 114ms at C:\Users\mpoc\src\n8n
 ELIFECYCLE  Command failed with exit code 1.
```

It happens because `lefthook` is executed directly from the `node_modules` path in this line in `scripts/prepare.mjs`:

```javascript
execSync('./node_modules/.bin/lefthook install', { stdio: 'inherit' });
```

This works fine when using PowerShell directly, but cmd does not resolve `.` as current directory, and cmd is the [default shell on Windows when using `execSync`](https://nodejs.org/api/child_process.html#default-windows-shell).

This change replaces direct execution of `lefthook` with `npx`, which handles cross-platform path resolution automatically:

```javascript
execSync('npx lefthook install', { stdio: 'inherit' });
```

## Related Linear tickets, Github issues, and Community forum posts

N/A

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-11-07 14:31 UTC, Joffcom commented
Hey @mpoc,

Thanks for the PR, We have created "GHC-402" as the internal reference to get this reviewed.

One of us will be in touch if there are any changes needed, in most cases this is normally within a couple of weeks but it depends on the current workload of the team.

2024-12-08 06:34 UTC, dobromyslov commented
Related question in the community: [N8n Installation Giving Issue](https://community.n8n.io/t/n8n-installation-giving-issue/63047).

2024-12-17 15:32 UTC, tomi approved these changes

2025-01-08 10:40 UTC, tomi approved these changes

2025-01-08 10:41 UTC, Joffcom approved these changes

2025-01-08 10:56 UTC, netroy requested changes

2025-01-08 10:56 UTC, netroy commented on scripts/prepare.mjs
> +execSync('npx lefthook install', { stdio: 'inherit' });
We should use `pnpm` instead of `npm` to use the already installed version of `lefthook`
```suggestion
execSync('pnpm lefthook install', { stdio: 'inherit' });
```

2025-01-08 10:58 UTC, netroy commented
closing in favor of the older #11065, which has this exact same fix.

2025-01-08 10:58 UTC, closed without merging