Mailjet add custom campaign ande
n8n-io/n8n pull request #11715
Opened 2024-11-13 10:43 UTC by maximepvrt

## Summary

## Related Linear tickets, Github issues, and Community forum posts

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-11-13 10:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/n8n-io/n8n?pullRequest=11715) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/n8n-io/n8n?pullRequest=11715) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/n8n-io/n8n?pullRequest=11715) it.</sub>

2024-11-13 11:00 UTC, Joffcom commented
Hey @maximepvrt,

Thanks for the PR, We have created "GHC-432" as the internal reference to get this reviewed.

One of us will be in touch if there are any changes needed, in most cases this is normally within a couple of weeks but it depends on the current workload of the team.

2025-01-08 18:18 UTC, maximepvrt commented
any news @Joffcom ?

2025-06-08 18:39 UTC, maximepvrt commented
@ivov @netroy @ggozad @dana-gill 😢😢

2025-08-29 04:31 UTC, michael-radency requested changes
Hello @maximepvrt , thanks for your PR, could you please add tests cobering this change?

2025-11-01 14:05 UTC, maximepvrt commented
@michael-radency, I tried to write a test by modifying the only one I found related to this node. I hope that’s what you had in mind!

2026-01-07 06:35 UTC, michael-radency commented on packages/testing/playwright/tests/cli-workflows/workflows/194.json
> +				}
why this test update needed?
also please add test case to node to cover changes

2026-01-07 06:52 UTC, michael-radency approved these changes
@maximepvrt
thanks for PR, I did add tests, approved :tada:

2026-01-07 11:43 UTC, merged