WIP: feat(n8n AWS Cognito Node): New node
n8n-io/n8n pull request #11767
Opened 2024-11-17 16:25 UTC by valentina98

## Summary

Adds AWS Cognito node. You can find the API documentation [here](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/Welcome.html).

2025-01-22 07:07 UTC, Parvezkhan0 commented on packages/nodes-base/credentials/Aws.credentials.ts
>  				} else if (service === 'rekognition' && credentials.rekognitionEndpoint) {
Add validation to ensure service is defined and valid before constructing the endpoint string.

2025-01-22 07:07 UTC, Parvezkhan0 commented on packages/nodes-base/nodes/Aws/Cognito/AwsCognito.node.ts
> +			{
Use concise messages like "Select a parameter to update this resource" to improve clarity.

2025-01-24 15:44 UTC, adina-hub commented
@Parvezkhan0 this node is still in a review phase, please wait for confirmation to continue.

2025-01-24 15:46 UTC, netroy commented on packages/nodes-base/credentials/Aws.credentials.ts
> -				} else if (service === 'sqs' && credentials.sqsEndpoint) {
why are these lines removed?

2025-01-24 15:48 UTC, adina-hub commented on packages/nodes-base/credentials/Aws.credentials.ts
> -				} else if (service === 'sqs' && credentials.sqsEndpoint) {
It was a duplicate, there was also a comment previously with this as a to-do

2025-02-19 16:05 UTC, ShireenMissi requested changes

2025-02-19 16:05 UTC, ShireenMissi commented on packages/nodes-base/nodes/Aws/Cognito/GenericFunctions.ts
The code in this file is complex and could be significantly simplified. It is hard to read due to excessive type casting, some of which are unnecessary. Additionally, API calls, such as checking if a user is in a group, could be optimised for better readability and efficiency.

2025-02-19 16:24 UTC, gandreini commented on packages/nodes-base/nodes/Aws/Cognito/AwsCognito.node.ts
> +				message: 'Select a parameter to update this resource',
@ShireenMissi yes too generic. Looking at the code it seems that this is fired when I update a user and send no data. We could rephrase it as `Select at least one user field to update`
Same for the warning below about the group

2025-02-21 11:39 UTC, ShireenMissi submitted a review, later dismissed
Could you please update the PR descriptions with details about the changes you made for example what Node was added and all resources/operations
Additionally on the User resource/ Update I find the attributes part hard to fill without checking the API docs
![Screenshot 2025-02-21 at 11 36 48](https://github.com/user-attachments/assets/75e7f4ff-38ec-4d96-88d4-868e92523150)
I think the standard attributes https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html these should be added as named options, and [name, value] pairs can be kept for any custom attributes

2025-03-10 06:42 UTC, adina-hub commented
> Could you please update the PR descriptions with details about the changes you made for example what Node was added and all resources/operations Additionally on the User resource/ Update I find the attributes part hard to fill without checking the API docs ![Screenshot 2025-02-21 at 11 36 48](https://private-user-images.githubusercontent.com/94372015/415626266-75e7f4ff-38ec-4d96-88d4-868e92523150.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE1ODc1MjksIm5iZiI6MTc0MTU4NzIyOSwicGF0aCI6Ii85NDM3MjAxNS80MTU2MjYyNjYtNzVlN2Y0ZmYtMzhlYy00ZDk2LTg4ZDQtODY4ZTkyNTIzMTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzEwVDA2MTM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3YjJlYTJiMDA2OWJlMTEzOWY4ZGRjOGVmMzBjYjhmYjI3ZDhhMDU1ZDZhM2ViYzIzOTU4N2FmZjJkMTliYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dmGHDqPDJr0H0dX8AcE7niF9DXh1omR215_qB8WlXBs) I think the standard attributes https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html these should be added as named options, and [name, value] pairs can be kept for any custom attributes
I implemented this , is this a good approach? @gandreini 
<img width="392" alt="Screenshot-2025-03-03-at-11 28 17AM" src="https://github.com/user-attachments/assets/3a353c78-8efc-4cc9-b63f-d402ef0ebcb7" />

2025-03-10 13:38 UTC, adina-hub commented on packages/nodes-base/nodes/Aws/Cognito/AwsCognito.node.ts
> +		],
@ShireenMissi is this good? 
<img width="1320" alt="Screenshot 2025-03-10 at 3 37 40 PM" src="https://github.com/user-attachments/assets/900f26fb-83ff-447d-9bf9-ebcb90831c1a" />

2025-03-10 21:47 UTC, ShireenMissi commented
> > Could you please update the PR descriptions with details about the changes you made for example what Node was added and all resources/operations Additionally on the User resource/ Update I find the attributes part hard to fill without checking the API docs ![Screenshot 2025-02-21 at 11 36 48](https://private-user-images.githubusercontent.com/94372015/415626266-75e7f4ff-38ec-4d96-88d4-868e92523150.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE1ODc1MjksIm5iZiI6MTc0MTU4NzIyOSwicGF0aCI6Ii85NDM3MjAxNS80MTU2MjYyNjYtNzVlN2Y0ZmYtMzhlYy00ZDk2LTg4ZDQtODY4ZTkyNTIzMTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzEwVDA2MTM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3YjJlYTJiMDA2OWJlMTEzOWY4ZGRjOGVmMzBjYjhmYjI3ZDhhMDU1ZDZhM2ViYzIzOTU4N2FmZjJkMTliYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dmGHDqPDJr0H0dX8AcE7niF9DXh1omR215_qB8WlXBs) I think the standard attributes https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html these should be added as named options, and [name, value] pairs can be kept for any custom attributes
> > I implemented this , is this a good approach? @gandreini
> 
> <img alt="Screenshot-2025-03-03-at-11 28 17AM" width="392" src="https://private-user-images.githubusercontent.com/64439268/420788214-3a353c78-8efc-4cc9-b63f-d402ef0ebcb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE2NDMzMjMsIm5iZiI6MTc0MTY0MzAyMywicGF0aCI6Ii82NDQzOTI2OC80MjA3ODgyMTQtM2EzNTNjNzgtOGVmYy00Y2M5LWI2M2YtZDQwMmVmMGViY2I3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzEwVDIxNDM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhZDQ2ZWY3Mzc2YzJhYmZkYTcxMzRlNGEwODJjMjMzNTZiNGJmZmM4NDU4OWY4OWRiNDUwOTY5NjczM2RlN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-fIINJDDnodjOsiejqQ8L7_UwdnhVTwaCARbkitLQTQ"> <img alt="Screenshot-2025-03-03-at-11 28 26AM" width="408" src="https://private-user-images.githubusercontent.com/64439268/420788760-a5755914-e526-474c-a828-8b9910b0262d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE2NDMzMjMsIm5iZiI6MTc0MTY0MzAyMywicGF0aCI6Ii82NDQzOTI2OC80MjA3ODg3NjAtYTU3NTU5MTQtZTUyNi00NzRjLWE4MjgtOGI5OTEwYjAyNjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzEwVDIxNDM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3OTc0NzM2YmZlOWI1YjU4MWI3OGViNTBmZGEyYTIwOGY1MDYxNTlhMjdlZWNkN2I5OWE2MjVjNWYxYTcxODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ASwC37ianmROP07wKlVBstYjZYfPZov2coZZZTd1Lug">

@adina-hub Thanks for making the changes, what I meant by my comment is actually adding the following options directly so users don't have to look up the API docs to update them 
  name
  family_name
  given_name
  middle_name
  nickname
  preferred_username
  profile
  picture
  website
  gender
  birthdate
  zoneinfo
  locale
  updated_at
  address
  email
  phone_number
  sub

2025-03-11 06:12 UTC, adina-hub commented
@ShireenMissi the code is ready for review.

2025-05-08 09:35 UTC, ShireenMissi reviewed
left some minor comments apart from that looks good 👍

2025-05-08 09:35 UTC, ShireenMissi commented on packages/nodes-base/nodes/Aws/Cognito/descriptions/user/User.resource.ts
> +	...del.description,
please use the same naming convention to keep consistency 
```suggestion
	...delete.description,
```

2025-05-08 09:35 UTC, ShireenMissi commented on packages/nodes-base/nodes/Aws/Cognito/descriptions/user/User.resource.ts
> +import * as del from './delete.operation';
please use the same naming convention to keep consistency
```suggestion
import * as delete from './delete.operation';
```

2025-05-08 09:35 UTC, ShireenMissi commented on packages/nodes-base/nodes/Aws/Cognito/descriptions/group/Group.resource.ts
> +	...del.description,
please use the same naming convention to keep consistency

```suggestion
	...delete.description,
```

2025-05-08 09:35 UTC, ShireenMissi commented on packages/nodes-base/nodes/Aws/Cognito/descriptions/group/Group.resource.ts
> +import * as del from './delete.operation';
please use the same naming convention to keep consistency

```suggestion
import * as delete from './delete.operation';
```

2025-05-08 09:43 UTC, ShireenMissi approved these changes
LGTM 🎉

2025-05-08 09:50 UTC, merged