fix(node): Throw error if GraphQL variables are not objects or strings
n8n-io/n8n pull request #11904
Opened 2024-11-26 16:07 UTC by dana-gill

## Summary

This PR throws an error if the variables set in the GraphQL nodes are neither objects nor strings. This also performs some cleanups to the GraphQL node.

## Related Linear tickets, Github issues, and Community forum posts

Resolves https://linear.app/n8n/issue/NODE-1602/graphql-node-unsuccessful-evaluation-of-variables-expression-silently

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-11-29 13:17 UTC, elsmr requested changes
Good work on the test and cleaning up the code 🙌 I did find a couple blocking bugs

2024-11-29 13:17 UTC, elsmr commented on packages/nodes-base/nodes/GraphQL/GraphQL.node.ts
> -							jsonBody.operationName = null;
I think this behavior was important. With the Linear GraphQL API for example this throws an error now.
You can use the node from the ticket description to reproduce it.

2024-11-29 16:19 UTC, dana-gill commented
PTAL! Specifically the last two commits. If everything looks fine then I'll squash them :)

2024-12-02 10:14 UTC, elsmr approved these changes
LGTM!

2024-12-02 14:18 UTC, Joffcom approved these changes

2024-12-02 16:15 UTC, merged

2024-12-04 13:45 UTC, janober commented
Got released with [`n8n@1.71.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.71.0)