fix(core): Correct invalid WS status code on removing connection
n8n-io/n8n pull request #11901
Opened 2024-11-26 15:35 UTC by ivov

Noticed we were occassionally calling `connection.close(undefined)` leading to:

```
Registered runner "Launcher" (8f2b63d571251e74)
Registered runner "JS Task Runner" (L2FT367NgrN5qekqlrwgQ)
First argument must be a valid error code number
TypeError: First argument must be a valid error code number
    at Sender.close (/Users/ivov/Development/n8n/node_modules/.pnpm/ws@8.17.1/node_modules/ws/lib/sender.js:181:13)
    at WebSocket.close (/Users/ivov/Development/n8n/node_modules/.pnpm/ws@8.17.1/node_modules/ws/lib/websocket.js:308:18)
    at TaskRunnerWsServer.removeConnection (/Users/ivov/Development/n8n/packages/cli/src/runners/runner-ws-server.ts:170:15)
```

2024-11-26 15:46 UTC, netroy requested changes

2024-11-26 15:46 UTC, netroy commented on packages/cli/src/runners/runner-ws-server.ts
> +const WsStatusCodes = {
can we move these to `constants.ts`? that way we can update [push code](https://github.com/n8n-io/n8n/blob/master/packages/cli/src/push/index.ts#L66) to use these as well.

2024-11-26 16:03 UTC, netroy approved these changes

2024-11-26 16:22 UTC, merged

2024-11-27 14:21 UTC, janober commented
Got released with [`n8n@1.70.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.70.0)