feat(editor): Add workflow evaluation run views (no-changelog)
n8n-io/n8n pull request #12258
Opened 2024-12-17 12:00 UTC by OlegIvaniv

## Summary
This pull request extends the test definition feature by adding new views and routes for managing and inspecting test runs, metrics, node pinning, and related execution data. Changes are behind a feature flag and mainly front-end.

**Routes & Views**

- **`/evaluation/:testId/runs` (TEST_DEFINITION_RUNS)**:  
  Lists all runs for a given test definition. Users can navigate from here to individual run details.
  
- **`/evaluation/:testId/runs/:runId` (TEST_DEFINITION_RUNS_DETAIL)**:  
  Displays details for a specific test run, including metrics and linked executions.  

These integrate into the existing `/evaluation` entry point:
- **`/evaluation` (TEST_DEFINITION)**:  
  Lists test definitions, now with actions to start runs and navigate to the test runs page.
  
- **`/evaluation/:testId` (TEST_DEFINITION_EDIT)**:  
  Updated to show node-pinning functionality and allow configuration of metrics and tags. A modal is available for selecting nodes to pin.

https://github.com/user-attachments/assets/43b34b25-b641-479b-ac46-04387886d049

**Key UI Components & Changes**

- **Node Pinning (`NodesPinning.vue`)**:  
  Accessed from the test definition edit view, this modal lets users pin nodes. Pinned nodes keep consistent execution data across test runs.
  
- **Metrics Management (`MetricsInput.vue`, `MetricsChart.vue`)**:  
  Users can define metrics(`MetricsInput.vue`) to track test performance. Metrics are displayed in charts over multiple runs (`MetricsChart.vue`) and handled with CRUD operations for metrics in `useTestDefinitionForm.ts` -> `testDefinition.store.ee.ts` -> `@/api/testDefinition.ee`.

- **N8nSelect & TagsDropdown**:  
  The `N8nSelect` and `TagsDropdown` components have been updated to include a `multipleLimit` prop and to handle tag creation and selection more gracefully.

- **Header Tabs (MainHeader.vue)**:  
  The top navigation now relies on arrays of route names to determine the active tab. This approach supports new test definition routes alongside existing workflow and execution routes.

**State & API Integrations**

- **State Store (testDefinition.store.ee.ts)**:  
  The store now manages:
  - Test runs: fetching all runs for a definition, getting a single run, starting a run, and deleting runs.
  - Metrics: fetching, creating, updating, deleting metrics per test definition.
  It integrates with new API client endpoints defined in `@/api/testDefinition.ee`.

- **TestRunnerService (`test-runner.service.ee.ts`)**:  
  Temporarily includes logic to pass `testRunId` as metadata to evaluation workflow executions. This allows us to fetch executions related to a run.
  *Note:* This is a short-term solution; future backend improvements should supersede this.

**Auto-Save & Polling**

- The test definition edit form auto-saves changes (e.g., description, tags, metrics) after a debounce period.
- The store polls for test runs that are in 'new' or 'running' states, updating their status until completion or error.

## Related Linear tickets, Github issues, and Community forum posts

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2025-01-03 14:27 UTC, alexgrozav requested changes
Found some bugs, and left a few remarks. Feel free to ignore what you feel is not necessary right now.

2025-01-03 14:27 UTC, alexgrozav commented on packages/editor-ui/src/views/TestDefinition/TestDefinitionEditView.vue
>  			<EvaluationHeader
The side panel is cut off while scrolling. 

<img width="515" alt="image" src="https://github.com/user-attachments/assets/b7015d11-6cb5-4872-9ae9-2c401de7bcaa" />

2025-01-03 14:27 UTC, alexgrozav commented on packages/editor-ui/src/components/MainHeader/MainHeader.vue
The workflow is not loaded if you refresh the `tests` page, causing the MainHeader to render blank:

<img width="1583" alt="image" src="https://github.com/user-attachments/assets/c0c59d48-18b5-4618-b58c-4bc84935098a" />

2025-01-06 13:11 UTC, OlegIvaniv commented on packages/editor-ui/src/stores/testDefinition.store.ee.ts
> +		});
Thanks, updated all the computed

2025-01-06 13:14 UTC, OlegIvaniv commented on packages/editor-ui/src/components/TestDefinition/composables/useMetricsChart.ts
> +	const colors = THEME_COLORS[mode];
We already have some logic regarding theme in the store, but unfortunately it wasn't dynamic. For that we'd need to watch the dark mode query and refresh it on change. LMK if these changes make sense to you:
https://github.com/n8n-io/n8n/blob/ce57de94636db35494ce8e9161efc4dabbf42764/packages/editor-ui/src/stores/ui.store.ts#L192-L199

2025-01-06 13:16 UTC, OlegIvaniv commented on packages/editor-ui/src/components/TestDefinition/EditDefinition/NodesPinning.vue
> +			:style="{ opacity: isLoading ? 0 : 1 }"
That's a good point. ✅

2025-01-06 13:16 UTC, OlegIvaniv commented on packages/editor-ui/src/components/MainHeader/MainHeader.vue
> +		}
Updated to a more concise syntax

2025-01-06 13:42 UTC, OlegIvaniv commented on packages/editor-ui/src/components/MainHeader/MainHeader.vue
I'll leave this one out for the P0 bug-fixing phase as it'll require a bit more effort, to get the workflow to load correctly so that the header works.

2025-01-06 14:36 UTC, OlegIvaniv commented
@alexgrozav I addressed all your comments and added a couple more unit tests. Can you please re-review?

2025-01-06 18:16 UTC, alexgrozav submitted a review, later dismissed
Thank you for addressing all the changes! Awesome work!

2025-01-07 09:46 UTC, alexgrozav approved these changes, later dismissed

2025-01-07 11:22 UTC, burivuhster approved these changes

2025-01-07 11:27 UTC, alexgrozav approved these changes

2025-01-07 11:52 UTC, merged

2025-01-09 17:27 UTC, janober commented
Got released with [`n8n@1.74.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.0)