WIP (overhaul): Node google admin overhaul
n8n-io/n8n pull request #12271
Opened 2024-12-17 16:11 UTC by Stamsy

## Summary

Overhaul Google Workspace Admin Node

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-12-17 16:30 UTC, Joffcom commented
Hey @Stamsy,

Thanks for the PR, We have created "GHC-606" as the internal reference to get this reviewed.

One of us will be in touch if there are any changes needed, in most cases this is normally within a couple of weeks but it depends on the current workload of the team.

2024-12-18 07:31 UTC, Bdrake317 reviewed
```
pull request 

```

2025-03-12 14:14 UTC, dana-gill requested changes
Please add tests :)

2025-03-12 14:41 UTC, Stamsy commented
> Please add tests :)

I placed my test in this folder https://github.com/n8n-io/n8n/tree/a068023d71fcf0b60b6a556d2d8c07d0664017dd/packages/nodes-base/nodes/Google/GSuiteAdmin/test . If I need to add anything else to the test, please let me know :)

2025-03-20 16:13 UTC, ShireenMissi requested changes

2025-03-20 16:13 UTC, ShireenMissi commented on packages/editor-ui/src/components.d.ts
Please remove this file

2025-03-20 16:13 UTC, ShireenMissi commented on packages/nodes-base/nodes/Google/GSuiteAdmin/UserDescription.ts
so much code duplication in this file, please reuse the common properties instead of redefining new ones 
you can use displayOptions to control which operation to show the property on 
there are currently 5 properties with name: 'userId'

2025-04-02 16:50 UTC, ShireenMissi submitted a review, later dismissed
Please add more tests to cover the missed lines see [here](https://app.codecov.io/gh/n8n-io/n8n/pull/12271?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=n8n-io) for detailed coverage report

2025-04-02 16:50 UTC, ShireenMissi commented on packages/nodes-base/nodes/Google/GSuiteAdmin/UserDescription.ts
> +				displayName: 'Roles',
this property is duplicated please re use it instead of repeating the same code, this will reduce the number of lines of codes and simplify the code

2025-04-11 15:11 UTC, dana-gill submitted a review, later dismissed
https://app.codecov.io/gh/n8n-io/n8n/pull/13727?dropdown=coverage&src=pr&el=h1

Codecov is still complaining about one of the files not having enough test coverage

2025-04-11 15:16 UTC, Stamsy commented
> https://app.codecov.io/gh/n8n-io/n8n/pull/13727?dropdown=coverage&src=pr&el=h1
> 
> Codecov is still complaining about one of the files not having enough test coverage



> https://app.codecov.io/gh/n8n-io/n8n/pull/13727?dropdown=coverage&src=pr&el=h1
> 
> Codecov is still complaining about one of the files not having enough test coverage

This link directs me to a test related to Microsoft SharePoint.

2025-05-02 16:23 UTC, ShireenMissi approved these changes
LGTM 🎉

2025-05-02 16:27 UTC, merged

2025-05-05 13:10 UTC, janober commented
Got released with [`n8n@1.92.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.92.0)