feat(API): Allow deletion of user from projects
n8n-io/n8n pull request #12329
Opened 2024-12-20 11:44 UTC by MarcL

## Summary

Adds the ability to delete users from projects using the public API endpoint:

```
DELETE /projects/<project-id>/users/<user-id>
```

## Related Linear tickets, Github issues, and Community forum posts

Partially fixes: PAY-1852

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included.
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-12-20 11:51 UTC, MarcL commented on packages/cli/src/public-api/v1/handlers/projects/spec/paths/projects.projectId.yml
> +        type: string
This was missing the `projectId` parameter when run through a validator.

2025-01-15 16:30 UTC, despairblue requested changes

2025-01-15 16:30 UTC, despairblue commented on packages/@n8n/api-types/src/schemas/project.schema.ts
> +	role: projectRoleSchema.exclude(['project:personalOwner']),
I've excluded the `project:personalOwner` here too. Personal projects are special, they can only have one owner with that role. There should not be any API endpoint that allows changing the relation. They are created when the user is created and deleted when the user is deleted.

2025-01-15 16:30 UTC, despairblue commented on packages/cli/src/services/project.service.ee.ts
>  	async syncProjectRelations(
TODO: add a test to make sure this throws when used with personal projects or the personalOwner role.

2025-01-15 16:30 UTC, despairblue commented on packages/cli/src/services/project.service.ee.ts
> +		// TODO: do we need to prevent project owner from being removed?
We don't, as long as this function only works with team projects.

TODO: add test to make sure this function throws when used on a personal project.

2025-01-15 16:30 UTC, despairblue commented on packages/cli/src/services/project.service.ee.ts
> +		// TODO: do we need to block any specific roles here?
Yeah, this function also should only work with team projects and should disallow the personalOwner role.

TODO: add test for this

2025-01-20 17:42 UTC, netroy commented on packages/cli/src/services/project.service.ee.ts
> +type Relation = { userId: string; role: ProjectRole };
can we not use the `ProjectRelation` from `@n8n/api-types`

2025-01-20 17:43 UTC, netroy commented on packages/@n8n/api-types/src/dto/project/add-users-to-project.dto.ts
I think we should definitely keep all public API DTOs in the public-api folder, since they don't need to be shared with editor-ui. but we can do that later in another PR.

2025-01-20 17:44 UTC, netroy commented on packages/@n8n/api-types/src/schemas/project.schema.ts
> +	userId: z.string().min(1),
just to prevent an accidental `"userId": ""` from reaching the controller code.

2025-01-20 17:45 UTC, netroy commented on packages/@n8n/api-types/src/schemas/project.schema.ts
> +	role: projectRoleSchema.exclude(['project:personalOwner']),
I've temporarily reverted this change, to make the build pass again.
Since there is a a lot more projects related types that are still duplicated between packages, I'd like to clean this up later in a separate PR as well.

2025-01-24 16:46 UTC, netroy commented on packages/cli/src/services/project.service.ee.ts
>  	async syncProjectRelations(
done

2025-01-24 16:54 UTC, netroy commented on packages/cli/src/services/project.service.ee.ts
> +	/**
I had to revert the changes to this method to fix the test, but the changes did make sense. I'll try to fix this and add additional tests next week.

2025-04-18 00:28 UTC, csmoakpax8 commented
I would really like to see this happen!

2025-05-23 08:04 UTC, guillaumejacquart approved these changes, later dismissed
Just a small comment, but looks good to me

2025-05-28 08:12 UTC, despairblue commented on packages/cli/src/services/project.service.ee.ts
> +		// TODO: do we need to prevent project owner from being removed?
Test added: https://github.com/n8n-io/n8n/blob/cfdb6ae290e649566d6e895546635205cc0d362b/packages/cli/src/services/__tests__/project.service.ee.test.ts#L221-L233

2025-05-28 08:13 UTC, despairblue commented on packages/cli/src/services/project.service.ee.ts
> +		// TODO: do we need to block any specific roles here?
Test added: https://github.com/n8n-io/n8n/blob/cfdb6ae290e649566d6e895546635205cc0d362b/packages/cli/src/services/__tests__/project.service.ee.test.ts#L215-L219

2025-05-30 09:32 UTC, guillaumejacquart approved these changes

2025-05-30 09:47 UTC, guillaumejacquart approved these changes

2025-05-30 09:49 UTC, shortstacked commented
## Workflow Test Results 📊 🔴 **2 Failed,** ⚠️ 2 Warnings, 👍 79 Successful out of 83 total workflows.
*Detail:* Workflows failing: *237*: Workflow contains 1 deleted data. [View full workflow run](https://github.com/n8n-io/n8n/actions/runs/15344030109)

*Tested Ref:* `1d01094eef5b1651a988269b24c9e6c84c5ece14` by @guillaumejacquart
### ❌ Failed Tests (2)
| Workflow ID | Workflow Name | Reason |
|-------------|---------------|--------|
| 237 | BasicLLMChain:AzureChat | Workflow contains 1 deleted data. |
| 258 | Agent:auto-fix:openai | Workflow contains 2 deleted data. |
### ⚠️ Warnings (2)
| Workflow ID | Workflow Name | Reason |
|-------------|---------------|--------|
| 53 | ConvertKit:CustomField:create getAll update delete... | Workflow contains new data that previously did not exist. |
| 257 | Agent:auto-fix:anthropic | Workflow contains new data that previously did not exist. |

2025-05-30 10:50 UTC, despairblue approved these changes

2025-05-30 11:04 UTC, merged

2025-06-02 15:45 UTC, janober commented
Got released with [`n8n@1.97.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.97.0)