fix(Postgres Node): re-use connection pool across executions
n8n-io/n8n pull request #12346
Opened 2024-12-23 12:30 UTC by despairblue

## Summary

todo

## Related Linear tickets, Github issues, and Community forum posts

todo: add help ticket link

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [x] ~[Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.~
- [ ] Tests included. 
- [x] ~PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)~

2024-12-24 11:06 UTC, netroy requested changes
besides some minor comments, LGTM 🎉.

2024-12-24 11:06 UTC, netroy commented on packages/nodes-base/utils/connection-pool-manager.ts
> +	}
having this in the constructor is a bit confusing. can we move this bit out?
```suggestion
	private map: Map<
			string,
			{ pool: unknown; cleanUpHandler: (pool: unknown) => Promise<void>; lastUsed: number }
		> = new Map()

	/**
	 * Private constructor that initializes the connection pool manager.
	 * Sets up cleanup handlers for process exit and stale connections.
	 */
	private constructor() {
		// Close all SSH connections when the process exits
		process.on('exit', () => this.onShutdown());

		// Regularly close stale SSH connections
		setInterval(() => this.cleanupStaleConnections(), cleanUpInterval);
	}
```

also, we could extract the `{ pool: unknown; cleanUpHandler: (pool: unknown) => Promise<void>; lastUsed: number }` bit into a type, and add jsdocs for each property (for future readability).

2024-12-24 11:06 UTC, netroy commented on packages/nodes-base/utils/connection-pool-manager.ts
> +		cleanUpHandler: (pool: T) => Promise<void>,
should we create a new type `GetConnectionOptions` that extends `Options`, but had `fallBackHandler` and `cleanUpHandler` as fields?
That would make the call to `getConnection` in the nodes code a lot more readable.

2024-12-24 11:50 UTC, netroy approved these changes

2024-12-27 08:15 UTC, merged

2025-01-09 17:06 UTC, janober commented
Got released with [`n8n@1.74.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.1)

2025-01-09 17:08 UTC, janober commented
Got released with [`n8n@1.74.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.1)

2025-01-09 17:11 UTC, janober commented
Got released with [`n8n@1.74.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.0)

2025-01-29 11:19 UTC, akhudolev commented
Hi! It looks like this change caused issues with postgres connections with ssh tunnel
https://github.com/n8n-io/n8n/issues/12807