feat: Make new canvas usable on mobile and touch devices
n8n-io/n8n pull request #12372
Opened 2024-12-26 11:17 UTC by alexgrozav

## Summary

https://github.com/user-attachments/assets/0086afdc-08be-4271-96a5-704dca641fbd

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/CAT-449/make-new-canvas-usable-on-mobile-and-touch-devices

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2025-01-06 08:47 UTC, OlegIvaniv requested changes
This is awesome, so much easier to use n8n on the phone now! I left a few comments. There's also an issue I've stumbled upon when the "try new canvas" tooltip is active, it widens the viewport unexpectedly(Iphone 16 Pro, Brave, IOS 18.2):  

https://github.com/user-attachments/assets/7283103f-20c7-48c6-96da-fed8dc73fdf0

2025-01-06 08:47 UTC, OlegIvaniv commented on packages/editor-ui/src/components/CredentialCard.vue
> +	}
Instead of having global css here and in WorkflowCard, couldn't we move `n8n-card-append` to Card.vue and use variable for the padding with a fallback? Then we'd only need to change it at a single place and without global

2025-01-06 08:47 UTC, OlegIvaniv commented on packages/editor-ui/src/components/CredentialCard.vue
> +		margin-right: auto !important;
We could get rid of this `!important` if we'd use a regular css instead of `mr-xs` in ProjectCardBadge, or use css variable

2025-01-06 08:47 UTC, OlegIvaniv commented on packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
> +	//display: flex;
👁️

2025-01-06 08:47 UTC, OlegIvaniv commented on packages/editor-ui/src/components/Projects/ProjectHeader.vue
> +				<div :class="[$style.icon]">
Nit: no need for array here

2025-01-06 08:47 UTC, OlegIvaniv commented on packages/editor-ui/src/components/WorkflowCard.vue
> +		margin-right: auto !important;
We could get rid of this !important if we'd use a regular css instead of `mr-xs` in ProjectCardBadge, or use css variable

2025-01-06 08:47 UTC, OlegIvaniv commented on packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsList.vue
> +@use 'n8n-design-system/css/mixins/breakpoints' as mixins;
Instead of adding this mixin to all the components, couldn't we just import it once in `packages/design-system/src/css/index.scss`?

2025-01-06 08:47 UTC, OlegIvaniv commented on packages/editor-ui/src/components/forms/ResourceFiltersDropdown.vue
> +		:global(span + span) {
Is this to disable button label margin if there's both icon or label? 🤔 Could you please drop a small comment to clarify

2025-01-06 08:47 UTC, OlegIvaniv commented on packages/editor-ui/src/styles/plugins/_vueflow.scss
> +		max-width: calc(100% - 42px - var(--spacing-s));
42 :D 
![CleanShot 2025-01-06 at 09 39 18](https://github.com/user-attachments/assets/3cb729b2-f49d-4b92-94da-e8963e6624bc)

2025-01-06 13:31 UTC, alexgrozav commented on packages/editor-ui/src/components/CredentialCard.vue
> +	}
Great suggestion! Improved this. Thanks

2025-01-06 13:31 UTC, alexgrozav commented on packages/editor-ui/src/components/CredentialCard.vue
> +		margin-right: auto !important;
Done

2025-01-06 13:31 UTC, alexgrozav commented on packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
> +	//display: flex;
Removed

2025-01-06 13:32 UTC, alexgrozav commented on packages/editor-ui/src/components/Projects/ProjectHeader.vue
> +				<div :class="[$style.icon]">
Removed

2025-01-06 13:32 UTC, alexgrozav commented on packages/editor-ui/src/components/WorkflowCard.vue
> +		margin-right: auto !important;
Done

2025-01-06 13:32 UTC, alexgrozav commented on packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsList.vue
> +@use 'n8n-design-system/css/mixins/breakpoints' as mixins;
Imported all mixins globally via `vite.config.ts`

2025-01-06 13:32 UTC, alexgrozav commented on packages/editor-ui/src/components/forms/ResourceFiltersDropdown.vue
> +		:global(span + span) {
Added a comment

2025-01-06 13:32 UTC, alexgrozav commented on packages/editor-ui/src/styles/plugins/_vueflow.scss
> +		max-width: calc(100% - 42px - var(--spacing-s));
It's magic! Updated to use variables 🙈

2025-01-06 14:44 UTC, OlegIvaniv approved these changes
🚀

2025-01-06 15:09 UTC, merged

2025-01-09 17:07 UTC, janober commented
Got released with [`n8n@1.74.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.1)

2025-01-09 17:09 UTC, janober commented
Got released with [`n8n@1.74.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.1)

2025-01-09 17:11 UTC, janober commented
Got released with [`n8n@1.74.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.0)

2025-01-09 17:27 UTC, janober commented
Got released with [`n8n@1.74.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.0)