fix(core): Validate values which are intentionally 0
n8n-io/n8n pull request #12382
Opened 2024-12-27 10:13 UTC by dana-gill

## Summary

Allow for resource mapper nodes to handle intentional `0` values.

This was especially problematic in the Postgres Insert Node when a user
wants to insert `0` as a value in a table in both Fixed and Expression
mode.

In `validateValueAgainstSchema`, when a resolvedValue is `0`, the value
is considered invalid since in Javascript, `0` is considered a falsey
value which makes `!0` is equal to `true`.

When we are in Expression Mode and value a `0`, we hit
`validateFieldType` with an unparsed number. This means, the value
passed in is a string (ie: `'0'`). This causes `validateFieldType` to
be consider the value as invalid because it check the type of the value
before properly parsing the value.

In addition, having `typeof number` is redundant if we're already
running `tryToParseNumber` since `tryToParseNumber` will throw an error
if it can't parse the number, the error of which is handled outside of
the catch block.

Workflow for testing:

```

```

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/NODE-2085/community-issue-postgres-node-validation-fails-with-0

Resolves https://github.com/n8n-io/n8n/issues/11939

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-12-27 10:16 UTC, dana-gill commented
For now, I'm going to park this issue since getting this work in Expression mode is a challenge since it involves the ResourceMapper. The problem is attemptToConvertTypes is set to false for Expression mode and the value being sent to validateFieldType is the string version of a number (ie: '0'). We somehow need to allow attemptToConvertTypes to be set to true for this to work.

2024-12-27 15:00 UTC, netroy requested changes
besides a minor comment, LGTM

2025-01-02 07:03 UTC, dana-gill commented on packages/core/src/node-execution-context/utils/validateValueAgainstSchema.ts
> +			resolvedValue === undefined
I'll also add a check for `null`. In the worst case, if this change does break things, we can always revert 🫡

2025-01-02 12:21 UTC, dana-gill commented
Well, I'm not 100% what happened, but this now works for Expressions :) So I can say that this resolves #11939

2025-01-08 14:56 UTC, netroy requested changes
can we add

2025-01-08 14:56 UTC, netroy commented on packages/core/src/node-execution-context/utils/validateValueAgainstSchema.ts
> +			resolvedValue === null
Shouldn't this be ?

```suggestion
			(resolvedValue === undefined ||
			resolvedValue === null)
```

2025-01-10 13:43 UTC, netroy approved these changes

2025-01-10 15:11 UTC, merged

2025-01-15 14:32 UTC, janober commented
Got released with [`n8n@1.75.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.75.0)