refactor(editor):  N8nOption type
n8n-io/n8n pull request #12399
Opened 2024-12-30 10:53 UTC by r00gm

## Summary

set the N8nOption 1 to 1 with Element Plus type
https://github.com/element-plus/element-plus/blob/dev/packages/components/select/src/option.vue#L44

this removes a bunch of console warning in dev mode

## Related Linear tickets, Github issues, and Community forum posts

[PAY-2413](https://linear.app/n8n/issue/PAY-2413/fix-n8noption-type)

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-12-30 11:54 UTC, mutdmour approved these changes, later dismissed

2024-12-30 12:01 UTC, netroy requested changes

2024-12-30 12:01 UTC, netroy commented on packages/design-system/src/components/N8nOption/Option.vue
> +	disabled: boolean;
```suggestion
	disabled?: boolean;
```

2024-12-30 12:23 UTC, netroy approved these changes
🤞🏽

2024-12-30 12:46 UTC, merged

2025-01-09 17:06 UTC, janober commented
Got released with [`n8n@1.74.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.1)

2025-01-09 17:08 UTC, janober commented
Got released with [`n8n@1.74.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.1)

2025-01-09 17:11 UTC, janober commented
Got released with [`n8n@1.74.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.0)

2025-01-09 17:27 UTC, janober commented
Got released with [`n8n@1.74.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.0)