Improve node error handling
n8n-io/n8n pull request #1309
Opened 2021-01-05 20:55 UTC by ivov

## Introduction

This is a draft pull request containing **work in progress** on implementing and expanding on [the 2020 MLH Fellowship proposal for standardized error handling](https://hackmd.io/@jh6EYijgQ-GeAm9l3y-a4g/rksOxZkfv).

The original proposal's core idea consists in specifying the path to the relevant values in the API response error object, so that we can standardize the error being thrown and thereby remove duplication.

## Background

For reference, this is the current error handling style:
```ts
if (error.statusCode === 401) {
    // Return a clear error
    throw new Error('The Spotify credentials are not valid!');
}

if (error.statusCode === 403 && error.response.body.message === 'Player command failed: Premium required') {
    throw new Error('You must have Spotify Premium for this operation!');
}

if (error.response && error.response.body && error.response.body.message) {
    // Try to return the error prettier
    throw new Error(`Spotify error response [${error.statusCode}]: ${error.response.body.message}`);
}

// If that data does not exist for some reason return the actual error
throw error;
```

## Original Proposal

We type the error path mapping:

```ts
interface N8nErrorAPI {
    code: string[];
    message: string[];
}
```
And then create it inside the `catch()` block of the API call, pass it to an error standardizer and then to a thrower:

```ts
/* Owned by Individual API Node */
const box2ToN8nErrorAPITransformer: N8nErrorAPI = {
    code: ["error", "error", "status"],
    message: ["error", "error", "message"]
};

const box2ToN8nErrorAPITransformer: N8nErrorAPI = {
    code: ["error", "error", "status"],
    message: ["error", "error", "message"]
};

const errorObj = errorHandler(error, box2ToN8nErrorAPITransformer);

userDisplayNodeError("Spotify", errorObj.code, errorObj.message);
```

Finally, we define the standardization logic (similarly to [_.get](https://lodash.com/docs/4.17.15#get)) and throw an error with a standardized message:

```ts
const recursivelyFindAction = (accumulator, currentValue) => accumulator[currentValue];

/**
* Takes in any API's error response object and uses the provided API to n8n Error Transformer to generate an n8n standard formatted error object.
* @param errorObj {any} - The API's Error Response Object
* @param pathTransformer {N8nErrorAPI} - The paths to parse in the errorObj to fetch the correct values.
* @return {N8nErrorAPIResponse} - The n8n standard API error object
*/
export const errorHandler = (errorObj: object, pathTransformer: N8nErrorAPI): N8nErrorAPIResponse => {
  const apiStandard: N8nErrorAPIResponse = {code: '', message: ''};

  for (const [key, value] of Object.entries(pathTransformer)) {
    apiStandard[key] = value.reduce(recursivelyFindAction, errorObj).toString();
  }

  return apiStandard;
};

const userDisplayNodeError = (nodeName: string, statusCode: string, errorMessage: string): string => {
	throw new Error(`${nodeName} error response [${statusCode}]: ${errorMessage}`);
};
```

## Expanded Proposal

We rename the mapping more explicitly and add a standard error type:

```ts
export interface IN8nErrorPathMapping {
	[key: string]: string[];
	code: string[];
	message: string[];
}

export interface IN8nApiResponseError {
	[key: string]: string;
	code: string;
	message: string;
}
```

We rename the standardizing and throwing functions more explicitly, refactor them under a single one and retype some of them. Note the [`never` type](https://www.typescriptlang.org/docs/handbook/basic-types.html#never) should be used for functions that do not return. 

```ts
/**
 * Standardizes an API response error and throws it.
 *
 * @export
 * @param {string} nodeName
 * @param {object} errorObject
 * @param {IN8nErrorPathMapping} errorPathMapping
 * @returns {never}
 */
export function handleError(
	nodeName: string,
	errorObject: object,
	errorPathMapping: IN8nErrorPathMapping
): never {
	const apiResponseError = standardizeError(errorObject, errorPathMapping);
	throwApiResponseError(nodeName, apiResponseError);
}

/**
 * Converts an API error object into a standard N8N error object based on the error path mapping provided.
 *
 * @export
 * @param {object} errorObject
 * @param {IN8nErrorPathMapping} errorPathMapping
 * @returns {IN8nApiResponseError}
 */
function standardizeError(errorObject: object, errorPathMapping: IN8nErrorPathMapping): IN8nApiResponseError {
	const apiResponseError: IN8nApiResponseError = {
		code: '',
		message: '',
	};

	const findValueRecursively = (accumulator: any, currentValue: any) => accumulator[currentValue]; // tslint:disable-line:no-any

	Object.entries(errorPathMapping).forEach(([key, path]) => {
		apiResponseError[key] = path.reduce(findValueRecursively, errorObject).toString();
	});

	return apiResponseError;
};

/**
 * Throws an error with a standard N8N error message.
 *
 * @export
 * @param {string} nodeName
 * @param {IN8nApiResponseError} apiResponseError
 * @returns {never}
 */
function throwApiResponseError(
	nodeName: string,
	apiResponseError: IN8nApiResponseError,
): never {
	throw new Error(`${nodeName} error response [${apiResponseError.code}]: ${apiResponseError.message}`);
};
```

Finally, we create the mapping and call the handler:

```ts
try {
	return await this.helpers.request!(options);
} catch (error) {

	const errorPathMapping: IN8nErrorPathMapping = {
		code: ["error", "status"],
		message: ["error", "error"],
	};

	handleError("Hacker News", error, errorPathMapping);
}
```

![image](https://user-images.githubusercontent.com/44588767/103697082-2dee5600-4f7e-11eb-8ddb-4f6b2780f7a0.png)

## Open Questions
- Where to place `IN8nErrorPathMapping` and `IN8nApiResponseError`? Is `packages/workflow/src/Interfaces.ts` the proper location?
- Where to place the error handling functionality? Is `packages/core/src/NodeExecutionFunctions.ts` the proper location?
- Can we think of a way to "auto-discover" the API response error object's structure so as to auto-generate the error path mapping?
- How to properly type the parameters to `findValueRecursively`?

2021-01-06 19:27 UTC, ivov commented
Error handling across the 149 nodes in the codebase that use a `request()` method.

Utility nodes (e.g. HTML Extract) and non-request nodes (e.g. Kafka) excluded.

**Compatibility key:**
- Yes: Implemented and operation verified.
- Likely: Error handling through sequential access check.
- Maybe: With adjustments, the proposal might possibly work.
- Unlikely: Even with adjustments, the proposal seems unlikely to work.
- Unknown: The error is just rethrown, so the API docs need to be revisited.

| Node                           | Compatible? | Reason if not compatible        |
|--------------------------------|-------------|---------------------------------|
| Google G Suite Admin           | Yes         |                -                |
| Hacker News                    | Yes         |                -                |
| Spotify                        | Yes         |                -                |
| Affinity                       | Likely      |                -                |
| Airtable                       | Likely      |                -                |
| Automizy                       | Likely      |                -                |
| AWS                            | Likely      |                -                |
| Bannerbear                     | Likely      |                -                |
| Bitbucket                      | Likely      |                -                |
| Bitly                          | Likely      |                -                |
| Brandfetch                     | Likely      |                -                |
| Calendly                       | Likely      |                -                |
| CircleCI                       | Likely      |                -                |
| Clearbit                       | Likely      |                -                |
| ClickUp                        | Likely      |                -                |
| Clickify                       | Likely      |                -                |
| Cockpit                        | Likely      |                -                |
| Coda                           | Likely      |                -                |
| Contentful                     | Likely      |                -                |
| ConvertKit                     | Likely      |                -                |
| Copper                         | Likely      |                -                |
| Cortex                         | Likely      |                -                |
| Customer.io                    | Likely      |                -                |
| Disqus                         | Likely      |                -                |
| Drift                          | Likely      |                -                |
| Dropbox                        | Likely      |                -                |
| Egoi                           | Likely      |                -                |
| EventBrite                     | Likely      |                -                |
| Facebook                       | Likely      |                -                |
| Flow                           | Likely      |                -                |
| FreshDesk                      | Likely      |                -                |
| GetResponse                    | Likely      |                -                |
| Ghost                          | Likely      |                -                |
| GitHub                         | Likely      |                -                |
| GitLab                         | Likely      |                -                |
| Google Sheet                   | Likely      |                -                |
| Google Translate               | Likely      |                -                |
| Gotify                         | Likely      |                -                |
| Gumroad                        | Likely      |                -                |
| Harvest                        | Likely      |                -                |
| HelpScout                      | Likely      |                -                |
| Intercom                       | Likely      |                -                |
| Iterable                       | Likely      |                -                |
| Jira                           | Likely      |                -                |
| Keap                           | Likely      |                -                |
| Line                           | Likely      |                -                |
| LingvaNex                      | Likely      |                -                |
| LinkedIn                       | Likely      |                -                |
| MailChimp                      | Likely      |                -                |
| MailerLite                     | Likely      |                -                |
| Mandrill                       | Likely      |                -                |
| Matrix                         | Likely      |                -                |
| Mattermost                     | Likely      |                -                |
| Mautic                         | Likely      |                -                |
| MessageBird                    | Likely      |                -                |
| Microsoft Excel                | Likely      |                -                |
| Microsoft OneDrive             | Likely      |                -                |
| Microsoft Outlook              | Likely      |                -                |
| Microsoft Teams                | Likely      |                -                |
| Mocean                         | Likely      |                -                |
| MondayCom                      | Likely      |                -                |
| MSG91                          | Likely      |                -                |
| NASA                           | Likely      |                -                |
| NextCloud                      | Likely      |                -                |
| OpenThesaurus                  | Likely      |                -                |
| Orbit                          | Likely      |                -                |
| Paddle                         | Likely      |                -                |
| PagerDuty                      | Likely      |                -                |
| Phantombuster                  | Likely      |                -                |
| Philips Hue                    | Likely      |                -                |
| PipeDrive                      | Likely      |                -                |
| Postmark                       | Likely      |                -                |
| ProfitWell                     | Likely      |                -                |
| Pushbullet                     | Likely      |                -                |
| Pushcut                        | Likely      |                -                |
| Quickbase                      | Likely      |                -                |
| RocketChat                     | Likely      |                -                |
| SignI4                         | Likely      |                -                |
| Spontit                        | Likely      |                -                |
| StoryBlok                      | Likely      |                -                |
| Stripe                         | Likely      |                -                |
| SurveyMonkey                   | Likely      |                -                |
| Telegram                       | Likely      |                -                |
| TheHive                        | Likely      |                -                |
| Todoist                        | Likely      |                -                |
| TravisCI                       | Likely      |                -                |
| Twilio                         | Likely      |                -                |
| Twist                          | Likely      |                -                |
| Typeform                      [...]

2021-03-22 11:35 UTC, krynble requested changes
Great job so far! I like the concept, this will be very helpful.

I had a few issues with existing nodes that were not changed. Can we improve the way we display errors for nodes that weren't changed?

We have some generic `throw new Error()` in the code and they won't display nicely in these cases. See the attached screenshot below. You can see the thrown error on the left side panel.

![Generic throw error](https://user-images.githubusercontent.com/219272/111978634-6aa10680-8b04-11eb-858b-c9669800a045.png)

I have seen this behavior on other nodes like Clickup and Airtable. Either we simply display the error message or nothing at all.

![Clickup node error](https://user-images.githubusercontent.com/219272/111980911-40047d00-8b07-11eb-8d8e-c33e2e02536a.png)

This is related to the `Unknown` nodes in the compatibility table.

2021-03-23 09:42 UTC, BHesseldieck commented on packages/workflow/src/NodeErrors.ts
> +				this.message = UNKNOWN_ERROR_MESSAGE;
agree, we just need to identify the error code first. Need to check what are the most common keys in the nodes that use error-codes 👍🏼

2021-04-13 15:15 UTC, Colton commented
Been having similar issues with trying to implement this kind of error handling for the QuickBase node. This PR looks great! Can't wait to test it out. Thank you @ivov !

2021-04-14 07:35 UTC, ivov commented
Thanks! @BHesseldieck contributed heavily to this as well.

2021-04-16 16:33 UTC, merged

2021-04-16 16:40 UTC, janober commented
Amazing work! Got merged and will be released with the next version.

2021-04-17 16:03 UTC, janober commented
Got released with n8n@0.116.0