Feature/UptimeRobot
n8n-io/n8n pull request #1752
Opened 2021-05-07 09:49 UTC by MedAliMarz

This PR include a node for UptimeRobot with support for:

- Account: getAccountDetails:
- Monitor: create reset getAll update delete
- Alert Contact: create getAll update delete
- Maintenance Window: create getAll update delete
- Public Status Page: create getAll update delete

<details>
<summary>
the next workflow can be used for reviewing the node functionalities
</summary>

```json
{
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        250,
        300
      ]
    },
    {
      "parameters": {},
      "name": "UptimeRobot",
      "type": "n8n-nodes-base.uptimeRobot",
      "typeVersion": 1,
      "position": [
        410,
        20
      ],
      "credentials": {
        "uptimeRobotApi": "Dali UptimeRobotApi creds"
      }
    },
    {
      "parameters": {
        "resource": "monitor",
        "operation": "create",
        "friendly_name": "=Monitor{{Date.now()}}",
        "type": 1,
        "url": "http://n8n.io"
      },
      "name": "UptimeRobot1",
      "type": "n8n-nodes-base.uptimeRobot",
      "typeVersion": 1,
      "position": [
        410,
        290
      ],
      "credentials": {
        "uptimeRobotApi": "Dali UptimeRobotApi creds"
      }
    },
    {
      "parameters": {
        "resource": "monitor",
        "operation": "reset",
        "id": "={{$node[\"UptimeRobot1\"].json[\"id\"]}}"
      },
      "name": "UptimeRobot2",
      "type": "n8n-nodes-base.uptimeRobot",
      "typeVersion": 1,
      "position": [
        580,
        290
      ],
      "credentials": {
        "uptimeRobotApi": "Dali UptimeRobotApi creds"
      }
    },
    {
      "parameters": {
        "resource": "monitor",
        "limit": 1,
        "filters": {}
      },
      "name": "UptimeRobot3",
      "type": "n8n-nodes-base.uptimeRobot",
      "typeVersion": 1,
      "position": [
        740,
        290
      ],
      "credentials": {
        "uptimeRobotApi": "Dali UptimeRobotApi creds"
      }
    },
    {
      "parameters": {
        "resource": "monitor",
        "operation": "update",
        "id": "={{$node[\"UptimeRobot1\"].json[\"id\"]}}",
        "updateFields": {
          "friendly_name": "UpdatedMonitor",
          "url": "http://community.n8n.io"
        }
      },
      "name": "UptimeRobot4",
      "type": "n8n-nodes-base.uptimeRobot",
      "typeVersion": 1,
      "position": [
        890,
        290
      ],
      "credentials": {
        "uptimeRobotApi": "Dali UptimeRobotApi creds"
      }
    },
    {
      "parameters": {
        "resource": "monitor",
        "limit": 1,
        "filters": {
          "monitors": "={{$node[\"UptimeRobot1\"].json[\"id\"]}}"
        }
      },
      "name": "UptimeRobot5",
      "type": "n8n-nodes-base.uptimeRobot",
      "typeVersion": 1,
      "position": [
        1050,
        290
      ],
      "credentials": {
        "uptimeRobotApi": "Dali UptimeRobotApi creds"
      }
    },
    {
      "parameters": {
        "resource": "monitor",
        "operation": "delete",
        "id": "={{$node[\"UptimeRobot1\"].json[\"id\"]}}"
      },
      "name": "UptimeRobot6",
      "type": "n8n-nodes-base.uptimeRobot",
      "typeVersion": 1,
      "position": [
        1220,
        290
      ],
      "credentials": {
        "uptimeRobotApi": "Dali UptimeRobotApi creds"
      }
    },
    {
      "parameters": {
        "resource": "alertContact",
        "operation": "create",
        "friendly_name": "=AlertContact{{Date.now()}}",
        "type": 2,
        "value": "=fakeemail{{Date.now().toString().substr(6)}}@test.com"
      },
      "name": "UptimeRobot7",
      "type": "n8n-nodes-base.uptimeRobot",
      "typeVersion": 1,
      "position": [
        410,
        450
      ],
      "credentials": {
        "uptimeRobotApi": "Dali UptimeRobotApi creds"
      }
    },
    {
      "parameters": {
        "resource": "alertContact",
        "limit": 1,
        "filters": {}
      },
      "name": "UptimeRobot8",
      "type": "n8n-nodes-base.uptimeRobot",
      "typeVersion": 1,
      "position": [
        560,
        450
      ],
      "credentials": {
        "uptimeRobotApi": "Dali UptimeRobotApi creds"
      }
    },
    {
      "parameters": {
        "resource": "alertContact",
        "operation": "update",
        "id": "={{$node[\"UptimeRobot7\"].json[\"id\"]}}",
        "updateFields": {
          "friendly_name": "UpdatedAlertContact"
        }
      },
      "name": "UptimeRobot9",
      "type": "n8n-nodes-base.uptimeRobot",
      "typeVersion": 1,
      "position": [
        700,
        450
      ],
      "credentials": {
        "uptimeRobotApi": "Dali UptimeRobotApi creds"
      }
    },
    {
      "parameters": {
        "resource": "alertContact",
        "operation": "delete",
        "id": "={{$node[\"UptimeRobot7\"].json[\"id\"]}}"
      },
      "name": "UptimeRobot10",
      "type": "n8n-nodes-base.uptimeRobot",
      "typeVersion": 1,
      "position": [
        850,
        450
      ],
      "credentials": {
        "uptimeRobotApi": "Dali UptimeRobotApi creds"
      }
    },
    {
      "parameters": {
        "resource": "mwindows",
        "operation": "create",
        "duration": 5,
        "friendly_name": "=Mwindow{{Date.now()}}",
        "start_time": "2021-05-20T22:00:00.000Z",
        "type": 2,
        "value": "20:30"
      },
      "name": "UptimeRobot11",
      "type": "n8n-nodes-base.uptimeRobot",
      "typeVersion": 1,
      "position": [
        410,
        600
      ],
      "credentials": {
        "uptimeRobotApi": "Dali UptimeRobotApi creds"
      }
    },
    {
      "parameters": {
        "resource": "mwindows",
        "limit": 1,
        "filters": {}
      },
      "name": "UptimeRobot12",
      "type": "n8n-nodes-base.uptimeRobot",
      "typeVersion": 1,
      "position": [
        550,
        600
      ],
      "credentials": {
        "uptimeRobotApi": "Dali UptimeRobotApi creds"
      }
    },
    {
      "parameters": {
        "resource": "mwindows",
        "operation": "update",
        "id": "={{$node[\"UptimeRobot11\"].json[\"id\"]}}",
        "duration": 4,
        "updateFields": {
          "type": 3,
          "value": "1-2"
        }
      },
      "name": "UptimeRobot13",
      "type": "n8n-nodes-base.uptimeRobot",
      "typeVersion": 1,
      "position": [
        700,
        600
      ],
      "credentials": {
        "uptimeRobotApi": "Dali UptimeRobotApi creds"
      }
    },
    {
      "parameters": {
        "resource": "mwindows",
        "limit": 1,
        "filters": {
          "mwindows": "={{$node[\"UptimeRobot11\"].json[\"id\"]}}"
        }
      },
      "name": "UptimeRobot14",
      "type": "n8n-nodes-base.uptimeRobot",
      "typeVersion": 1,
      "position": [
        850,
        600
      ],
      "credentials": {
        "uptimeRobotApi": "Dali UptimeRobotApi creds"
      }
    },
    {
      "parameters": {
        "resource": "mwindows",
        "operation": "delete",
        "id": "={{$node[\"UptimeRobot11\"].json[\"id\"]}}"
      },
      "name": "UptimeRobot15",
      "type": "n8n-nodes-base.uptimeRobot",
      "typeVersion": 1,
      "position": [
        1000,
        600
      ],
      "credentials": {
        "uptimeRobotApi": "Dali UptimeRobotApi creds"
      }
    },
    {
      "parameters": {
        "resource": "psp",
        "operation": "create",
        "friendly_name": "=Psp{{Date.now()}}",
        "monitors": "={{$node[\"UptimeRobot1\"].json[\"id\"]}}",
        "additionalFields": {}
      },
      "name": "UptimeRobot16",
      "type": "n8n-nodes-base.uptimeRobot",
      "typeVersion": 1,
      "position": [
        550,
        130
      ],
      "credentials": {
        "uptimeRobotApi": "Dali UptimeRobotApi creds"
      }
    },
    {
      "parameters": {
        "resource": "psp",
        "limit": 1,
        "filters": {
          "psps": "={{$node[\"UptimeRobot16\ [...]

2021-05-11 14:55 UTC, ivov requested changes
Thanks for taking this on 👍 

Quick code review - node not yet tested.

2021-05-11 14:55 UTC, ivov commented on packages/nodes-base/credentials/UptimeRobotApi.credentials.ts
> +	displayName = 'UptimeRobotApi';
```suggestion
	displayName = 'Uptime Robot API';
```

2021-05-11 14:55 UTC, ivov commented on packages/nodes-base/credentials/UptimeRobotApi.credentials.ts
> +	documentationUrl = 'uptimerobot';
```suggestion
	documentationUrl = 'uptimeRobot';
```

2021-05-11 14:55 UTC, ivov commented on packages/nodes-base/nodes/UptimeRobot/GenericFunctions.ts
> +import { IDataObject, NodeApiError, NodeOperationError, } from 'n8n-workflow';
Multinline imports.

2021-05-11 14:55 UTC, ivov commented on packages/nodes-base/nodes/UptimeRobot/GenericFunctions.ts
> +export async function uptimeRobotApiRequest(this: IExecuteFunctions | IExecuteSingleFunctions | ILoadOptionsFunctions, method: string, resource: string, body: any = {}, qs: IDataObject = {}, uri?: st
Suggestion: Every async function returns a `Promise` and an unspecified return type implies `any`, so you can remove `Promise<any>` while preserving type information, including removal of the TSLint exception.

2021-05-11 16:41 UTC, MedAliMarz commented on packages/nodes-base/nodes/UptimeRobot/UptimeRobot.node.ts
> +		icon: 'file:uptimerobot.png',
I think that's an old logo, maybe we can keep using the current one

2021-05-14 13:53 UTC, ivov requested changes

2021-05-14 13:53 UTC, ivov commented on packages/nodes-base/nodes/UptimeRobot/GenericFunctions.ts
> +			throw new NodeApiError(this.getNode(),responseData.error);
I would think `NodeOperationError` is preferable for these cases, but there are examples of both in the codebase - see [Slack](https://github.com/n8n-io/n8n/blob/5c65a73cc21ac4348eaae6b6b010980ff789cefe/packages/nodes-base/nodes/Slack/GenericFunctions.ts#L60-L62) vs. [ActiveCampaign](https://github.com/n8n-io/n8n/blob/4801510b0cbc86390f8e3ca8eef008c2880f14ec/packages/nodes-base/nodes/ActiveCampaign/GenericFunctions.ts#L55-L57).

Thoughts welcome @BHesseldieck 

Also, no need to specify the `error` property in `responseData.error` - it should be found.

2021-05-14 13:53 UTC, ivov commented on packages/nodes-base/nodes/UptimeRobot/MonitorDescription.ts
> +						name: 'Paused',
```suggestion
						name: 'Pause',
```

2021-05-14 13:53 UTC, ivov commented on packages/nodes-base/nodes/UptimeRobot/UptimeRobot.node.ts
> +		group: [ 'output' ],
Codebase convention is no whitespace inside single-line arrays. Same for elsewhere.
```suggestion
		group: ['output'],
```

2021-05-14 13:53 UTC, ivov commented on packages/nodes-base/nodes/UptimeRobot/UptimeRobot.node.ts
>  			/*                                Maintenance Windows                         */
```suggestion
			/*                                Maintenance Window                         */
```

2021-05-14 13:53 UTC, ivov commented on packages/nodes-base/nodes/UptimeRobot/UptimeRobot.node.ts
>  			/*                               Public Status Pages                          */
```suggestion
			/*                               Public Status Page                          */
```

2021-05-14 13:53 UTC, ivov commented on packages/nodes-base/nodes/UptimeRobot/UptimeRobot.node.ts
>  		const length = items.length as unknown as number;
```suggestion
		const length = items.length;
```

2021-05-14 13:53 UTC, ivov commented on packages/nodes-base/nodes/UptimeRobot/UptimeRobot.node.ts
>  						let parsedStartTime;
Another option:
```
const parsedStartTime = type === 1
	? moment(startTime).unix()
	: moment(startTime).format('HH:mm');
```

2021-05-14 13:53 UTC, ivov commented on packages/nodes-base/credentials/UptimeRobotApi.credentials.ts
> +	displayName = 'Uptime Robot Api';
```suggestion
	displayName = 'Uptime Robot API';
```

2021-05-14 13:53 UTC, ivov commented on packages/nodes-base/nodes/UptimeRobot/GenericFunctions.ts
> +export async function uptimeRobotApiRequest(this: IExecuteFunctions, method: string, resource: string, body: any = {}, qs: IDataObject = {}, uri?: string, option: IDataObject = {}) {
```suggestion
export async function uptimeRobotApiRequest(this: IExecuteFunctions, method: string, resource: string, body: IDataObject = {}, qs: IDataObject = {}, uri?: string, option: IDataObject = {}) {
```

2021-05-14 13:57 UTC, ivov commented
Node functionality tested - all operations working.

Minor details to add to the above:
`HTTP(s)` → `HTTP(S)`
`Web-Hook` → `Webhook`
`mwindows` → `mwindow`

2021-05-17 08:06 UTC, ivov commented on packages/nodes-base/nodes/UptimeRobot/MonitorDescription.ts
> +					},
Capital letter for `name` value.

2021-05-17 08:06 UTC, ivov commented on packages/nodes-base/nodes/UptimeRobot/PublicStatusPageDescription.ts
> +					},
Capital letter for `name` value.

2021-05-17 08:06 UTC, ivov commented on packages/nodes-base/nodes/UptimeRobot/PublicStatusPageDescription.ts
> +				description: 'The sorting of the status page',
```suggestion
				description: 'The sorting of the status page.',
```

2021-05-17 08:06 UTC, ivov commented on packages/nodes-base/nodes/UptimeRobot/PublicStatusPageDescription.ts
> +					},
Capital letter for `name` value.

2021-05-17 11:20 UTC, ivov approved these changes

2021-05-26 20:39 UTC, RicardoE105 commented
Closing this in favor of #1830

2021-05-26 20:39 UTC, closed without merging

2021-05-30 00:42 UTC, janober commented
Thanks a lot. Got merged with #1830

2021-05-30 18:48 UTC, janober commented
Got released with n8n@0.122.0