n8n-2302 Update the webhook URL details UI
n8n-io/n8n pull request #2004
Opened 2021-07-19 12:44 UTC by MedAliMarz

This PR updates the details for the production and test URL for the webhook node.

2021-07-20 13:28 UTC, BHesseldieck requested changes

2021-07-20 13:28 UTC, BHesseldieck commented on packages/editor-ui/src/components/NodeWebhooks.vue
> +				showUrlFor: 'Test URL',
can we keep this as test? maybe even lowercased?
```suggestion
				showUrlFor: 'test',
```

2021-07-20 13:28 UTC, BHesseldieck commented on packages/editor-ui/src/components/NodeWebhooks.vue
> +				if (this.showUrlFor === 'Test URL') {
would need to adjust based on comment above

2021-07-23 15:41 UTC, BHesseldieck approved these changes

2021-07-23 15:42 UTC, merged

2021-07-24 20:38 UTC, janober commented
Got released with n8n@0.131.0