n8n-2305 fix the workflow activation confirmation modal
n8n-io/n8n pull request #2005
Opened 2021-07-19 13:09 UTC by MedAliMarz

This PR make the activation confirmation modal appear only if the workflow is not saved.

2021-07-20 14:14 UTC, BHesseldieck requested changes

2021-07-20 14:14 UTC, BHesseldieck commented on packages/editor-ui/src/components/WorkflowActivator.vue
> +					isDirty: "getStateIsDirty",
names that start with `is` are usually expected to be a function. Would recommend to rather choose a name that is understood as a bool
```suggestion
					dirtyState: "getStateIsDirty",
```

2021-07-20 14:14 UTC, BHesseldieck commented on packages/editor-ui/src/components/WorkflowActivator.vue
> +						if (this.isDirty) {
referring to previous comment
```suggestion
						if (this.dirtyState) {
```

2021-07-22 13:02 UTC, BHesseldieck approved these changes

2021-07-23 07:32 UTC, merged

2021-07-23 07:33 UTC, janober commented
Thanks a lot. Got merged.

2021-07-24 20:37 UTC, janober commented
Got released with n8n@0.131.0