n8n-2303 update webhook response
n8n-io/n8n pull request #2006
Opened 2021-07-19 16:02 UTC by MedAliMarz

This PR adds hints to the webhook invocation response for two cases:

- webhook not registered
- webhook on received response

2021-07-20 15:37 UTC, BHesseldieck requested changes

2021-07-20 15:37 UTC, BHesseldieck commented on packages/cli/src/TestWebhooks.ts
> +				throw new ResponseHelper.ResponseError(`The requested webhook "${httpMethod} ${path}" is not registered.`, 404, 404, `Click the 'Execute workflow' button on the canvas, then try again. (In test m
can we also move this hint to a constant?

2021-07-22 13:02 UTC, BHesseldieck approved these changes
great job!

2021-07-23 18:56 UTC, merged

2021-07-23 18:56 UTC, janober commented
Thanks a lot. Got merged.

2021-07-24 20:37 UTC, janober commented
Got released with n8n@0.131.0