Tributech DSK Nodes
n8n-io/n8n pull request #2125
Opened 2021-08-24 14:25 UTC by mayrmax

Add Nodes for [Tributech DSK](https://docs.tributech.io/docs/introduction/overview) API's:

- Data-API
- Trust-API
- Twin-API
- Catalog-API

I will open a pull request for the documentation soon.

I did my best to follow the node submission checklist, if something is missing please let me know.

2021-09-02 15:11 UTC, krynble commented
Hey @mayrmax 

Thank you for your contribution.

I would like to make some testing before providing feedback. How can I get an account? I went to your website and saw that I'd need to get in touch with a representative and stuff.

Could you share with me a test account? You can contact me directly at omar@n8n.io.

2021-12-29 12:14 UTC, krynble requested changes

2021-12-29 12:14 UTC, krynble commented on packages/nodes-base/nodes/Tributech/descriptions/catalog-api/ManageModelsDescription.ts
> +	{
For `Get all`-like operations we always fetch a single page by default, with the maximum number of items in a single page and add a toggle named `Return All` that automatically iterates over all pages and returns all data in a single execution.

Could you please make this change? This makes it consistent with n8n's expected behavior.

2021-12-29 12:14 UTC, krynble commented on packages/nodes-base/nodes/Tributech/descriptions/twin-api/RelationshipsDescription.ts
> +		options: [
Same as above, related to `Get all` operations. We can remove page number and page size and fetch a single page by default and a `Return all` toggle that makes the node automatically iterate over all pages and return all data in a single execution.

2021-12-29 12:14 UTC, krynble commented on packages/nodes-base/nodes/Tributech/descriptions/twin-api/TwinsDescription.ts
> +		options: [
Same here

2022-09-09 19:43 UTC, Joffcom commented
Hey @mayrmax,

Thanks for the contribution, We have now created a Community Node Repository which is our preferred method for new node submissions.

Once a node has been published to the Community Node Repository users will be able to install the node from their n8n interface and will be able to use your node quicker, You will also be able to update the node as needed without needing to wait for the review process.

In the future we may reach out to you about including your node in our main release, But for now I am going to close this PR.

You can find more information in the links below, If you have any questions about this or need any help let us know.

Building Community Nodes: https://docs.n8n.io/integrations/community-nodes/build-community-nodes/
Submitting Community Nodes: https://docs.n8n.io/integrations/creating-nodes/deploy/submit-community-nodes/
Published Nodes: https://www.npmjs.com/search?q=keywords:n8n-community-node-package

2022-09-09 19:43 UTC, closed without merging