Fixed due_datetime formatting
n8n-io/n8n pull request #2491
Opened 2021-11-28 22:32 UTC by X-pech

Quick fix of #2489

2021-11-29 11:17 UTC, X-pech commented
Also added an option to specify due_string parameter language by 2-character code

2021-12-08 13:46 UTC, krynble requested changes
Hey @X-pech 

Thanks a lot for your contribution!

I requested 2 small changes so we can proceed with merging your PR.

Can you please fix these?

2021-12-08 13:46 UTC, krynble commented on packages/nodes-base/nodes/Todoist/GenericFunctions.ts
> +	returnJsonArray,
Could you please remove this import? I think it was added by mistake.

2021-12-08 13:46 UTC, krynble commented on packages/nodes-base/nodes/Todoist/GenericFunctions.ts
> +import { Console } from 'console';
Same for this one, could you please remove?

2021-12-14 13:18 UTC, krynble approved these changes

2021-12-19 11:41 UTC, merged

2021-12-19 11:41 UTC, janober commented
Thanks a lot. Got merged.

2021-12-19 13:40 UTC, janober commented
Got released with `n8n@0.154.0`