Add logging to user management endpoints v2
n8n-io/n8n pull request #2836
Opened 2022-02-17 15:49 UTC by ivov

To replace #2821

2022-02-21 10:43 UTC, krynble requested changes

2022-02-21 15:49 UTC, ivov commented
FYI changes to migrations were only formatting and hiding logs for test runs.

2022-02-21 16:57 UTC, csuermann commented on packages/cli/src/UserManagement/UserManagementHelper.ts
> +import express = require('express');
why require() instead of import?

2022-02-21 17:13 UTC, ivov commented on packages/cli/src/UserManagement/UserManagementHelper.ts
> +import express = require('express');
> When exporting a module using `export =`, TypeScript-specific `import module = require("module")` must be used to import the module. [Source](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require) and [Express typings export line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/207f8177bfad6b542e5f1cb9b1936af6fb280816/types/express/index.d.ts#L133)

2022-02-22 08:46 UTC, krynble approved these changes

2022-02-22 09:07 UTC, merged