N8N-2961 New expression variables
n8n-io/n8n pull request #2837
Opened 2022-02-17 17:40 UTC by michael-radency

2022-02-23 09:52 UTC, krynble requested changes
Hey @michael-radency amazing job! I just added a tiny change for the sake of consistency.

2022-02-23 09:52 UTC, krynble commented on packages/workflow/src/WorkflowDataProxy.ts
> +									if (!executionData.length) return [];
Just to be consistent, we should return `undefined` here

2022-03-11 08:58 UTC, krynble requested changes

2022-03-13 09:34 UTC, merged

2022-03-13 09:34 UTC, janober commented
Thanks a lot. Got merged.

2022-03-13 11:53 UTC, janober commented
Got released with `n8n@0.167.0`