N8N-2942 new format google ads
n8n-io/n8n pull request #2904
Opened 2022-03-01 08:00 UTC by agobrech

2022-03-01 08:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/n8n-io/n8n?pullRequest=2904) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/n8n-io/n8n?pullRequest=2904) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: agobrech<br/>:x: cgobrech<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/n8n-io/n8n?pullRequest=2904) it.</sub>

2022-03-03 09:28 UTC, krynble requested changes

2022-03-03 09:28 UTC, krynble commented on packages/nodes-base/nodes/Google/Ads/GoogleAds.node.ts
> +						value: 'analytic',
Keep this name consistent with the label to make it easier, so use `analytics` everywhere.

2022-03-03 09:28 UTC, krynble commented on packages/nodes-base/nodes/Google/Ads/InvoiceDescription.ts
> +				name: 'Return invoices',
We can name this one "Search"

2022-03-03 11:05 UTC, agobrech commented on packages/nodes-base/nodes/Google/Ads/GoogleAds.node.ts
> +						url: '/v9/customers:listAccessibleCustomers',
Yes it does work on my end

2022-03-03 11:09 UTC, agobrech commented on packages/nodes-base/nodes/Google/Ads/InvoiceDescription.ts
> +		required: true,
Yes all the fields are required

2022-06-16 14:17 UTC, closed without merging