Discord node v2
n8n-io/n8n pull request #2918
Opened 2022-03-02 13:29 UTC by agobrech

Refactored the work of @Timeraa and added more parameter to the Discord node.

2022-03-21 13:47 UTC, nivb06 commented
Thanks for flagging, was meant to close the [original](https://github.com/n8n-io/n8n/pull/1416) one as this one is in the works on this PR
reopening

2022-03-21 13:48 UTC, Byter09 commented
Yay :D Hopefully we get a review soon

2022-04-13 14:18 UTC, krynble requested changes

2022-04-13 14:18 UTC, krynble commented on packages/nodes-base/nodes/Discord/Discord.node.json
> +	"codexVersion": "2.0",
We can revert these to 1.0

2022-04-13 14:18 UTC, krynble commented on packages/nodes-base/nodes/Discord/Discord.node.ts
> +				name: 'content',
Changing this name actually causes this to become a breaking change; we should keep the `name` the same. The label (`displayName`) could be changed, but it's better to keep it as it was.

2022-04-13 14:18 UTC, krynble commented on packages/nodes-base/nodes/Discord/Discord.node.ts
> +				options: [
Please change this list to be alphabetically ordered

2022-04-13 14:18 UTC, krynble commented on packages/nodes-base/nodes/Discord/Discord.node.ts
> +		body.content =
This change actually introduces another breaking change. We are defaulting the value of the text to be the input field `content`.

If this is intended, then the user should use an expression and set this directly.

Comparing to the original code, I think we should continue with the previous behavior where only declarative data is used and we don't assume behaviors.

2022-04-13 14:18 UTC, krynble commented on packages/nodes-base/nodes/Discord/Discord.node.ts
> +		const webhookUri = this.getNodeParameter('webhookUri', 0, '') as string;
We should move the `webhookUri` variable as well as the `body` to inside the `for` loop since these can be expressions.

2022-04-13 14:18 UTC, krynble commented on packages/nodes-base/nodes/Discord/Discord.node.ts
> +					// }
Please remove the comments if they are not necessary

2022-04-13 14:18 UTC, krynble commented on packages/nodes-base/nodes/Discord/Discord.node.ts
> +					throw new Error('components must be valid JSON.');
Change the word `components` have upper case first letter

2022-04-15 08:04 UTC, merged

2022-04-15 08:04 UTC, janober commented
Thanks a lot. Got merged.

2022-04-19 11:27 UTC, janober commented
Got released with `n8n@0.173.0`