Fix component in executions list failing custom validator
n8n-io/n8n pull request #3284
Opened 2022-05-11 14:53 UTC by ivov

2022-05-24 12:59 UTC, mutdmour requested changes

2022-05-24 15:23 UTC, mutdmour approved these changes

2022-05-27 16:21 UTC, merged

2022-05-27 16:21 UTC, janober commented
Thanks a lot. Got merged.

2022-05-30 12:52 UTC, janober commented
Got released with `n8n@0.179.0`