Allows to ignore Notion URL properties if empty
n8n-io/n8n pull request #3564
Opened 2022-06-20 13:41 UTC by baflo

This PR addresses a problem shown in https://community.n8n.io/t/notion-integration-got-created/3522/23?u=baflo

It adds an option to Notion properties of type `url` that allows to not send the property to Notion API if no value is set.

2022-06-27 13:21 UTC, baflo commented
How can I help so this will be accepted?

2022-07-13 09:16 UTC, agobrech approved these changes

2022-07-18 16:38 UTC, agobrech requested changes
Hey @baflo, thanks for the changes just a small fix: the option is not in the correct location. They have to be alphabetically sorted. After that we can merge it  👍.

2022-07-20 09:38 UTC, agobrech approved these changes

2022-07-20 11:34 UTC, merged

2022-07-20 18:15 UTC, janober commented
Got released with `n8n@0.187.1`