N8N 3949 add cred test to popular nodes
n8n-io/n8n pull request #3668
Opened 2022-07-06 10:58 UTC by agobrech

2022-07-12 13:55 UTC, krynble requested changes

2022-07-12 16:26 UTC, agobrech commented on packages/nodes-base/nodes/Notion/GenericFunctions.ts
> +		if (!uri) {
Yep the code was unnecessary, however I found out we we never make request with Oauth2 even though the credential exists.

2022-07-15 14:20 UTC, merged

2022-07-15 14:20 UTC, janober commented
Thanks a lot. Got merged.

2022-07-20 18:15 UTC, janober commented
Got released with `n8n@0.187.1`