Fix auth on pinned triggers
n8n-io/n8n pull request #3699
Opened 2022-07-12 16:07 UTC by ivov

2022-07-13 07:14 UTC, alexgrozav requested changes

2022-07-13 07:14 UTC, alexgrozav commented on packages/cli/src/Server.ts
> +}
We've got code duplication here. Can we import `findPinnedTrigger` from core instead? (also, make it a standalone helper function in core to have it importable)

2022-07-13 07:14 UTC, alexgrozav commented on packages/cli/src/Server.ts
> +					const pinnedTrigger = findPinnedTrigger(workflowData, pinData);
How do we handle the scenario in which we have multiple pinned triggers? WIll only one get executed?

2022-07-13 07:17 UTC, ivov commented
@alexgrozav This was not sent for review.

2022-07-14 09:04 UTC, alexgrozav approved these changes
Works as expected! Great work.

2022-07-14 09:05 UTC, merged