Suggestions for community nodes repo
n8n-io/n8n pull request #3767
Opened 2022-07-25 08:05 UTC by ivov

2022-08-01 12:42 UTC, BHesseldieck approved these changes

2022-08-01 16:05 UTC, krynble requested changes

2022-08-01 16:27 UTC, ivov commented on packages/cli/src/CommunityNodes/helpers.ts
> +import type { Npm } from '../Interfaces';
Agree, changed to `CommunityPackages`.

2022-08-01 16:27 UTC, ivov commented on packages/cli/src/CommunityNodes/helpers.ts
> +	// This default testing URL is a Postman mock service
Removed.

2022-08-01 16:27 UTC, ivov commented on packages/cli/src/CommunityNodes/packageModel.ts
> +	return findInstalledPackage(packageName) !== undefined;
Great catch! Fixed.

2022-08-01 16:27 UTC, ivov commented on packages/cli/src/api/nodes.api.ts
> +		throw new ResponseHelper.ResponseError('Unauthorized', undefined, 403);
Restored and documented.

2022-08-02 07:16 UTC, krynble approved these changes

2022-08-02 08:40 UTC, merged

2022-08-02 08:41 UTC, janober commented
Thanks a lot. Got merged.

2022-08-03 19:44 UTC, janober commented
Got released with `n8n@0.189.0`