N8n 4168 add node ids
n8n-io/n8n pull request #3788
Opened 2022-07-27 14:23 UTC by mutdmour

2022-07-27 14:48 UTC, mutdmour commented on packages/editor-ui/src/components/Node.vue
> +					{{ node.id }}
TODO REMOVE BEFORE MERGE

2022-08-01 12:29 UTC, BHesseldieck requested changes

2022-08-01 12:29 UTC, BHesseldieck commented on packages/cli/src/PublicApi/v1/handlers/workflows/workflows.service.ts
> +		id: v4(),
why not `uuid()` and importing `v4` twice?

2022-08-01 12:29 UTC, BHesseldieck commented on packages/cli/src/WorkflowHelpers.ts
> +	}
nit:
```suggestion
	nodes.forEach((node) => {
		if (!node.id) {
			node.id = uuid();
		}
	});
```

2022-08-01 12:29 UTC, BHesseldieck commented on packages/cli/src/databases/migrations/mysqldb/1658932910559-AddNodeIds.ts
> +					}
wrong logic + `delete` is indempotent
```suggestion
				  delete node.id;
```

2022-08-01 12:29 UTC, BHesseldieck commented on packages/cli/src/databases/migrations/postgresdb/1658932090381-AddNodeIds.ts
> +				});
wrong logic + `delete` is indempotent 👍🏼 
```suggestion
				nodes.forEach((node) => delete node.id);
```

2022-08-01 12:29 UTC, BHesseldieck commented on packages/cli/src/databases/migrations/sqlite/1658930531669-AddNodeIds.ts
> +				});
nit:
```suggestion
				nodes.forEach((node: INode) => delete node.id);
```

2022-08-01 12:29 UTC, BHesseldieck commented on packages/editor-ui/src/views/canvasHelpers.ts
> +import { v4 as uuidv4} from 'uuid';
nit:
```suggestion
import { v4 as uuid } from 'uuid';
```

2022-08-01 12:29 UTC, BHesseldieck commented on packages/editor-ui/src/views/canvasHelpers.ts
> +		nodes.push({...DEFAULT_START_NODE, id: uuidv4() });
ref previous comment
```suggestion
		nodes.push({...DEFAULT_START_NODE, id: uuid() });
```

2022-08-02 11:07 UTC, BHesseldieck approved these changes

2022-08-03 11:06 UTC, merged

2022-08-03 11:07 UTC, janober commented
Thanks a lot. Got merged.

2022-08-03 19:43 UTC, janober commented
Got released with `n8n@0.189.0`