Remove request libraries from cli package
n8n-io/n8n pull request #3803
Opened 2022-07-29 13:39 UTC by brianinoa

https://linear.app/n8n/issue/N8N-4255/remove-from-cli-package

2022-08-02 12:21 UTC, krynble requested changes

2022-08-02 12:26 UTC, brianinoa commented on packages/cli/src/Server.ts
> +						workflowData = data;
@krynble 👍 Will do that immediately

2022-08-02 12:46 UTC, krynble approved these changes
Nice thanks!

2022-08-02 14:43 UTC, merged

2022-08-02 14:43 UTC, janober commented
Thanks a lot. Got merged.

2022-08-03 19:43 UTC, janober commented
Got released with `n8n@0.189.0`