n8n-4126 credentials injection and testing on specific nodes
n8n-io/n8n pull request #3816
Opened 2022-08-02 07:43 UTC by agobrech

2022-08-11 13:17 UTC, krynble requested changes
Hey Ael!

Thanks for all the effort. I've found some things not working fine and I've left a few comments.

2022-08-11 13:17 UTC, krynble commented on packages/nodes-base/credentials/UProcApi.credentials.ts
> +			baseURL: 'https://api.uproc.io/api/v2/process',
uProc credential test does not seem to work since /me does not exist (returns 404)

2022-08-17 09:04 UTC, agobrech commented on packages/nodes-base/credentials/LemlistApi.credentials.ts
> +		requestOptions.headers!['user-agent'] = 'n8n';
It was in the old authenticate method so I kept it just in case.

2022-08-24 08:25 UTC, krynble approved these changes

2022-08-24 08:26 UTC, merged

2022-08-24 16:07 UTC, janober commented
Got released with `n8n@0.192.0`