n8n-4344-insert-and-update-operations-post-null-values-MongoDB-node
n8n-io/n8n pull request #3901
Opened 2022-08-19 07:23 UTC by michael-radency

2022-08-31 16:20 UTC, krynble requested changes

2022-08-31 16:20 UTC, krynble commented on packages/nodes-base/nodes/MongoDb/MongoDb.node.ts
> +					if (filter[updateKey] === '_id') {
This comparison is wrong, we should change against `updateKey` and not `filter[updateKey]`

2022-08-31 16:20 UTC, krynble commented on packages/nodes-base/nodes/MongoDb/MongoDb.node.ts
> -						delete item['_id'];
Removign the deletion of `_id` is causing the update operation to fail

2022-08-31 16:20 UTC, krynble commented on packages/nodes-base/nodes/MongoDb/MongoDb.node.ts
> +					if (filter[updateKey] === '_id') {
The comparison here is also wrong, making the update based on `_id` to not work

2022-08-31 16:20 UTC, krynble commented on packages/nodes-base/nodes/MongoDb/MongoDb.node.ts
> +					if (filter[updateKey] === '_id') {
Similar issue here

2022-09-01 08:21 UTC, krynble approved these changes

2022-09-01 08:23 UTC, merged

2022-09-01 08:52 UTC, janober commented
Got released with `n8n@0.193.2`