N8N-4134 Add AWS cred testing and http custom calls with credentials
n8n-io/n8n pull request #3924
Opened 2022-08-23 13:29 UTC by agobrech

2022-08-23 16:14 UTC, krynble approved these changes

2022-08-23 16:43 UTC, krynble requested changes

2022-08-23 16:43 UTC, krynble commented on packages/nodes-base/nodes/Aws/S3/GenericFunctions.ts
> +		qs: {
There is something a bit strange happening with s3 node.

I tried to run `File` -> `Get All` to list all files from a bucket and this operation is now failing.

2022-08-23 17:02 UTC, merged

2022-08-24 16:07 UTC, janober commented
Got released with `n8n@0.192.0`