Moving /executions endpoints to separate file
n8n-io/n8n pull request #3952
Opened 2022-08-26 10:29 UTC by freyamade

Moving `/executions` endpoints out of the Server.ts file to their own file and controller

2022-08-26 10:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/n8n-io/n8n?pullRequest=3952) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/n8n-io/n8n?pullRequest=3952) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/n8n-io/n8n?pullRequest=3952) it.</sub>

2022-08-26 15:16 UTC, krynble requested changes
Hey @freyamade it looks great. There is just another small thing: could you please remove the remaining function `getExecutionsCount` from the `Server.ts` file? It is no longer used and can be safely taken away.

2022-08-26 15:17 UTC, freyamade commented
Oh yes I had a slight feeling I was forgetting something I planned, thank you for the reminder :sweat_smile:

2022-08-26 15:27 UTC, krynble approved these changes

2022-08-26 15:31 UTC, merged

2022-08-31 15:28 UTC, janober commented
Got released with `n8n@0.193.0`