feat(core, editor): introduce workflow caller policy
n8n-io/n8n pull request #4368
Opened 2022-10-18 11:50 UTC by ivov

2022-10-20 11:01 UTC, krynble requested changes
Thanks a lot for the PR @ivov 

Small changes suggested. One thing that I'm wondering about is whether or not we should think about an overlap of ownership to allow subworkflow execution.

Maybe it should behave just like credentials? Where at least one of the people with access to the workflow need to also have access to the used credentials. Perhaps implementing the same behavior here, where at least one of the people with access to the parent workflow must have access to the child. Probably not a requirement, but it's worth checking.

2022-10-20 12:46 UTC, ivov commented on packages/cli/config/schema.ts
> +			default: 'any',
Exactly my reasoning.

2022-10-20 12:47 UTC, ivov commented on packages/cli/src/WorkflowExecuteAdditionalData.ts
> +		const allowedCallerIds = workflowData.settings.callerIds.split(',').filter(Boolean);
Added just in case. FE-side I'm disallowing `\s` in the input check.

2022-10-20 12:47 UTC, ivov commented on packages/editor-ui/src/components/WorkflowSettings.vue
> +				<el-row>
Thanks! I keep forgetting there is no BE UM feature branch.

2022-10-20 16:53 UTC, krynble approved these changes
LGTM.
If default behavior should be changed to be more restrictive we can create a small pr to fix it.

2022-10-26 12:59 UTC, merged

2022-10-27 15:29 UTC, janober commented
Got released with `n8n@0.200.0`