refactor(editor): encapsulating canvas actions
n8n-io/n8n pull request #4416
Opened 2022-10-23 22:17 UTC by cstuncsik

2022-10-25 11:58 UTC, cstuncsik commented on packages/editor-ui/src/modules/canvas.ts
> +		const element = nodeViewHtmlElement.value;
do you mean in NDV store?

2022-10-25 12:04 UTC, cstuncsik commented on packages/editor-ui/src/store.ts
> +	// @ts-ignore
Without it my IntelliJ IDE complains (maybe it is just the editor and there is no type error when checked in CI)
![image](https://user-images.githubusercontent.com/5410822/197768482-f8422e28-acae-467b-bd50-3926d4c0f1d1.png)

It should be `process.env.NODE_ENV` anyways

2022-10-25 12:07 UTC, cstuncsik commented on packages/editor-ui/src/components/CanvasControls.vue
> +}
I could agree if it wasn't `position: fixed`.
Since it doesn't matter where we put it in the DOM I see it better packed together.

2022-10-25 12:18 UTC, cstuncsik commented on packages/editor-ui/src/modules/canvas.ts
> +		const element = nodeViewHtmlElement.value;
actually not, I geuss it's Node Details View and it's for different purposes
if you tell wich one do you think of I can move it

2022-10-26 07:55 UTC, mutdmour commented on packages/editor-ui/src/store.ts
> +	// @ts-ignore
it was updated when we moved to the new build system.. I think Alex would know why

2022-10-26 07:59 UTC, mutdmour commented on packages/editor-ui/src/components/CanvasControls.vue
> +}
I see your point.. but still feels ugly to me... but it's your call :)

2022-10-26 08:00 UTC, mutdmour commented on packages/editor-ui/src/modules/canvas.ts
> +		const element = nodeViewHtmlElement.value;
should not the html element stay in the view component? not in any data store?

2022-11-04 10:17 UTC, cstuncsik commented on packages/editor-ui/src/modules/canvas.ts
> +		const element = nodeViewHtmlElement.value;
it's not in the store anymore, it stays in NodeView.vue

2022-11-04 10:18 UTC, cstuncsik commented on packages/editor-ui/src/store.ts
> +	// @ts-ignore
ok, I left it untouched except for the ts-ignore comment

2022-11-05 10:21 UTC, MiloradFilipovic requested changes
The code looks good. Nice job on composition API and dynamic imports.
Just one thing: I am getting errors when scrolling with mouse wheel:
<img width="742" alt="image" src="https://user-images.githubusercontent.com/2598782/200115074-cf53e351-bb0f-40af-8bf8-37f4110e7590.png">

Once that is addressed, it's good to go.

2022-11-07 08:47 UTC, MiloradFilipovic approved these changes
Ok, looks good.

2022-11-07 08:53 UTC, merged

2022-11-10 17:51 UTC, janober commented
Got released with `n8n@0.202.0`