chore(core): fix node-dev Build.ts linting
n8n-io/n8n pull request #4418
Opened 2022-10-24 08:10 UTC by OlegIvaniv

We can safely disable this linting check because the `tsconfig-build.json` file should always be present.

2022-10-24 08:14 UTC, ivov requested changes
Can we please fix using the helper from #4403?

2022-10-24 08:57 UTC, netroy commented
@ivov any idea why the issue wasn't caught in https://github.com/n8n-io/n8n/pull/4403 ?
Is it an issue with the diff plugin?

2022-10-24 09:01 UTC, ivov commented on packages/node-dev/src/Build.ts
> +	const tsConfig = jsonParse<IDataObject>(tsConfigString);
```suggestion
	const tsConfig = jsonParse<{ include: string[] }>(tsConfigString);
```

2022-10-24 09:01 UTC, ivov commented on packages/node-dev/src/Build.ts
> +	for (const includeFile of tsConfig.include as string[]) {
```suggestion
	for (const includeFile of tsConfig.include) {
```

2022-10-24 09:05 UTC, ivov commented
> @ivov any idea why the issue wasn't caught in #4403 ? Is it an issue with the diff plugin?

Exactly, when we add a new rule or increase severity to `error`, we have to run a full lint. I'll add a tech debt story to check and enforce this.

2022-10-24 09:15 UTC, ivov approved these changes

2022-10-24 09:21 UTC, merged

2022-10-27 15:29 UTC, janober commented
Got released with `n8n@0.200.0`