Implement runtime checks for credentials
n8n-io/n8n pull request #4481
Opened 2022-10-31 09:56 UTC by ivov

2022-11-04 12:03 UTC, krynble requested changes
Great work. I think the only necessary change was the one I've mentioned in Linear, where we need to make sure the current user did not tamper the request by changing existing nodes with credentials they don't have access to, neither adding credentials they shouldn't access.

2022-11-09 15:07 UTC, krynble commented on packages/cli/src/UserManagement/PermissionChecker.ts
> +	private static mapCredIdsToNodes(workflow: Workflow) {
I loved the creation of this function, this is very useful in so many places.

2022-11-09 16:02 UTC, krynble submitted a review, later dismissed
LGTM

2022-11-10 11:25 UTC, krynble approved these changes, later dismissed

2022-11-11 10:10 UTC, krynble approved these changes

2022-11-11 10:14 UTC, merged

2022-11-17 18:03 UTC, janober commented
Got released with `n8n@0.203.0`