refactor(editor): remove old execution view route and its dependants
n8n-io/n8n pull request #4651
Opened 2022-11-18 16:14 UTC by cstuncsik

2022-11-19 10:23 UTC, MiloradFilipovic requested changes
Nice job on this. It has been needing a cleanup.
However, you've cut a bit too much with this one: Execution previews are not loading anymore and execution preview canvas doesn't have it's distinct striped background (compared to main node view canvas which have dots).
I have left comments in PR files which parts I think need to get back, but please test and make sure we can still see execution previews after refactor.

2022-11-19 10:23 UTC, MiloradFilipovic commented on packages/editor-ui/src/views/NodeView.vue
> -					this.isExecutionPreview,
We still need this.

2022-11-19 10:23 UTC, MiloradFilipovic commented on packages/editor-ui/src/views/NodeView.vue
> -				isExecutionPreview: false,
And this.

2022-11-19 10:23 UTC, MiloradFilipovic commented on packages/editor-ui/src/views/NodeView.vue
> -			async openExecution(executionId: string) {
And this.

2022-11-19 10:23 UTC, MiloradFilipovic commented on packages/editor-ui/src/views/NodeView.vue
> -							this.isExecutionPreview = false;
This also.

2022-11-19 10:23 UTC, MiloradFilipovic commented on packages/editor-ui/src/views/NodeView.vue
> -					} else if (json && json.command === 'openExecution') {
And this.

2022-11-19 10:23 UTC, MiloradFilipovic commented on packages/editor-ui/src/views/canvasHelpers.ts
> -export const getBackgroundStyles = (scale: number, offsetPosition: XYPosition, executionPreview: boolean) => {
And this.

2022-11-19 10:23 UTC, MiloradFilipovic commented on packages/editor-ui/src/views/canvasHelpers.ts
> -	if (executionPreview) {
And also this.

2022-11-19 10:31 UTC, MiloradFilipovic commented
A bit of context that may be helpful:
We are still using `NodeView` to display executions preview, it's just that it's used inside an `iframe` on _Executions_ tab. So [`openExecution`](https://github.com/n8n-io/n8n/blob/c2da21621fb08c676bd3dc5e2a9de613a4f135f3/packages/editor-ui/src/views/NodeView.vue#L682) function is still needed, but it's only used [here](https://github.com/n8n-io/n8n/blob/c2da21621fb08c676bd3dc5e2a9de613a4f135f3/packages/editor-ui/src/views/NodeView.vue#L3163), so all of [this logic](https://github.com/n8n-io/n8n/blob/c2da21621fb08c676bd3dc5e2a9de613a4f135f3/packages/editor-ui/src/views/NodeView.vue#L2182) in `initView` can go away (which was already done in this PR 🙌). Another thing is the `isExecutionPreview` data member which is used to distinguish `NodeView` used to display workflows from the ones used to preview executions, for now we use it only to set canvas background but it's important none the less.

For reference, this is how canvas should look like:

![SCR-20221119-fmm](https://user-images.githubusercontent.com/2598782/202846366-54a7b99e-cb35-49fa-b9fd-c4bfc664a23e.png)

And this is what I see on this branch

![SCR-20221119-fnv](https://user-images.githubusercontent.com/2598782/202846380-30a9d5e5-fc7a-4d7e-903b-97cc810be882.png)


And this is what I see on this branch:

2023-01-16 08:57 UTC, MiloradFilipovic approved these changes
Looks good to me.

2023-01-16 09:11 UTC, merged

2023-01-16 15:32 UTC, janober commented
Got released with `n8n@0.211.1`