fix: use the updated slots syntax in ResourceLocator (no-changelog)
n8n-io/n8n pull request #4663
Opened 2022-11-21 11:20 UTC by netroy

and remove the eslint exceptions

Follow up to #4652

2022-11-21 12:39 UTC, alexgrozav requested changes

2022-11-21 12:39 UTC, alexgrozav commented on packages/editor-ui/src/components/ResourceLocator/ResourceLocatorDropdown.vue
> +		<slot name="reference" />
This should be:

```
<template #reference>
    <slot />
</template>
```

2022-11-21 14:18 UTC, alexgrozav approved these changes
Looks good to me

2022-11-21 14:28 UTC, merged

2022-11-24 16:21 UTC, janober commented
Got released with `n8n@0.204.0`