feat: Add workflow sharing telemetry
n8n-io/n8n pull request #4906
Opened 2022-12-13 13:25 UTC by alexgrozav

2022-12-14 14:23 UTC, krynble requested changes

2022-12-14 14:23 UTC, krynble commented on packages/editor-ui/src/components/WorkflowCard.vue
> +				this.$telemetry.track('User opened sharing modale', {
```suggestion
				this.$telemetry.track('User opened sharing modal', {
```

2022-12-14 14:25 UTC, alexgrozav commented on packages/editor-ui/src/components/WorkflowCard.vue
> +				this.$telemetry.track('User opened sharing modale', {
Fixed

2022-12-14 14:33 UTC, krynble approved these changes

2022-12-15 08:05 UTC, merged

2022-12-16 14:54 UTC, janober commented
Got released with `n8n@0.208.0`