fix(Schedule Trigger Node): Change scheduler behaviour for intervals days and hours
n8n-io/n8n pull request #5133
Opened 2023-01-11 16:27 UTC by agobrech

Github issue / Community forum post (link here to close automatically):
https://community.n8n.io/t/confused-re-schedule-node-executing-at-the-same-time-every-day/20324?u=mutedjam

2023-01-12 08:33 UTC, krynble requested changes, later dismissed

2023-01-12 08:33 UTC, krynble commented on packages/nodes-base/nodes/Schedule/ScheduleTrigger.node.ts
> +						() => executeTrigger(i, hour, 'hours'),
It's starting to get confusing having these as optional information. We should make this mandatory and change all recurrency rules to send this information and adapt the code to use it whenever needed.

2023-01-12 08:33 UTC, krynble commented on packages/nodes-base/nodes/Schedule/ScheduleTrigger.node.ts
> +				if (hour === 1) {
I think we're now relying too much on the Cron lib and for an execution that should happen every X hours the `setInterval` would be a better approach, WDYT?

2023-01-12 08:33 UTC, krynble commented on packages/nodes-base/nodes/Schedule/ScheduleTrigger.node.ts
> +			} else if (intervalSize && recurrencyRuleIndex !== undefined && typeInterval === 'days') {
This is starting to become a bit spaghetti - maybe refactor to take into accounts scenarios based on the recurrence rule?

2023-02-01 17:13 UTC, maspio approved these changes

2023-02-01 21:53 UTC, merged

2023-02-05 04:26 UTC, janober commented
Got released with `n8n@0.214.0`