test(editor): Enable adding nodes in between any two nodes on canvas in e2e tests (no-changelog)
n8n-io/n8n pull request #5393
Opened 2023-02-07 12:24 UTC by MiloradFilipovic

Github issue / Community forum post (link here to close automatically):

2023-02-07 13:49 UTC, OlegIvaniv requested changes

2023-02-07 13:49 UTC, OlegIvaniv commented on packages/editor-ui/src/utils/nodeViewUtils.ts
> +export const addConnectionTestData = (connectionInfo: ConnectionEstablishedParams) => {
We can make this more DRY be slightly refactoring this method and using it both in NodeView and `addConnectionActionsOverlay`
```
export const addConnectionTestData = (
	source: HTMLElement,
	target: HTMLElement,
	el: HTMLElement,
) => {
	const sourceNodeName = source.getAttribute('data-name')?.toString();
	const targetNodeName = target.getAttribute('data-name')?.toString();

	if (el && sourceNodeName && targetNodeName) {
		el.setAttribute('data-source-node', sourceNodeName);
		el.setAttribute('data-target-node', targetNodeName);
	}
};
```

And then in `addConnectionActionsOverlay` it's just `addConnectionTestData(component.source, component.target, div);` 
And in NodeView: 
```
if ('canvas' in info.connection.connector) {
							setTimeout(() => {
								NodeViewUtils.addConnectionTestData(
									info.source,
									info.target,
									info.connection.connector.canvas as HTMLElement,
								);
							}, 0);
						}
```

2023-02-07 14:32 UTC, OlegIvaniv approved these changes

2023-02-07 15:34 UTC, merged

2023-02-10 17:15 UTC, janober commented
Got released with `n8n@0.215.0`