feat(core): Augment data instead of copying it
n8n-io/n8n pull request #5487
Opened 2023-02-15 10:43 UTC by janober

Currently, Code & Function-Nodes copy a lot of data just to make sure that not by accident anything that should not change gets changed. This PR will enable the same but just in a cheaper way.

Still incomplete and WIP. Esp. support for arrays is still missing.

2023-03-15 11:56 UTC, flipswitchingmonkey requested changes
I think this approach works, but it feels like we are re-inventing a number of things that we could get out of the box by using prototype chaining instead. As an example:

```ts
interface SomeObject {
  [key:string]: any;
  title: string;
  version: string;
  data: number;
}

const parent: SomeObject = {
  title: "Parent",
  version: "1",
  data: 1,
}
Object.freeze(parent);

const child1: SomeObject = Object.create(parent);
child1.title = "Child1";
child1.version = "1.1";
parent.data = 5;  // does not change!

const child2: SomeObject = Object.create(parent);
child2.title = "Child2";
child2.version = "1.2";

Object.freeze(child1);
child1.title = "Changed"; // does not change!

const grandChild: SomeObject = Object.create(child1);
grandChild.title = "GrandChild";
grandChild.version = "1.1.1";

function print(o: SomeObject) {
  console.log(`${o.title} version: ${o.version} data: ${o.data} parent: ${o.__proto__.title}`);
}

print(parent); // 'Parent version: 1 data: 1 parent: undefined'
print(child1); // 'Child1 version: 1.1 data: 1 parent: Parent'
print(child2); // 'Child2 version: 1.2 data: 1 parent: Parent'
print(grandChild); // 'GrandChild version: 1.1.1 data: 1 parent: Child1'
```

2023-03-16 11:11 UTC, netroy reviewed
We might be able to replace reflect-metadata calls with prototype chaining for possibly better performance. but that can be done in another PR.

2023-03-16 11:46 UTC, flipswitchingmonkey submitted a review, later dismissed

2023-03-16 12:22 UTC, netroy commented on packages/workflow/src/WorkflowDataProxy.ts
>  			? deepCopy(connectionInputData)
after testing with a bunch of different JSON sizes, and multiple code-nodes in a workflow, I'm certain that the pros of using `augmentArray` here significantly out-weigh any cons.

2023-03-16 13:28 UTC, netroy approved these changes

2023-03-16 14:14 UTC, merged

2023-03-26 16:04 UTC, janober commented
Got released with [`n8n@0.221.2`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.221.2)

2023-03-26 16:09 UTC, janober commented
Got released with [`n8n@0.221.2`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.221.2)