feat: Add feature flag evaluation server side
n8n-io/n8n pull request #5511
Opened 2023-02-20 05:16 UTC by mutdmour

Github issue / Community forum post (link here to close automatically):

2023-02-20 18:14 UTC, OlegIvaniv requested changes
Looking good! 👏  Left just a few minor comments

2023-02-20 18:14 UTC, OlegIvaniv commented on packages/cli/src/UserManagement/UserManagementHelper.ts
> +	return Promise.race([fetchPromise, timeoutPromise]);
Ha, love this workaround!

2023-02-21 04:10 UTC, mutdmour commented on packages/editor-ui/src/stores/posthog.ts
> +		// todo check why Date is used there
fixed.. removed Date type from this. thanks

2023-02-21 04:12 UTC, mutdmour commented on packages/editor-ui/src/stores/posthog.ts
> +	const init = (bootstrapped?: FeatureFlags) => {
will rename to something clearer

2023-02-21 04:17 UTC, mutdmour commented on packages/editor-ui/src/stores/posthog.ts
> +				onLogout();
alright will make the change

2023-02-21 04:18 UTC, mutdmour commented on packages/editor-ui/src/stores/posthog.ts
> +				onLogout();
went back and forth this. might be clearer if all posthog related code is together.. but it's simpler to understand without the watch. will keep for now

2023-02-21 04:21 UTC, mutdmour commented on packages/editor-ui/src/stores/posthog.ts
> +				onLogout();
nvm moved it to logout

2023-02-21 08:15 UTC, MiloradFilipovic approved these changes
Looks to me all revew comments are addressed.

2023-02-21 08:35 UTC, merged

2023-02-24 16:51 UTC, janober commented
Got released with `n8n@0.217.1`