:zap: Add user activation survey
n8n-io/n8n pull request #5677
Opened 2023-03-13 01:52 UTC by RicardoE105

Github issue / Community forum post (link here to close automatically):

2023-03-13 22:25 UTC, madgbec reviewed
How do I know which cards to activate I have many

2023-03-14 19:34 UTC, RicardoE105 commented
@madgbec can you please elaborate?

2023-03-20 19:36 UTC, madgbec commented
yes I was hoping to get a tutorial on the procees


Sent from Yahoo Mail for iPhone


On Tuesday, March 14, 2023, 12:34, Ricardo Espinoza ***@***.***> wrote:




@madgbec can you please elaborate?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-04-04 09:05 UTC, krynble requested changes
I'd ask you to centralise all actions that update the user settings in the `user.service.ts` and perhaps, to prevent misuse, read data from db first, merge incoming settings and then save, wdyt? Simply because if a user is logged in on multiple devices or this might cause override when we add more settings in the future.

2023-04-04 10:44 UTC, OlegIvaniv commented on packages/editor-ui/src/components/UserActivationSurveyModal.vue
> +							ref="input"
Nit: This ref doesn't seem necessary

2023-04-04 10:46 UTC, OlegIvaniv commented on packages/editor-ui/src/components/UserActivationSurveyModal.vue
> +import { USER_ACTIVATION_SURVEY_MODAL } from '../constants';
Nit: IMO: We should use aliased import in case we decide to move this file

2023-04-11 10:29 UTC, krynble approved these changes
BE code looks great. Thanks!

2023-04-11 16:43 UTC, merged

2023-04-12 08:58 UTC, netroy commented
@RicardoE105 the newly added e2e test is failing on this branch, as well as on master.