feat(editor): Recommend and pre-select auth type with overrides
n8n-io/n8n pull request #5684
Opened 2023-03-14 10:02 UTC by MiloradFilipovic

2023-03-16 14:49 UTC, RicardoE105 requested changes

2023-03-16 15:49 UTC, MiloradFilipovic commented on packages/editor-ui/src/utils/nodeTypesUtils.ts
> +					const cred = getNodeCredentialForSelectedAuthType(nodeType, option.value);
Nice catch. Updated.

2023-03-17 02:05 UTC, RicardoE105 approved these changes

2023-03-17 08:01 UTC, merged

2023-03-26 16:04 UTC, janober commented
Got released with [`n8n@0.221.2`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.221.2)

2023-03-26 16:09 UTC, janober commented
Got released with [`n8n@0.221.2`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.221.2)