docs: Refer to docker.n8n.io/n8nio/n8n for pulling n8n docker images (no-changelog)
n8n-io/n8n pull request #5763
Opened 2023-03-23 13:55 UTC by csuermann

2023-03-23 14:00 UTC, netroy commented on docker/images/n8n/README.md
>  docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --build-arg N8N_VERSION=<VERSION> -t n8nio/n8n:<VERSION> .
should we change this from `n8nio/n8n:<VERSION>` to `n8n:<VERSION>`. no one building an image should be using the org-name in the tag.

2023-03-23 14:01 UTC, netroy requested changes
besides the comments, LGTM

2023-03-23 14:10 UTC, netroy approved these changes

2023-03-23 14:38 UTC, merged

2023-03-30 15:46 UTC, janober commented
Got released with [`n8n@0.222.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.222.0)