feat(core): Convert eventBus controller to decorator style and improve permissions
n8n-io/n8n pull request #5779
Opened 2023-03-24 15:44 UTC by flipswitchingmonkey

Github issue / Community forum post (link here to close automatically):

2023-03-24 16:21 UTC, netroy requested changes

2023-03-24 16:21 UTC, netroy commented on packages/cli/src/eventbus/eventBus.controller.ts
> +				return res.send({
this could be reverted to `return result;`

2023-03-24 16:21 UTC, netroy commented on packages/cli/src/eventbus/eventBus.controller.ts
> +		return res.send({
same here

2023-03-24 16:21 UTC, netroy commented on packages/cli/src/eventbus/eventBus.controller.ts
> +				return res.send({
all instances of `return res.send({ data: xyz })` can be replaced with `return xyz`.

2023-03-24 16:21 UTC, netroy commented on packages/cli/src/eventbus/eventBus.controller.ts
> +		return res.send({
same here.

2023-03-24 16:21 UTC, netroy commented on packages/cli/src/eventbus/eventBus.controller.ts
> +		return res.send({
same here

2023-03-24 16:21 UTC, netroy commented on packages/cli/src/eventbus/eventBus.controller.ts
> +		return res.send({
and here

2023-03-24 16:58 UTC, netroy submitted a review, later dismissed
I propose a few more changes in [this](https://github.com/n8n-io/n8n/commit/f401972a85e3a7c36f9a0f0d7f79542b6288d277) commit. but please free to cherry-pick or not.

2023-03-24 17:03 UTC, netroy commented on packages/cli/src/eventbus/eventBus.controller.ts
> +			amount = parseInt(req.query?.amount as string);
since `req.query` will always be an object, this line will never throw. instead you'd end up with `amount` = `NaN` for invalid values of `amount`

2023-03-27 07:57 UTC, netroy approved these changes

2023-03-27 10:30 UTC, merged

2023-04-19 08:49 UTC, janober commented
Got released with [`n8n@0.223.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.223.0)