feat(core): Prevent non owners password reset when saml is enabled
n8n-io/n8n pull request #5788
Opened 2023-03-27 13:48 UTC by flipswitchingmonkey

2023-03-30 10:14 UTC, netroy commented on packages/cli/src/controllers/passwordReset.controller.ts
> +			throw new InternalServerError(
I think we should throw an `UnauthorizedError` instead.

2023-03-30 10:15 UTC, netroy requested changes
besides the error type, LGTM

2023-03-30 10:21 UTC, netroy approved these changes

2023-03-30 10:44 UTC, merged

2023-04-19 08:49 UTC, janober commented
Got released with [`n8n@0.223.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.223.0)