feat(editor): Enable saving workflow when node details view is open
n8n-io/n8n pull request #5856
Opened 2023-03-31 09:04 UTC by MiloradFilipovic

This one should enable saving current workflow from NDV. Please mind that saving cannot be performed while editable text inputs are focused, so this popup message should indicate when wf is saved successfully:
![image](https://user-images.githubusercontent.com/2598782/229076601-87a4b966-d672-4d0f-b48d-e154a4f0d6ae.png)

Fixes ADO-511

2023-03-31 09:31 UTC, OlegIvaniv requested changes
Love this change! There's just one thing that needs fixing and it would be great to add an e2e spec for this

2023-03-31 09:31 UTC, OlegIvaniv commented on packages/editor-ui/src/views/NodeView.vue
> +			document.addEventListener('keyup', this.keyUp, { capture: true, once: false });
Setting `capture: true` here breaks keyboard shortcuts in NodeCreator panel, for example CMD-A, CMD-C, CMD-V

2023-03-31 11:15 UTC, OlegIvaniv approved these changes

2023-03-31 11:59 UTC, merged

2023-04-19 08:48 UTC, janober commented
Got released with [`n8n@0.223.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.223.0)