feat(HTTP Request Node): Follow redirects by default
n8n-io/n8n pull request #5895
Opened 2023-04-03 15:45 UTC by agobrech

2023-04-03 16:05 UTC, netroy commented on packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
> +			if (redirect?.redirect?.followRedirects || (nodeVersion >= 5 && redirect === undefined)) {
You could extract the repeated check into a separate variable
```typescript 
const autoRedirect = nodeVersion >= 5 && redirect === undefined;
if (autoRedirect || redirect?.redirect?.followRedirects) {
```

2023-04-03 16:09 UTC, netroy approved these changes, later dismissed
besides the one comment, LGTM

2023-04-03 16:30 UTC, csuermann reviewed
How would this PR affect the user experience in the UI? The HTTP Request Node already has an option toggle for following redirects. I would somehow expect this toggle to be set by default in v5?!

2023-04-03 16:33 UTC, agobrech commented
> How would this PR affect the user experience in the UI? The HTTP Request Node already has an option toggle for following redirects. I would somehow expect this toggle to be set by default in v5?!

With this PR if the toggle is not in the UI it will follow redirects, however if you add the toggle it will already be set as false.

2023-04-03 16:41 UTC, netroy commented on packages/nodes-base/nodes/HttpRequest/HttpRequest.node.ts
> +			5: new HttpRequestV3(baseDescription),
considering that v4 was added only 3 days ago, and isn't out in any release, maybe we should use v4 for this check as well.

2023-04-03 16:42 UTC, csuermann commented
> With this PR if the toggle is not in the UI it will follow redirects, however if you add the toggle it will already be set as false.

My point is: As the toggle already exists, shouldn't it be also visibly switched on in the UI to clearly express the new default behavior? It probably shouldn't be an optional property either then, no?

2023-04-03 17:33 UTC, netroy requested changes, later dismissed
If I add the `Redirects` option, the flag is correctly enabled, and redirects work as expected. But, when the option isn't added to the node, the behavior is defaulting to the same as in v1-3.

2023-04-04 14:15 UTC, netroy approved these changes, later dismissed
LGTM

2023-04-05 13:19 UTC, netroy approved these changes

2023-04-05 13:37 UTC, merged

2023-04-19 08:48 UTC, janober commented
Got released with [`n8n@0.223.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.223.0)