feat(editor): SAML paywall state
n8n-io/n8n pull request #5906
Opened 2023-04-04 14:55 UTC by cstuncsik

2023-04-04 15:25 UTC, flipswitchingmonkey requested changes

2023-04-04 15:25 UTC, flipswitchingmonkey commented on packages/editor-ui/src/plugins/i18n/locales/en.json
> +	"settings.sso.actionBox.description": "Use Single Sign On to consolidates authentication into a single platform to improve security and agility.",
consolidate (no s)

2023-04-05 09:43 UTC, flipswitchingmonkey approved these changes, later dismissed

2023-04-07 11:05 UTC, alexgrozav approved these changes

2023-04-07 11:14 UTC, OlegIvaniv approved these changes

2023-04-07 11:29 UTC, merged

2023-04-19 08:50 UTC, janober commented
Got released with [`n8n@0.224.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.224.0)