refactor: Set up Cypress as pnpm workspace (no-changelog)
n8n-io/n8n pull request #6049
Opened 2023-04-21 09:34 UTC by ivov

https://linear.app/n8n/issue/N8N-5644/set-up-linting-for-cypress

2023-04-21 12:27 UTC, OlegIvaniv requested changes
The e2e pipeline is failing with these changes :/ 
https://github.com/n8n-io/n8n/actions/runs/4764774969/jobs/8469859284 

You can trigger e2e pipeline for this specific branch running `gh workflow run e2e-tests.yml --ref n8n-6365 ` if you have Github CLI installed

2023-04-21 12:27 UTC, OlegIvaniv commented on cypress/package.json
> +  }
I wonder, if we separate the Cypress packages, would they get installed & cached by `e2e-reusable` install job?

2023-04-21 12:27 UTC, OlegIvaniv commented on .github/workflows/e2e-reusable.yml
> +          config-file: /__w/n8n/n8n/cypress/cypress.config.js
The e2e specs are now failing, we might have to add /cypress to the caching path similiar to /packages:
```
- name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: |
            /github/home/.cache
            /github/home/.pnpm-store
            ./node_modules
            ./packages
          key: ${{ inputs.cache-key }}
          
```

2023-05-02 08:02 UTC, ivov commented
Marking as draft till next tech debt day

2023-07-31 09:12 UTC, ivov commented
To revisit at a later time.

2024-06-10 13:02 UTC, netroy approved these changes
rebased and fixed this up.

[tests also pass now](https://github.com/n8n-io/n8n/actions/runs/9448641273).

2024-06-10 13:38 UTC, OlegIvaniv approved these changes

2024-06-10 13:49 UTC, merged

2024-06-12 14:06 UTC, janober commented
Got released with [`n8n@1.46.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.46.0)