refactor: Integrate `consistent-type-imports` in FE packages (no-changelog)
n8n-io/n8n pull request #6060
Opened 2023-04-21 13:54 UTC by ivov

https://linear.app/n8n/issue/N8N-6054/integrate-consistent-type-imports-in-fe-packages

2023-04-24 10:03 UTC, cstuncsik approved these changes

2023-04-24 10:18 UTC, merged

2023-04-24 10:39 UTC, OlegIvaniv requested changes
Nice one! I found a few cases where we could adjust/remove imports. It seems like the linting is not triggered for imports which are not used

2023-04-24 10:39 UTC, OlegIvaniv commented on packages/editor-ui/src/api/workflows.ts
> +import { ExecutionStatus, WorkflowExecuteMode } from 'n8n-workflow';
These two should also be import type, no? But also, they are not used in this file so could be deleted

2023-04-24 10:39 UTC, OlegIvaniv commented on packages/editor-ui/src/components/Node.vue
> +import { IDataObject, NodeHelpers } from 'n8n-workflow';
IDataObject is type, but it's not used in the file

2023-04-24 10:39 UTC, OlegIvaniv commented on packages/editor-ui/src/components/Node.vue
> +import { INodeUpdatePropertiesInformation } from '@/Interface';
INodeUpdatePropertiesInformation is type, but it's not used in the file

2023-04-24 10:39 UTC, OlegIvaniv commented on packages/editor-ui/src/components/Node/NodeCreator/MainPanel.vue
> +import { INodeTypeNameVersion } from 'n8n-workflow';
INodeTypeNameVersion is type but not used in this file

2023-04-24 10:39 UTC, OlegIvaniv commented on packages/editor-ui/src/components/ParameterInput.vue
> +import { NodeHelpers, NodeParameterValue } from 'n8n-workflow';
NodeParameterValue is type but not used in the file

2023-04-24 10:39 UTC, OlegIvaniv commented on packages/editor-ui/src/components/ParameterInputWrapper.vue
> +import { IRunData, isResourceLocatorValue } from 'n8n-workflow';
IRunData is type but not used in the file

2023-04-24 10:39 UTC, OlegIvaniv commented on packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
> +import { INodeListSearchResult } from 'n8n-workflow';
INodeListSearchResult is type but not used in the file

2023-04-24 10:39 UTC, OlegIvaniv commented on packages/editor-ui/src/components/SettingsLogStreaming/EventDestinationSettingsModal.ee.vue
> +} from 'n8n-workflow';
Should enums be also imported as type? If so, `MessageEventBusDestinationTypeNames` should be included

2023-04-24 10:39 UTC, OlegIvaniv commented on packages/editor-ui/src/components/Sticky.vue
> +import { IDataObject } from 'n8n-workflow';
IDataObject is type but not in the file

2023-04-24 10:39 UTC, OlegIvaniv commented on packages/editor-ui/src/components/VariableSelector.vue
> +import { IExecutionResponse } from '@/Interface';
IExecutionResponse is type but not in the file

2023-04-24 10:39 UTC, OlegIvaniv commented on packages/editor-ui/src/mixins/restApi.ts
> +import { INodeTranslationHeaders } from '@/Interface';
INodeTranslationHeaders is type but not included in the file

2023-04-24 10:39 UTC, OlegIvaniv commented on packages/editor-ui/src/mixins/workflowHelpers.ts
> +import { INodeTypeData, IPinData, NodeHelpers, deepCopy } from 'n8n-workflow';
INodeTypeData, IPinData are types but not in the file

2023-04-24 10:39 UTC, OlegIvaniv commented on packages/editor-ui/src/permissions.ts
> +import { IRootState, EnvironmentVariable } from '@/Interface';
None of these are used in the file, the import could be removed

2023-04-24 10:39 UTC, OlegIvaniv commented on packages/editor-ui/src/stores/segment.ts
> +import type { INodeTypeDescription, IRun } from 'n8n-workflow';
The two `n8n-workflow` imports could be merged

2023-04-24 10:39 UTC, OlegIvaniv commented on packages/editor-ui/src/stores/workflows.ts
> +import type { IDataObject } from 'n8n-workflow';
Could be merged with import above

2023-04-24 10:39 UTC, OlegIvaniv commented on packages/editor-ui/src/utils/typeGuards.ts
> +import type { NewCredentialsModal } from './../Interface';
Is same as `@/Interface` import below

2023-04-24 10:39 UTC, OlegIvaniv commented on packages/editor-ui/src/utils/typesUtils.ts
>  import { DateTime } from 'luxon';
DateTime is a type but not used in this file

2023-04-24 10:39 UTC, OlegIvaniv commented on packages/editor-ui/src/utils/userUtils.ts
> +import type { ILogInStatus, IRole, IUserPermissions } from '@/Interface';
Could be merged with the import above

2023-04-24 10:39 UTC, OlegIvaniv commented on packages/editor-ui/src/views/CredentialsView.vue
> +import { IUser } from '@/Interface';
This is a type but not used in the file

2023-04-24 10:40 UTC, OlegIvaniv commented on packages/editor-ui/src/api/workflows.ts
> +import { ExecutionStatus, WorkflowExecuteMode } from 'n8n-workflow';
These are types but not used in the file

2023-05-02 10:16 UTC, janober commented
Got released with [`n8n@0.226.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.226.1)