chore: Debug e2e pipeline
n8n-io/n8n pull request #6240
Opened 2023-05-12 11:53 UTC by OlegIvaniv

Github issue / Community forum post (link here to close automatically):

2023-05-12 11:56 UTC, mutdmour requested changes
what is this

2023-05-12 12:01 UTC, mutdmour requested changes
I disapprove

2023-05-12 12:03 UTC, mutdmour approved these changes

2023-05-12 14:45 UTC, netroy approved these changes

2023-05-12 15:00 UTC, merged

2023-05-25 11:40 UTC, janober commented
Got released with [`n8n@0.230.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.230.1)