fix(editor): Pin all data regardless of pagination
n8n-io/n8n pull request #6346
Opened 2023-05-31 15:53 UTC by cstuncsik

2023-06-01 13:56 UTC, alexgrozav requested changes
As far as I know, `pinData` still needs to be paginated. Other than that, the fix works as expected.

2023-06-01 13:56 UTC, alexgrozav commented on packages/editor-ui/src/components/RunData.vue
> +				!pinData
As far as I know, `pinData` still needs to be paginated.

2023-06-01 13:56 UTC, alexgrozav commented on packages/editor-ui/src/components/RunData.vue
> +			if (this.isSchemaView || this.pinData) {
Same as above.

2023-06-02 09:03 UTC, alexgrozav approved these changes

2023-06-02 09:59 UTC, merged

2023-06-14 11:07 UTC, janober commented
Got released with [`n8n@0.232.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.232.0)