feat(Set Node): Overhaul
n8n-io/n8n pull request #6348
Opened 2023-06-01 07:22 UTC by michael-radency

Github issue / Community forum post (link here to close automatically):

2023-06-01 20:15 UTC, luizeof commented
it would be nice to have an option to remove some fields

2023-08-28 16:23 UTC, luizeof commented
This pull is fantastic, is there any preview date or version?

As it changes the node interface, an ETA would be nice so we have time to show it to the community to avoid adoption issues for less experienced users.

2023-09-12 14:47 UTC, MiloradFilipovic requested changes
I left a minor comment in the code but am also getting some errors/inconsistencies when using the node:

1. When using `number` type and entering something that is not a number, I am getting `null` value instead of validation error:
![image](https://github.com/n8n-io/n8n/assets/2598782/f079165d-487a-40fd-b9d1-a9a3f90d2b7b)
3. I am unable to delete fields, getting this console error when clicking thrash icon:
![image](https://github.com/n8n-io/n8n/assets/2598782/5f0d8722-6f54-4ab2-93b8-4ba68275b431)

2023-09-12 14:47 UTC, MiloradFilipovic commented on packages/workflow/src/NodeHelpers.ts
> +	if (!(typeof value === 'string' && value.trim() === '')) {
Can this be turned into `if(String(val) !== '')`?

2023-09-18 10:34 UTC, maspio submitted a review, later dismissed

2023-09-18 15:41 UTC, MiloradFilipovic submitted a review, later dismissed
Looking good, thanks for addressing previous comments, @michael-radency 🙌
There is one minor thing that I noticed but ultimately it's a product decision:
When Ignore type conversion is turned on, inline validation errors (warnings next to inputs) are still showing up which could look confusing to users:
<img width="701" alt="image" src="https://github.com/n8n-io/n8n/assets/2598782/7e834cac-c916-4ddd-8169-68518aa9b7e3">

2023-09-19 06:26 UTC, maspio approved these changes, later dismissed

2023-09-19 10:02 UTC, maspio approved these changes

2023-09-19 10:16 UTC, merged

2023-09-21 16:37 UTC, janober commented
Got released with [`n8n@1.8.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.8.1)

2023-09-30 15:25 UTC, artemdzyuba commented
In 1.8.2, this Set node messes with null and undefined values. See [this thread](https://community.n8n.io/t/null-and-undefined-in-string-fields/31060).