fix(editor): Prevent XSS in RunDataHtml
n8n-io/n8n pull request #6432
Opened 2023-06-14 14:06 UTC by netroy

N8N-6496

2023-06-14 14:15 UTC, netroy commented on packages/editor-ui/src/components/RunDataHtml.vue
> +	},
```suggestion
	allowedAttributes: {
	    ...default.allowedAttributes,
		'*': ['class'],
	},
```

2023-06-14 15:52 UTC, ivov requested changes
CSS styling is lost!

Before:

<img width="1440" alt="image" src="https://github.com/n8n-io/n8n/assets/44588767/a677e04d-5b21-45d0-8d01-6c6a985964df">

After:

<img width="1440" alt="image" src="https://github.com/n8n-io/n8n/assets/44588767/0a29cc6c-3d2f-4567-90ca-94f9b8a2d7a8">

2023-06-14 16:08 UTC, netroy commented
> CSS styling is lost!

That's because `enforceHtmlBoundary` is set to `true`, and the style tag in your example is in the wrong place. I explicitly made this decision to make the preview is consistent with what a user might see in a webview of apps like Outlook, etc.

Perhaps we should also update the placeholder to use semantically correct markup, by moving `style` and `script` tags to be inside the document.

2023-06-15 07:52 UTC, ivov commented
> Perhaps we should also update the placeholder

Agree! We should either fix the placeholder to have effect or remove the CSS, to avoid confusing users. If removing it, we should run this by Giulio who requested the styling back when this was reviewed.

2023-06-16 11:00 UTC, ivov submitted a review, later dismissed
1. Comparing side by side, `line-height`, `font-family` and `padding` are very different from the original. Also the HTML doc title was not rendered before, but now it is. 
2. The `Format HTML` option restores the old way of `script` and `style` at root level. We should update this or perhaps disable the option until we address it.

I do not mean to block a security fix on styling - up to you if this can be fixed in a follow-up.

2023-06-16 12:18 UTC, netroy commented
I've reverted the `enforceHtmlBoundary` flag, and everything should now work.

The styles are still going to be slightly different, as the styles were not completely sanboxed earlier, and now they are. Which means the preview looks a lot more like what most users would see outside n8n.

2023-06-16 15:27 UTC, ivov approved these changes

2023-06-16 15:42 UTC, merged

2023-06-22 14:56 UTC, janober commented
Got released with [`n8n@0.234.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.234.0)