ci: Prevent e2e failure on `commented` type review (no-changelog)
n8n-io/n8n pull request #6452
Opened 2023-06-16 08:08 UTC by ivov

2023-06-16 08:08 UTC, OlegIvaniv reviewed
Testing comment

2023-06-16 08:21 UTC, netroy requested changes
test

2023-06-16 08:23 UTC, netroy commented
could we instead have the CI workflow not even start until the PR is approved, instead of starting, and then skipping it.

2023-06-16 08:31 UTC, ivov commented
> could we instead have the CI workflow not even start until the PR is approved, instead of starting, and then skipping it.

I also found it odd why we do this, but seeing the below PRs, this might be needed. Maybe @OlegIvaniv knows better?

- https://github.com/n8n-io/n8n/pull/5958
- https://github.com/n8n-io/n8n/pull/6240

2023-06-16 08:43 UTC, OlegIvaniv commented
> > could we instead have the CI workflow not even start until the PR is approved, instead of starting, and then skipping it.
> 
> I also found it odd why we do this, but seeing the below PRs, this might be needed. Maybe @OlegIvaniv knows better?
> 
> * [ci: Prevent skipping of E2E fail job (no-changelog) #5958](https://github.com/n8n-io/n8n/pull/5958)
> * [ci: Debug e2e pipeline (no-changelog) #6240](https://github.com/n8n-io/n8n/pull/6240)

GH actions do not support approved as activity type for `pull_request_review`, there's only `submitted`, `dismissed` and `edited`.  But maybe we could just remove the ` github.event.review.state != 'approved'` condition from the fail branch, then it should get skipped

2023-06-16 10:02 UTC, netroy approved these changes
This should be good enough for now. Thanks 🙏🏽

2023-06-16 10:17 UTC, merged

2023-06-22 14:56 UTC, janober commented
Got released with [`n8n@0.234.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.234.0)