fix: Make MySQL migration for nano id change compatible with version 5.7
n8n-io/n8n pull request #6498
Opened 2023-06-21 08:18 UTC by krynble

Github issue / Community forum post (link here to close automatically):

2023-06-21 09:20 UTC, flipswitchingmonkey submitted a review, later dismissed

2023-06-21 09:46 UTC, netroy reviewed
[Started DB tests](https://github.com/n8n-io/n8n/actions/runs/5332571860/jobs/9661927713). Let's wait for them to pass, before merging.

2023-06-21 09:55 UTC, netroy requested changes, later dismissed
[Tests failed](https://github.com/n8n-io/n8n/actions/runs/5332571860/jobs/9661927713)

2023-06-21 13:25 UTC, netroy commented on packages/cli/src/databases/migrations/mysqldb/1690000000001-MigrateIntegerKeysToString.ts
> +		if (dbVersionQuery?.length === 1) {
[we have a similar check in a previous migration](https://github.com/n8n-io/n8n/blob/master/packages/cli/src/databases/migrations/mysqldb/1623936588000-CertifyCorrectCollation.ts#L10). maybe we can unify the two, or at least use the same code in both the places.

2023-06-21 13:25 UTC, netroy commented on packages/cli/src/databases/migrations/mysqldb/1690000000001-MigrateIntegerKeysToString.ts
> +		const dbVersionQuery = (await queryRunner.query('SELECT @@version')) as  // eslint-disable-next-line @typescript-eslint/naming-convention
I think we might need skip the whole collation thing on mariadb.

2023-06-21 14:37 UTC, flipswitchingmonkey approved these changes

2023-06-21 14:56 UTC, netroy approved these changes

2023-06-21 15:10 UTC, merged

2023-06-22 14:56 UTC, janober commented
Got released with [`n8n@0.234.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.234.0)