fix(core): Use owners file to export wf owners
n8n-io/n8n pull request #6547
Opened 2023-06-27 06:25 UTC by flipswitchingmonkey

2023-06-27 15:52 UTC, krynble requested changes

2023-06-27 17:23 UTC, flipswitchingmonkey commented on packages/cli/src/environments/sourceControl/sourceControl.service.ee.ts
> +				const existingWorkflow = await Db.collections.Workflow.find({
good point

2023-06-28 06:07 UTC, flipswitchingmonkey commented on packages/cli/src/environments/sourceControl/sourceControlImport.service.ee.ts
>  		await Db.transaction(async (transactionManager) => {
removed transactions

2023-06-28 07:22 UTC, krynble commented on packages/cli/src/environments/sourceControl/sourceControlExport.service.ee.ts
> +			sharedWorkflows.forEach((e) => (owners[e.workflowId] = e.user.email));
One problem I see here is that we're always sending the full file, regardless of the workflows actually exported.

One problem I had is that I have over 100 workflows, but I exported a single one. My owners file contains all the 100 workflow owner names, even though my repo only contains a single workflow file.

I'm thinking that maybe we should read the file contents and append the rows that were added WDYT?

2023-06-28 07:23 UTC, krynble requested changes
Other than the comment I left, it all looks fine.

2023-06-28 08:39 UTC, krynble approved these changes

2023-06-28 09:06 UTC, merged

2023-07-05 14:04 UTC, janober commented
Got released with [`n8n@0.236.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.236.0)