fix(core): Deactivate on init workflow that should not be retried
n8n-io/n8n pull request #6676
Opened 2023-07-17 14:46 UTC by ivov

To test manually:
1. Set up workflow 1 with a trigger with an invalid cred.
2. Set up workflow 2 with an error trigger. Set this workflow to save executions.
3. Set workflow 1 to have workflow 2 one as error workflow.
4. In DB edit `workflow_entity.active` for workflow 1 to `true`
5. Run `packages/cli/bin/n8n start --tunnel`

Expected:
- Workflow 1 should be deactivated and displayed as inactive on canvas.
- Workflow 1 should not keep retrying to activate.
- Workflow 2 should have executed.

2023-07-17 14:57 UTC, krynble requested changes
I think one of the issues that we are having is that the `packages/cli/src/ActiveWorkflowRunner.ts`'s `activationErrors` property is not getting set correctly.

We need to show the red triangle with exclamation mark properly as in the code in `packages/editor-ui/src/components/WorkflowActivator.vue` (look for `displayActivationError`)

We gotta make sure that this works properly and users can see this in the UI.

2023-07-18 07:30 UTC, ivov commented
> I think one of the issues that we are having is that the `packages/cli/src/ActiveWorkflowRunner.ts`'s `activationErrors` property is not getting set correctly.
> 
> We need to show the red triangle with exclamation mark properly as in the code in `packages/editor-ui/src/components/WorkflowActivator.vue` (look for `displayActivationError`)
> 
> We gotta make sure that this works properly and users can see this in the UI.

Got you, I didn't know this. Please see update.

2023-07-18 08:45 UTC, krynble approved these changes
LGTM

This will cover only one scenario where the error message contains "Authorization" only, so maybe we still fail to detect other cases, but since we added the retry policy we can't simply fail and give up.

Maybe @netroy has some ideas on how to improve this, but it looks good in the problem it needs to address.

2023-07-18 10:04 UTC, ivov commented
@krynble Based on our discussion, I just now tested the follow-up case:
1. Set up workflow 1 with a trigger with an invalid cred.
2. Set up workflow 2 with an error trigger. Set this workflow to save executions.
3. Set workflow 1 to have workflow 2 as error workflow.
4. In DB edit `workflow_entity.active` for workflow 1 to `true`
5. Run `packages/cli/bin/n8n start --tunnel` → Workflow 1 shown with red activator on canvas.
6. Update cred to be valid.
7. Deactivate and reactivate workflow → Workflow 1 starts listening for events.

Tested with GH trigger.

2023-07-18 12:19 UTC, netroy approved these changes

2023-07-18 12:19 UTC, netroy commented on packages/cli/test/unit/ActiveWorkflowRunner.test.ts
> +			id: (i + 1).toString(),
thanks for this fix. [I've had this change in a branch for weeks](https://github.com/n8n-io/n8n/commit/84613648334ffeef1336d932ea98df5fba852f7f), but haven't had the opportunity to sneak it in a PR 🙏🏽

2023-07-18 12:27 UTC, netroy commented on packages/cli/test/unit/ActiveWorkflowRunner.test.ts
> +			id: (i + 1).toString(),
in general, I'd really like us to move away from using `Object.assign` for creating entities, and use `repository.create` instead, as that's type-safe.

2023-07-18 13:57 UTC, merged

2023-07-19 20:02 UTC, janober commented
Got released with [`n8n@0.236.3`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.236.3)