refactor(core): Move webhook DB access to repository (no-changelog)
n8n-io/n8n pull request #6706
Opened 2023-07-20 07:30 UTC by ivov

2023-07-20 07:42 UTC, krynble approved these changes
I have mixed feelings about using the built-in functions (such as `findById`) but since it's not something we could remove either, I think this is fine. Thanks for addressing this.

To clarify: I think having specific functions that return specific objects is best as we can optimize and make sure the desired behaviors are implemented. The usage of `findById` and such functions is too flexible and usually would lead to poorly performing queries. Not a big deal for this entity, so this is all right, but when you have joins (such as the execution repo) I think dedicated functions are best.

2023-07-20 07:44 UTC, krynble requested changes
I'm having problems starting n8n with this

2023-07-20 07:47 UTC, krynble commented
To clarify:

```
    ServiceNotFoundError: Service with "MaybeConstructable<DataSource>" identifier was not found in the 
    container. Register it before usage via explicitly calling the "Container.set" function or using the 
    "@Service()" decorator.

```

I think we're having issues starting n8n and injecting the service properly. I remember having this when implementing the Execution repo. The solution was to use `Container.get` instead of injecting the class at startup.

2023-07-20 07:48 UTC, krynble commented on packages/cli/src/ActiveWorkflowRunner.ts
> +		private webhookRepository: WebhookRepository,
The dependency injection here is failing at start time

2023-07-25 14:28 UTC, netroy reviewed
I've cherry-picked the fix for this from another PR. This PR should be good for review now.

2023-07-25 15:16 UTC, krynble approved these changes
Thanks!

2023-07-25 16:17 UTC, merged

2023-07-26 11:02 UTC, janober commented
Got released with [`n8n@1.1.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.1.0)