fix(editor): Fix collapsed sub menu elements
n8n-io/n8n pull request #6778
Opened 2023-07-28 09:41 UTC by cstuncsik

2023-07-28 09:54 UTC, alexgrozav commented
Looks like the menu items still show a tooltip when collapsed. 
<img width="328" alt="image" src="https://github.com/n8n-io/n8n/assets/6179477/2544a77f-f1eb-4752-8910-a7502a9f7d7e">

2023-07-28 09:59 UTC, alexgrozav requested changes
See comment above

2023-07-28 10:34 UTC, alexgrozav approved these changes

2023-07-28 11:09 UTC, merged

2023-08-09 17:48 UTC, janober commented
Got released with [`n8n@1.2.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.2.1)