ci: Parallelize `ci-master` (no-changelog)
n8n-io/n8n pull request #6819
Opened 2023-08-01 10:56 UTC by ivov

2023-08-01 10:57 UTC, ivov commented on .github/workflows/ci-master.yml
>        - name: Notify Slack on failure
Do we need to duplicate the Slack notification step or will it capture issues from parallel jobs?

2023-08-01 11:09 UTC, netroy reviewed
Can you please add `parallelize-ci-master` to `on.push.branches` to test if this works as expected ?

2023-08-01 11:40 UTC, netroy requested changes
This is now using the node-version matrix only for the build process, and not for the entire flow. which means that we aren't testing the builds on node 20.
If this is too complicated to fix, we can disable node 20 support for now.

2023-08-01 12:16 UTC, ivov commented
> This is now using the node-version matrix only for the build process, and not for the entire flow. which means that we aren't testing the builds on node 20. If this is too complicated to fix, we can disable node 20 support for now.

I'll revisit as soon as I can! Need to focus on main task for now.

2023-08-02 12:44 UTC, netroy approved these changes

2023-08-02 15:16 UTC, netroy approved these changes

2023-08-02 15:38 UTC, merged

2023-08-09 17:48 UTC, janober commented
Got released with [`n8n@1.2.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.2.1)