feat(core): Descriptive message for common nodeJS errors
n8n-io/n8n pull request #6841
Opened 2023-08-03 03:57 UTC by michael-radency

Github issue / Community forum post (link here to close automatically):

2023-08-03 10:27 UTC, netroy requested changes
at a first glance this looks good so far, but this code can definitely benefit from unit tests.

2023-08-03 10:27 UTC, netroy commented on packages/workflow/src/NodeErrors.ts
> +/* eslint-disable @typescript-eslint/prefer-nullish-coalescing */
we should really be trying to get rid of file level linting exceptions, and add the on a line by line basis.

2023-08-14 18:55 UTC, netroy approved these changes

2023-08-14 19:12 UTC, merged

2023-08-15 06:05 UTC, netroy commented
looks like this change might be breaking the workflow tests https://github.com/n8n-io/n8n/actions/runs/5862793654/job/15895155750

2023-08-16 16:27 UTC, janober commented
Got released with [`n8n@1.3.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.3.0)