refactor(core): Move tag collection into repository (no-changelog)
n8n-io/n8n pull request #6860
Opened 2023-08-07 07:41 UTC by ivov

2023-08-07 17:43 UTC, netroy requested changes
besides minor comments, LGTM.

2023-08-07 17:43 UTC, netroy commented on packages/cli/src/Server.ts
> +			new TagsController({ config, tagRepository: Container.get(TagRepository), externalHooks }),
maybe we can import `config` directly in `TagsController`, add `@Service()` to that class, and replace this line with `Container.get(TagsController)`. 
That's the eventual goal: to stop explicitly passing in dependencies everywhere.

2023-08-07 17:43 UTC, netroy commented on packages/cli/test/integration/shared/testDb.ts
> +	const [tag, rest] = separate(collections, (c) => c === 'Tag');
as we remove repositories from `Db.collections`, maybe we should switch to each test file defining what tables **not to truncate**, and then we can truncate all other tables.

2023-08-07 17:43 UTC, netroy commented on packages/cli/test/integration/shared/utils/testServer.ts
> +							new TagsController({
same as mentioned above: if we make `TagsController` a `@Service`, can replace this block with `Container.get(TagsController)`

2023-08-07 17:43 UTC, netroy commented on packages/cli/src/TagHelpers.ts
>  import type { EntityManager } from 'typeorm';
almost all of the code in this file belongs to the `TagRepository` file.

2023-08-07 17:43 UTC, netroy commented on packages/cli/src/environments/sourceControl/sourceControl.service.ee.ts
> +		const lastUpdatedTag = await Container.get(TagRepository).find({
you can inject this in the constructor instead.

2023-08-07 17:43 UTC, netroy commented on packages/cli/src/environments/sourceControl/sourceControlExport.service.ee.ts
> +			const tags = await Container.get(TagRepository).find();
can be injected in the constructor

2023-08-07 17:43 UTC, netroy commented on packages/cli/src/environments/sourceControl/sourceControlImport.service.ee.ts
> +		const localTags = await Container.get(TagRepository).find({
constructor injection here as well

2023-08-08 11:55 UTC, netroy approved these changes

2023-08-08 12:08 UTC, merged

2023-08-09 17:49 UTC, janober commented
Got released with [`n8n@1.2.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.2.1)