feat: Clean up onboarding experiment
n8n-io/n8n pull request #6873
Opened 2023-08-08 10:40 UTC by mutdmour

Github issue / Community forum post (link here to close automatically):

2023-08-08 11:57 UTC, OlegIvaniv requested changes

2023-08-08 11:57 UTC, OlegIvaniv commented on packages/editor-ui/src/stores/segment.store.ts
> -	const showAppCuesChecklist = () => {
The method is still returned from composable:
```
{
		showAppCuesChecklist,
		track,
		trackAddedTrigger,
		trackSuccessfulWorkflowExecution,
		EVENTS,
	};
	```

2023-08-08 12:16 UTC, mutdmour commented on packages/editor-ui/src/stores/segment.store.ts
> -		track(EVENTS.SHOW_CHECKLIST);
ah yes thanks

2023-08-08 13:33 UTC, OlegIvaniv approved these changes

2023-08-08 15:00 UTC, merged

2023-08-09 17:49 UTC, janober commented
Got released with [`n8n@1.2.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.2.1)