fix(core): Set up OAuth2 cred test
n8n-io/n8n pull request #6960
Opened 2023-08-17 14:08 UTC by ivov

https://linear.app/n8n/issue/PAY-728

2023-08-17 15:00 UTC, krynble requested changes

2023-08-17 15:20 UTC, ivov commented on packages/cli/src/CredentialsHelper.ts
> +			credentialsDecrypted,
Found a way to avoid this!

2023-08-17 15:24 UTC, ivov commented
Thanks @krynble! Can you please check again?

2023-08-18 08:09 UTC, krynble approved these changes
LGTM
Tested and working fine!

2023-08-18 09:36 UTC, netroy commented
This branch needs to be rebased to fix the e2e tests.

2023-08-18 13:49 UTC, flipswitchingmonkey approved these changes

2023-08-18 14:18 UTC, merged

2023-08-30 09:02 UTC, janober commented
Got released with [`n8n@1.4.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.4.1)