feat: Create workflow history database migration
n8n-io/n8n pull request #7031
Opened 2023-08-28 11:19 UTC by krynble

Github issue / Community forum post (link here to close automatically):

For the upcoming workflow history feature, we're creating the necessary database tables.

Also changes the schema for Postgres so the versionId column is now properly a UUID. The `using` statement prevents losing data, basically converting the strings to UUIDs.

2023-08-28 11:37 UTC, netroy requested changes

2023-08-28 11:37 UTC, netroy commented on packages/cli/src/databases/migrations/common/1692967111175-CreateWorkflowHistoryTable.ts
> +			.withColumns(...columns)
```suggestion
import type { MigrationContext, ReversibleMigration } from '@db/types';

const tableName = 'workflow_history';

export class CreateWorkflowHistoryTable1692967111175 implements ReversibleMigration {
	async up({ schemaBuilder: { createTable, column }, queryRunner }: MigrationContext) {
		await createTable(tableName)
			.withColumns(
				column('versionId').uuid.primary.notNull,
				column('workflowId').varchar(36).notNull,
				column('nodes').text.notNull,
				column('connections').text.notNull,
				column('authors').varchar(255).notNull,
			)
```

2023-08-28 13:44 UTC, netroy commented on packages/cli/src/databases/migrations/postgresdb/1692967111174-ChangeVersionIdToUUID.ts
> +			`ALTER TABLE "${tablePrefix}workflow_entity" ALTER "versionId" TYPE uuid USING "versionId"::uuid`,
do we need this migration in this PR? if not, I'd prefer this to be in a separate PR whenever we need it.

2023-08-28 15:44 UTC, netroy approved these changes

2023-08-29 09:43 UTC, netroy approved these changes

2023-08-29 10:01 UTC, merged

2023-08-31 13:29 UTC, janober commented
Got released with [`n8n@1.5.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.5.1)