[Fix] a typo in MessageInterface.ts
n8n-io/n8n pull request #7078
Opened 2023-09-03 06:04 UTC by KubeAl

A typo in zulip node message interface, not letting update all messages of same topic.

Github issue / Community forum post (link here to close automatically):

2023-09-03 06:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/n8n-io/n8n?pullRequest=7078) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/n8n-io/n8n?pullRequest=7078) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/n8n-io/n8n?pullRequest=7078) it.</sub>

2023-09-05 10:13 UTC, Joffcom approved these changes

2023-09-05 10:16 UTC, Joffcom requested changes, later dismissed
This also needs to be changed in the node as well or it won't work, It looks like this is in the main node .ts file.

2024-06-20 15:46 UTC, netroy approved these changes
Thanks

2024-06-20 19:09 UTC, merged

2024-06-27 10:36 UTC, janober commented
Got released with [`n8n@1.48.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.48.0)