ci: Remove eslint diff plugin. Run full linting on PRs (no-changelog)
n8n-io/n8n pull request #7175
Opened 2023-09-14 14:04 UTC by netroy

2023-09-14 14:10 UTC, ivov requested changes

2023-09-14 14:10 UTC, ivov commented on .github/workflows/ci-pull-requests.yml
> +      - name: Lint
According to [the original PR](https://github.com/n8n-io/n8n/pull/4137/files#diff-4eb787923b5d10508f08732ecbbe5195a389acb35bb1d56c7b57ccaa747d9c7c) we also need to remove the prior `Fetch base branch` step.

2023-09-14 14:29 UTC, ivov approved these changes

2023-09-14 14:55 UTC, merged

2023-09-21 16:37 UTC, janober commented
Got released with [`n8n@1.8.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.8.1)