fix(core): Ensure execution deletion in worker lifecycle hook
n8n-io/n8n pull request #7481
Opened 2023-10-20 14:58 UTC by ivov

Reported by customer [here](https://n8nio.slack.com/archives/C05PUALKZHD/p1697446945481249?thread_ts=1697196557.638169&cid=C05PUALKZHD), apparently a very old long-standing bug for queue mode. Please review closely as I am not familiar with queue mode.

2023-10-20 14:59 UTC, ivov commented on packages/cli/src/WorkflowExecuteAdditionalData.ts
> +
Duplication will be removed at https://github.com/n8n-io/n8n/pull/7370

2023-10-24 07:52 UTC, krynble requested changes

2023-10-24 07:52 UTC, krynble commented on packages/cli/src/WorkflowExecuteAdditionalData.ts
> +							});
Unfortunately this deletion cannot happen here.

Due to the nature of queue mode, we save the execution data to DB and notify via Redis that a given execution has finished.

This in turn allows the caller (be it `main` or `webhook`) to load the execution from DB (if needed) and react (such as sending an HTTP response or removing an item from a queue).

This code would need to be part of the array returned by `getWorkflowHooksWorkerMain` instead.

2023-10-24 09:55 UTC, ivov commented on packages/cli/src/WorkflowExecuteAdditionalData.ts
> +			}
Duplication will be removed at #7370

2023-10-25 15:39 UTC, krynble approved these changes

2023-10-25 17:13 UTC, merged

2023-10-26 12:28 UTC, janober commented
Got released with [`n8n@1.14.2`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.14.2)