feat: Add AI features unit and e2e tests
n8n-io/n8n pull request #7513
Opened 2023-10-25 13:10 UTC by alexgrozav

- Adds unit tests for @n8n/chat package
  <img width="726" alt="image" src="https://github.com/n8n-io/n8n/assets/6179477/b9372f26-c476-4721-acd9-9586b333d25e">

- Adds unit tests for various editor-ui files
- Adds e2e tests for AI Nodes and new input types
- Refactor editor-ui for unit testing
  - Pinia triggers a strange error when stores are imported from an index file, this PR fixes it
  ```
   FAIL  src/components/__tests__/WorkflowSettings.spec.ts [ src/components/__tests__/WorkflowSettings.spec.ts ]
  TypeError: Cannot read properties of undefined (reading '$id')
   ❯ ../../node_modules/.pnpm/pinia@2.1.6_typescript@5.2.2_vue@3.3.4/node_modules/pinia/dist/pinia.mjs:1803:26
      1801|     return stores.reduce((reduced, useStore) => {
      1802|         // @ts-expect-error: $id is added by defineStore
      1803|         reduced[useStore.$id + mapStoreSuffix] = function () {
         |                          ^
      1804|             return useStore(this.$pinia);
      1805|         };
   ❯ Module.mapStores 
  ../../node_modules/.pnpm/pinia@2.1.6_typescript@5.2.2_vue@3.3.4/node_modules/pinia/dist/pinia.mjs:1801:19
   ❯ src/components/WorkflowSettings.vue:454:6
   ❯ src/components/__tests__/WorkflowSettings.spec.ts:1:31
  ```

2023-11-09 10:04 UTC, OlegIvaniv requested changes
LOVE IT! 💙 Just remove the console.logs and its good to go in my view

2023-11-09 14:51 UTC, alexgrozav commented on packages/editor-ui/src/mixins/pushConnection.ts
> +
Good catch!

2023-11-09 14:51 UTC, alexgrozav commented on cypress/utils/executions.ts
> +export function runMockWorkflowExcution({
Thank you!  🙏

2023-11-09 14:58 UTC, alexgrozav commented on packages/editor-ui/src/__tests__/defaults.ts
> +	[MANUAL_TRIGGER_NODE_TYPE]: {
Updated to use `nodes.json`. Great idea!

2023-11-10 07:06 UTC, OlegIvaniv approved these changes

2023-11-10 13:04 UTC, merged