fix(core): Ensure pruning starts only after migrations have completed
n8n-io/n8n pull request #7626
Opened 2023-11-06 14:54 UTC by ivov

https://linear.app/n8n/issue/PAY-986/bug-execution-pruning-timer-is-started-before-the-database-is-ready

2023-11-06 15:06 UTC, netroy requested changes

2023-11-06 15:06 UTC, netroy commented on packages/cli/src/commands/BaseCommand.ts
> +		const pruningService = Container.get(PruningService);
Should we move this to `packages/cli/src/commands/start.ts` instead after `server.start()` ?

2023-11-06 15:24 UTC, netroy approved these changes, later dismissed
🙏🏽

2023-11-06 16:28 UTC, netroy approved these changes

2023-11-07 12:56 UTC, merged

2023-11-08 14:10 UTC, janober commented
Got released with [`n8n@1.16.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.16.0)