Add tests to POST /users
n8n-io/n8n pull request #7658
Opened 2023-11-09 00:23 UTC by RicardoE105

Github issue / Community forum post (link here to close automatically):

2023-11-09 00:40 UTC, RicardoE105 commented
Fixes: https://linear.app/n8n/issue/ADO-1358/add-tests-to-post-users-endpoint

2023-11-09 13:48 UTC, RicardoE105 commented
@netroy Do you know why we have `user.controller.test` and `users.api.test`? I just rewrote the test because I checked in the controller and did not know we had a users.api.test. Should we have only one for tests the that belong to users.controller?

2023-11-10 10:47 UTC, netroy requested changes

2023-11-10 10:47 UTC, netroy commented on packages/cli/test/unit/Helpers.ts
> +export const getLastArgsTo = <T>(subject: MockedFunction<any>) => {
this doesn't seem to be used

2023-11-10 14:14 UTC, netroy approved these changes

2023-11-10 14:41 UTC, merged

2023-11-15 14:46 UTC, janober commented
Got released with [`n8n@1.17.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.17.0)