perf(core): Lazyload security audit reporters
n8n-io/n8n pull request #7696
Opened 2023-11-13 08:55 UTC by ivov

Also converting to service.

Followup to https://github.com/n8n-io/n8n/pull/7663

2023-11-13 10:11 UTC, netroy requested changes
besides the one comment, LGTM

2023-11-13 10:11 UTC, netroy commented on packages/cli/src/PublicApi/v1/handlers/audit/audit.handler.ts
> +				const result = await Container.get(SecurityAuditService).run(
You could make this a dynamic import to make this code truly lazy-loaded.
```suggestion
				const { SecurityAuditService } = await import('@/security-audit/SecurityAudit.service');
				const result = await Container.get(SecurityAuditService).run(
```

2023-11-13 10:22 UTC, netroy approved these changes

2023-11-13 10:50 UTC, merged

2023-11-15 14:46 UTC, janober commented
Got released with [`n8n@1.17.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.17.0)