fix(core): Fix user comparison in same-user subworkflow caller policy
n8n-io/n8n pull request #7913
Opened 2023-12-04 09:19 UTC by ivov

https://linear.app/n8n/issue/PAY-992

https://community.n8n.io/t/executing-workflow-using-owner-role-created-by-another-user-fails/33443

2023-12-04 17:17 UTC, krynble approved these changes
LGTM!
Thanks for the fix!

2023-12-04 19:50 UTC, krynble requested changes
We still have a problem with this PR - the error thrown by `checkSubworkflowExecutePolicy` is of type `SubworkflowOperationError`.

The problem is that the caller function expects the error to be of type `ExecutionError`.

Long story short: the `SubworkflowOperationError` error type is missing a `node` attribute stating the failed node, so we can show the error correctly in the proper node.

2023-12-05 09:52 UTC, ivov commented
> We still have a problem with this PR - the error thrown by `checkSubworkflowExecutePolicy` is of type `SubworkflowOperationError`.
> 
> The problem is that the caller function expects the error to be of type `ExecutionError`.
> 
> Long story short: the `SubworkflowOperationError` error type is missing a `node` attribute stating the failed node, so we can show the error correctly in the proper node.

Thanks! Quick question: Is this in scope of this PR? Looks like a preexisting issue in multiple places whenever `SubworkflowOperatorError` is used. Might be best to ship the fix and address this separately, else let me know.

2023-12-05 13:41 UTC, krynble commented
@ivov we'll have to fix this as the scope of this PR otherwise the error message is still completely useless as it errors with `Failed reading property of undefined: reading name` or something similar.

On the other hand this should not be too hard to fix, as it's a matter of extending the correct error class and sending the`Execute Workflow` node used to trigger. Hopefully this won't be too complicated.

2023-12-05 14:39 UTC, ivov commented
Thanks! I'll come back to this soon.

2023-12-06 09:34 UTC, krynble commented on packages/cli/src/UserManagement/PermissionChecker.ts
> +		const executeWorkflowNode = Object.values(parentWorkflow.nodes).find(
The problem I see here is that if a workflow contains more than 1 execute workflow node, we'll get the first one we find.

Instead, what we could do is pass the `node` from https://github.com/n8n-io/n8n/blob/f5502cc628f6b348f7fe3325b96ec9dc3360beaf/packages/core/src/NodeExecuteFunctions.ts#L3155 to this function call. Then we'd have the exact node that was trying to execute a child workflow and display the error in the proper place.

2023-12-06 10:34 UTC, krynble commented on packages/cli/src/WorkflowHelpers.ts
> +				workflowErrorData.workflow.id!,
In here we could use `workflowInstance.getNode(workflowErrorData.execution?.lastNodeExecuted);` if available as it should contain the last executed node.

2023-12-06 11:42 UTC, krynble approved these changes
I've made a small change to `WorkflowHelpers.ts`

2023-12-06 12:27 UTC, merged

2023-12-13 16:03 UTC, janober commented
Got released with [`n8n@1.21.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.21.0)