fix(editor): Turn off executions list auto-refresh after leaving the page
n8n-io/n8n pull request #8005
Opened 2023-12-12 14:47 UTC by cstuncsik

## Summary
Fixes the bug when users leave the executions page but there is still an ongoing request for executions.

2023-12-12 17:03 UTC, netroy requested changes
I've seen at least 3 PRs in the past to fix auto-refresh for the executions list. Maybe we should add an e2e test for this view, and prevent this regression from ever happening again?

2023-12-14 10:20 UTC, netroy approved these changes

2023-12-14 10:20 UTC, netroy commented on packages/editor-ui/src/components/ExecutionsList.vue
>  			if (document.visibilityState === 'hidden') {
perhaps a task for another time, but we should move most of this duplicate code into a `useAutoRefresh` composable, and use `useDocumentVisibility` from vueuse instead.

2023-12-14 10:50 UTC, merged

2023-12-15 13:25 UTC, janober commented
Got released with [`n8n@1.21.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.21.1)