fix(Asana Node): Omit body from GET and HEAD requests
n8n-io/n8n pull request #8057
Opened 2023-12-15 20:00 UTC by aarongut

## Summary
Avoid unnecessarily including a request body with GET and HEAD requests. Per RFC 7230 clients should not include a body for these requests, and we (Asana) are rolling out an infrastructure change that will cause these requests to fail.

## Related tickets and issues
> Include links to **Linear ticket** or Github issue or Community forum post. Important in order to close *automatically* and provide context to reviewers.

## Review / Merge checklist
- [x] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included.
   > A bug is not considered fixed, unless a test is added to prevent it from happening again.
   > A feature is not complete without tests.

2023-12-15 20:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/n8n-io/n8n?pullRequest=8057) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/n8n-io/n8n?pullRequest=8057) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/n8n-io/n8n?pullRequest=8057) it.</sub>

2023-12-15 20:53 UTC, Joffcom approved these changes, later dismissed

2023-12-20 11:10 UTC, netroy requested changes

2023-12-20 11:10 UTC, netroy commented on packages/nodes-base/nodes/Asana/GenericFunctions.ts
> +		body: method === 'GET' || method === 'HEAD' ? null : { data: body },
should this not also include `DELETE` ?

2023-12-21 16:53 UTC, netroy approved these changes

2023-12-21 18:21 UTC, merged

2023-12-27 15:34 UTC, janober commented
Got released with [`n8n@1.22.2`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.22.2)