refactor(core): Inject dependencies into workflow services (no-changelog)
n8n-io/n8n pull request #8066
Opened 2023-12-18 08:32 UTC by ivov

Inject dependencies into workflow services (no-changelog)

Up next:

- ~~Make workflow services injectable~~ #8033
- ~~Inject dependencies into workflow services~~ (current)
- Consolidate workflow controllers into one
- Make workflow controller injectable
- Inject dependencies into workflow controller

2023-12-18 10:07 UTC, netroy requested changes

2023-12-18 10:07 UTC, netroy commented on packages/cli/src/workflows/workflow.service.ts
> +		private readonly multiMainSetup: MultiMainSetup,
This is definitely creating a bunch of circular dependencies. which is most definitely going to prevent the app from starting up.

2023-12-18 13:34 UTC, netroy approved these changes, later dismissed
Left some comments for next refactor PR. LGTM

2023-12-18 14:57 UTC, netroy approved these changes

2023-12-18 15:10 UTC, merged

2023-12-21 13:25 UTC, janober commented
Got released with [`n8n@1.22.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.22.0)