ci: Fix Postgres and MySQL tests (no-changelog)
n8n-io/n8n pull request #8106
Opened 2023-12-20 09:51 UTC by ivov

This role query works for sqlite but [fails for Postgres and MySQL](https://github.com/n8n-io/n8n/actions/runs/7269009778/job/19805986017), so generalize by adding alias and accounting for count possibly being `string` in the resulting rows.

2023-12-20 09:56 UTC, netroy reviewed
Can we change [this line](https://github.com/n8n-io/n8n/blob/master/.github/workflows/ci-postgres-mysql.yml#L9) to `packages/cli/src/databases/**` to run DB test on repository and entity changes as well?

2023-12-20 10:01 UTC, netroy requested changes

2023-12-20 10:01 UTC, netroy commented on packages/cli/src/databases/repositories/role.repository.ts
>  			.groupBy('role.name')
This will not work with custom schema and table-prefix.

2023-12-20 10:18 UTC, netroy requested changes

2023-12-20 10:18 UTC, netroy commented on packages/cli/src/databases/repositories/role.repository.ts
>  			.innerJoin('user', 'user', 'role.id = user.globalRoleId')
try this
```suggestion
			.innerJoin(User, 'user', 'role.id = user.globalRoleId')
```

2023-12-20 14:01 UTC, netroy approved these changes

2023-12-20 14:14 UTC, merged

2023-12-21 13:25 UTC, janober commented
Got released with [`n8n@1.22.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.22.0)