Feat/Include sort field in pipedrive get all persons
n8n-io/n8n pull request #8138
Opened 2023-12-21 23:46 UTC by daniel-alba17

## Summary
Include sort field in Pipedrive get all persons node

![image](https://github.com/n8n-io/n8n/assets/102531532/e1ab6676-14f0-44d3-b7b6-02e9da9d2259)

2024-02-07 10:30 UTC, Joffcom approved these changes

2024-04-29 18:43 UTC, daniel-alba17 commented
@Joffcom Done!

2024-05-20 12:24 UTC, Joffcom approved these changes

2024-06-20 09:31 UTC, netroy requested changes
Sorry we forgot to merge this after the last approval.
Can you please merge the latest master back into your branch 🙏🏽 

---
Also, for any future PRs, **please keep this checkbox enabled**, so that we can rebase the PR without having to bother you.
 
![image](https://github.com/n8n-io/n8n/assets/196144/c9ff5a26-48a9-4af9-9015-e729121797a7)

2024-06-20 17:47 UTC, netroy approved these changes

2024-06-20 18:18 UTC, merged