feat: Add assignment component with drag and drop to Set node
n8n-io/n8n pull request #8283
Opened 2024-01-10 08:54 UTC by elsmr

## Summary

<img width="588" alt="image" src="https://github.com/n8n-io/n8n/assets/8850410/a73f8913-1e79-40b6-9968-15d5268234c6">
<img width="588" alt="image" src="https://github.com/n8n-io/n8n/assets/8850410/c5099e6f-e5b5-494a-9e0b-3ed029fc3895">

- Adds new assignmentCollection parameter type
- New assignment component UI based on Filter component
- Adds drag-and-drop functionality to add assignments
- Implements in Set node

## Related tickets and issues
https://linear.app/n8n/issue/NODE-1010/dragndrop-component
https://linear.app/n8n/issue/NODE-1011/edit-fields-set-node-dragdrop-and-assignment-components
https://linear.app/n8n/issue/NODE-1012/assigment-component

## Review / Merge checklist
- [ ] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included.
   > A bug is not considered fixed, unless a test is added to prevent it from happening again.
   > A feature is not complete without tests.

2024-01-24 11:33 UTC, alexgrozav requested changes
Excellent work, @elsmr! Tested and everything works as expected.

Can you please add unit tests for the components you've added? Specifically, `Assignment.vue`, `TypeSelect.vue`, `InputTriple.vue`, `DropArea.vue`. Thank you!

2024-01-25 13:33 UTC, maspio commented on packages/nodes-base/nodes/Set/v2/helpers/utils.ts
Looks like mapToAssignmentItem is not used anywhere.

2024-01-30 10:55 UTC, alexgrozav approved these changes, later dismissed
Thank you for addressing the requested changes. Awesome work!

2024-01-30 16:18 UTC, alexgrozav submitted a review, later dismissed

2024-02-06 15:53 UTC, maspio approved these changes, later dismissed

2024-02-06 16:41 UTC, maspio approved these changes

2024-02-06 17:34 UTC, merged

2024-02-07 15:01 UTC, janober commented
Got released with [`n8n@1.28.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.28.0)