feat(OpenAI Node): Overhaul
n8n-io/n8n pull request #8335
Opened 2024-01-15 13:15 UTC by michael-radency

## Summary
Update OpenAI node

Small tweaks on custom code tool and other

Other OpenAI node tickets 

## Related tickets and issues
https://linear.app/n8n/issue/NODE-976/ai-node-tweaks-and-openai-node-update

2024-02-03 22:01 UTC, BleedingDev commented
Is there something I could do for this PR? I'd like to contribute to make it pass sooner. :)

2024-02-14 17:15 UTC, OlegIvaniv requested changes
Really nice job on this one! 👏 
I love that you've added tests and `updateDisplayOptions` helper also seems quite helpful. 
I left just a few comments with typos, btw if you're using VS Code I would really recommend to install [Code Spell Checker extension](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker), it saved me many times :D

2024-02-14 17:15 UTC, OlegIvaniv commented on packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/image/generate.operation.ts
> +				displayName: 'Responde with Image URL(s)',
Typo: `Responde`

2024-02-14 17:15 UTC, OlegIvaniv commented on packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/text/classify.operation.ts
> +					'Whether to use the stable version of the model instead of the latest version, accuracy may be sligthly lower',
Typo: `sligthly` -> `slightly`

2024-02-14 17:15 UTC, OlegIvaniv commented on packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/text/message.operation.ts
> +									"Usualy used to set the model's behavior or context for the next user message",
Typo: `Usualy` -> `Usually`

2024-02-15 07:30 UTC, OlegIvaniv approved these changes

2024-02-15 08:15 UTC, merged

2024-02-15 11:32 UTC, janober commented
Got released with [`n8n@1.29.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.29.0)