refactor(core): Use DI in execution services (no-changelog)
n8n-io/n8n pull request #8358
Opened 2024-01-17 10:04 UTC by ivov

Continue modernizing executions ahead of refactor to [support the new executions list](https://linear.app/n8n/issue/PAY-1271).

Follow-up to: https://github.com/n8n-io/n8n/pull/8349

2024-01-17 14:18 UTC, netroy requested changes

2024-01-17 14:18 UTC, netroy commented on packages/cli/src/executions/execution.service.ee.ts
> +
`@Service()` is needed here. without that the app won't start.

2024-01-17 14:18 UTC, netroy commented on packages/cli/src/executions/executions.controller.ts
> +			: await this.workflowSharingService.getSharedWorkflowIds(req.user, ['owner']);
```suggestion
		const sharedWorkflowIds = await this.workflowSharingService.getSharedWorkflowIds(
			req.user,
			isSharingEnabled() ? undefined : ['owner'],
		);
```

You could also extract this into a private method on this class, to get rid of the 3 other duplicates.

2024-01-17 14:27 UTC, netroy approved these changes

2024-01-17 14:42 UTC, merged

2024-01-24 13:00 UTC, janober commented
Got released with [`n8n@1.26.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.26.0)