fix: Set '@typescript-eslint/return-await' rule to 'always' for FE (no-changelog)
n8n-io/n8n pull request #8373
Opened 2024-01-17 17:25 UTC by tomi

## Summary

Frontend follow-up of #8363

Returning a promise from function without awaiting it causes the function to be dropped from the stacktrace. This makes debugging harder. So this PR changes TS ESLint rule '@typescript-eslint/return-await' from its default value to 'always', so it is required to await any promises returned from async functions.

## Related tickets and issues

https://n8nio.slack.com/archives/C03MZF137FV/p1705496007084329

## Review / Merge checklist
- [x] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))

2024-01-18 09:04 UTC, alexgrozav requested changes
Looks good other than one small issue I found. Once that's fixed, we can move it further. 🚀

2024-01-18 09:07 UTC, tomi commented on packages/@n8n/chat/src/api/generic.ts
> +	return await ((await response.json()) as Promise<T>);
Oh nice catch! Will fix

2024-01-18 09:09 UTC, alexgrozav approved these changes
Thanks for addressing the issue!

2024-01-18 09:28 UTC, merged

2024-01-24 13:00 UTC, janober commented
Got released with [`n8n@1.26.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.26.0)