feat(editor): Implement loading and error states for dynamically loaded components in node parameter list
n8n-io/n8n pull request #8477
Opened 2024-01-29 14:01 UTC by MiloradFilipovic

## Summary
Adds `#fallback` slot and error state for dynamically loaded components rendered using `Suspense` in node parameter list.

NOTE: Decided to go without tests with this one since I couldn't figure out how to mock failed async component loading in Cypress. We should definitely add tests once we figure out and fix the root problem of this.

### To test loading state
1. Create a workflow that contains `Merge` node
2. Reload page
3. Set network throttling to 2G
4. Open `Merge` node's NDV

![Screen Recording 2024-01-29 at 14 56 30](https://github.com/n8n-io/n8n/assets/2598782/e017025d-f278-442f-94ed-fb59b278e54d)

### To test error state:
1. Throw an error in `FixedCollectionParameter` component's `created` hook ([here](https://github.com/n8n-io/n8n/blob/c9b3649b7ee568f90fdabce674ee1bdfe75780cb/packages/editor-ui/src/components/FixedCollectionParameter.vue#L221))
6. Create a new workflow with a `Merge` node
7. Open `Merge` node NDV

![image](https://github.com/n8n-io/n8n/assets/2598782/d7db6d9f-873e-45e7-b88f-5acc7cea6225)

## Related tickets and issues
Cosses ADO-1756

## Review / Merge checklist
- [ ] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included.
   > A bug is not considered fixed, unless a test is added to prevent it from happening again.
   > A feature is not complete without tests.

2024-01-29 15:26 UTC, OlegIvaniv requested changes
Seems to works as expected 🎉 Added just two minor comments, also there's some linting issues we should fix

2024-01-29 15:26 UTC, OlegIvaniv commented on packages/editor-ui/src/components/ParameterInputList.vue
> +      console.error(e);
Do we need this? It seems to me like it's duplicate-logging the error.

2024-01-29 15:26 UTC, OlegIvaniv commented on packages/editor-ui/src/components/ParameterInputList.vue
> +      return true;
To stop the propagation the return should be `false` as per Vue docs:
```
The hook can return false to stop the error from propagating further. See error propagation details below.
```

2024-01-30 12:25 UTC, OlegIvaniv approved these changes
Thanks for addressing my points, LGTM 🎉

2024-01-30 13:27 UTC, merged

2024-02-02 13:24 UTC, janober commented
Got released with [`n8n@1.27.2`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.27.2)