fix(editor): Do not clear expression when changing operator type in Filter component
n8n-io/n8n pull request #8635
Opened 2024-02-14 17:33 UTC by elsmr

## Summary

In the If node, when changing from a String operator to a Boolean operator (or any other type) should not change/clear expressions.

## Related tickets and issues
https://linear.app/n8n/issue/NODE-1113/bug-filter-component-changing-comparison-type-erases-any-expressions

## Review / Merge checklist
- [ ] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included.
   > A bug is not considered fixed, unless a test is added to prevent it from happening again.
   > A feature is not complete without tests.

2024-02-16 08:59 UTC, OlegIvaniv requested changes
Just one minor comment. Happy to approve after

2024-02-16 08:59 UTC, OlegIvaniv commented on packages/editor-ui/src/components/FilterConditions/Condition.vue
> +		currentOperator: operator.value,
`currentOperator` property is no longer accepted by this method

2024-02-16 10:42 UTC, OlegIvaniv approved these changes

2024-02-16 13:32 UTC, merged

2024-02-21 16:19 UTC, janober commented
Got released with [`n8n@1.30.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.30.0)