feat(editor): Improve errors in output panel
n8n-io/n8n pull request #8644
Opened 2024-02-15 11:21 UTC by gandreini

## Summary
> Describe what the PR does and how to test. Photos and videos are recommended.
Improves how errors are displayed in the output panel to better support
![image](https://github.com/n8n-io/n8n/assets/66951/783c476c-a625-47ec-93ce-a9846fa2cd8c)

## Related tickets and issues
> Include links to **Linear ticket** or Github issue or Community forum post. Important in order to close *automatically* and provide context to reviewers.
https://linear.app/n8n/issue/NODE-856/improve-errors-in-output-panel

## Review / Merge checklist
- [ ] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included.
   > A bug is not considered fixed, unless a test is added to prevent it from happening again.
   > A feature is not complete without tests.

2024-03-07 13:51 UTC, alexgrozav requested changes
Looks and works great overall! Left one small remark.

2024-03-07 13:51 UTC, alexgrozav commented on packages/workflow/test/errors/node.error.test.ts
> +describe('NodeError TESTER', () => {
Is this intended?

2024-03-07 13:56 UTC, michael-radency commented on packages/workflow/test/errors/node.error.test.ts
> +describe('NodeError TESTER', () => {
nope, removed

2024-03-07 13:58 UTC, alexgrozav approved these changes

2024-03-07 16:08 UTC, merged

2024-03-13 14:35 UTC, janober commented
Got released with [`n8n@1.33.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.33.0)