fix(core): Apply correct hostname to redirected requests
n8n-io/n8n pull request #8674
Opened 2024-02-20 10:19 UTC by elsmr

## Summary

Broken in https://github.com/n8n-io/n8n/pull/8562

`servername` set on the httpsAgent was also being used for redirected requests. When redirected to another domain this breaks. This PR updates the `Agent.servername` when redirected.

workflow test added here: https://github.com/n8n-io/test-workflows/pull/263

## Related tickets and issues
https://linear.app/n8n/issue/NODE-1149/recent-change-to-host-header-breaks-redirect-downloads
fixes https://github.com/n8n-io/n8n/issues/8668
https://community.n8n.io/t/ignore-ssl-setting-isnt-working-error-ssl-issue-consider-using-the-ignore-ssl-issues-option/40492

## Review / Merge checklist
- [ ] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included.
   > A bug is not considered fixed, unless a test is added to prevent it from happening again.
   > A feature is not complete without tests.

2024-02-20 10:47 UTC, netroy requested changes

2024-02-20 10:47 UTC, netroy commented on packages/core/src/NodeExecuteFunctions.ts
> +	axiosConfig.beforeRedirect = (redirectedRequest) => {
The two code blocks are identical. Can we extract this into a function like this
```typescript
const getBeforeRedirectFn =
	(agentOptions: AgentOptions, axiosConfig: AxiosRequestConfig<any>) =>
	(redirectedRequest: Record<string, any>) => {
		const redirectAgent = new Agent({
			...agentOptions,
			servername: redirectedRequest.hostname,
		});
		redirectedRequest.agent = redirectAgent;
		redirectedRequest.agents.https = redirectAgent;

		if (axiosConfig.headers?.Authorization) {
			redirectedRequest.headers.Authorization = axiosConfig.headers.Authorization;
		}
		if (axiosConfig.auth) {
			redirectedRequest.auth = `${axiosConfig.auth.username}:${axiosConfig.auth.password}`;
		}
	};
```

2024-02-20 10:47 UTC, netroy commented on packages/core/src/NodeExecuteFunctions.ts
> +	axiosConfig.beforeRedirect = (redirectedRequest) => {
```suggestion
	axiosConfig.beforeRedirect = getBeforeRedirectFn(agentOptions, axiosConfig);
```

2024-02-20 10:47 UTC, netroy commented on packages/core/src/NodeExecuteFunctions.ts
> +	axiosRequest.beforeRedirect = (redirectedRequest) => {
```suggestion
	axiosRequest.beforeRedirect = getBeforeRedirectFn(agentOptions, axiosRequest);
```

2024-02-20 12:04 UTC, netroy approved these changes

2024-02-20 12:23 UTC, merged

2024-02-21 16:19 UTC, janober commented
Got released with [`n8n@1.30.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.30.0)