fix: AI agents, throw error on duplicate names in dynamic tools
n8n-io/n8n pull request #8766
Opened 2024-02-29 07:06 UTC by michael-radency

## Summary
Error if we have two tools with the same name

## Related tickets and issues
https://linear.app/n8n/issue/AI-95/error-if-we-have-two-tools-with-the-same-name

2024-02-29 08:01 UTC, OlegIvaniv requested changes

2024-02-29 08:50 UTC, OlegIvaniv approved these changes, later dismissed

2024-02-29 09:30 UTC, OlegIvaniv approved these changes

2024-02-29 11:28 UTC, merged

2024-03-06 10:33 UTC, janober commented
Got released with [`n8n@1.31.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.31.1)