feat(Telegram Node): Add editMessageCaption action
n8n-io/n8n pull request #8862
Opened 2024-03-11 14:13 UTC by milanjrodd

## Summary
> PR adds a telegram action for editMessageCaption method.
<img width="732" alt="image" src="https://github.com/n8n-io/n8n/assets/121220673/0373def4-2f5b-4d38-a1e9-9e11da869ff2">

## Related tickets and issues
> https://community.n8n.io/t/telegram-edit-message-caption/10669

## Review / Merge checklist
- [x] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [x] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.

2024-04-22 10:38 UTC, Joffcom commented
This has been scheduled to be reviewed on Thursday (April 25th)

2024-04-25 11:24 UTC, Joffcom requested changes

2024-04-25 11:24 UTC, Joffcom commented on packages/nodes-base/nodes/Telegram/Telegram.node.ts
> +						action: 'Edit a caption of test message',
I think the Description and action might be better as

"Edit the caption of a message"

I am unable to make this change as you have used the master branch not a standard branch, if you can update this I can fit it in for a second review on Monday or next Thursday.

2024-04-25 13:37 UTC, milanjrodd commented
Fixed as requested :)

2024-04-29 07:07 UTC, Joffcom commented
Hey @milanjrodd,

It also needs updating in `packages/editor-ui/src/utils/testData/nodeTypeTestData.ts` I forgot to add those to the list.

2025-09-29 15:50 UTC, ShireenMissi commented
Thank you so much for your contribution! 🙏 
This PR has been inactive for a while, so I’m going to close it for now. If you’d like to revisit it in the future, please feel free to open a new PR based on the current codebase. We’d be happy to review it.

2025-09-29 15:50 UTC, closed without merging