feat(core): Node execution warnings
n8n-io/n8n pull request #8954
Opened 2024-03-22 07:23 UTC by michael-radency

## Summary
Warnings are messages that are attached to the output. Unlike errors, they’re in addition to the output data, not instead of it.
![image](https://github.com/n8n-io/n8n/assets/88898367/5307c584-7552-4ab3-b34a-272c731524f3)

## Related tickets and issues
https://linear.app/n8n/issue/NODE-1238/output-warnings-and-run-once-for-each-item-harmonisation

2024-05-10 08:44 UTC, netroy requested changes
looks good, but can we please add any kind of a tests to ensure that this doesn't break the next time someone changes WorkflowExecute or NodeHelper.

2024-05-13 10:17 UTC, netroy submitted a review, later dismissed

2024-05-13 12:26 UTC, michael-radency commented
@netroy added some tests, we would need to add more after some nodes would have hints added

2024-05-13 12:29 UTC, netroy approved these changes

2024-05-13 12:46 UTC, merged

2024-05-15 10:40 UTC, janober commented
Got released with [`n8n@1.42.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.42.0)