feat(core): Return all team projects if the user has global `project:read` permissions
n8n-io/n8n pull request #8983
Opened 2024-03-27 11:23 UTC by despairblue

## Summary

The endpoint `GET /my-projects` now returns the personal project and all team projects if the user has global `project:read` permissions.

## Related tickets and issues

https://linear.app/n8n/issue/PAY-1455/update-the-project-endpoint-to-return-all-team-projects-for

## Review / Merge checklist

- [x] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [x] Tests included.
  > A bug is not considered fixed, unless a test is added to prevent it from happening again.
  > A feature is not complete without tests.

2024-03-27 11:54 UTC, krynble commented on packages/cli/src/controllers/project.controller.ts
> +				name: `Unclaimed Personal Project (${pr.projectId})`,
One consideration is that we might want to have all projects with name, including for invited but not signed up user - perhaps use just the email. But this is something to discuss later.

2024-03-27 11:55 UTC, krynble approved these changes

2024-03-27 12:49 UTC, krynble requested changes
![Screenshot 2024-03-27 at 12 48 54](https://github.com/n8n-io/n8n/assets/219272/e0bc70f6-8eec-4ddd-9302-87342a6f5cbb)

Just noticed that if I am also part of the project, it gets duplicate for whatever reason. I created a project and invited an additional user, and I can now see it twice in the response.

2024-03-27 17:20 UTC, krynble approved these changes

2024-03-27 17:53 UTC, despairblue commented
> ![Screenshot 2024-03-27 at 12 48 54](https://private-user-images.githubusercontent.com/219272/317269197-e0bc70f6-8eec-4ddd-9302-87342a6f5cbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDQxNTksIm5iZiI6MTcxMTU0Mzg1OSwicGF0aCI6Ii8yMTkyNzIvMzE3MjY5MTk3LWUwYmM3MGY2LThlZWMtNGRkZC05MzAyLTg3MzQyYTZmNWNiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QxMjUwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Y2JhNDRiZjY5MDBlNDhkMjJiNzZlNDkxM2VjODZiNTZlNjMzOGRkYjRlNjRlZGNlOTY1MTI3YzY2MDQ2MGZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yCNtd88YN1mENyN_QshHR9JnDEiwn60ua1B8FPb5CtA)
> 
> Just noticed that if I am also part of the project, it gets duplicate for whatever reason. I created a project and invited an additional user, and I can now see it twice in the response.

It's fixed now. But that took some fidgeting. The problem was that it used the relationships to get all projects. Which meant it would return projects multiple times if we have an `OR` query like "all project relations that you are a part of OR relate to team projects".

It would also not return orphaned projects at all, because they have no project relation.

Anyways, it's both fixed now, but the controller got a bit more complicated. I amended the tests to check for the right roles and scopes as well.

Btw it will return the global role for projects for which the user has no project relationship. 

I hope that makes sense. If not let me know and create some examples.

2024-03-28 08:39 UTC, krynble approved these changes

2024-03-28 08:51 UTC, merged