feat(JWT Node): New node
n8n-io/n8n pull request #9005
Opened 2024-03-29 11:04 UTC by michael-radency

## Summary
based on @Joffcom community [node](https://github.com/Joffcom/n8n-nodes-jwt)

## Related tickets and issues
https://linear.app/n8n/issue/NODE-1252/jwt-node-new-node

2024-04-08 17:46 UTC, Joffcom requested changes
Other than the URL we should add some tests as well.

2024-04-08 17:46 UTC, Joffcom commented on packages/nodes-base/nodes/Jwt/Jwt.node.json
> +				"url": "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.jwt/"
This should probably be `https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.jwt/` as it isn't integrating with a service

2024-04-10 07:59 UTC, Joffcom approved these changes

2024-04-10 10:16 UTC, merged

2024-04-10 14:16 UTC, janober commented
Got released with [`n8n@1.37.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.37.0)