perf: Add tailwind to editor and design system
n8n-io/n8n pull request #9032
Opened 2024-04-03 07:19 UTC by cstuncsik

2024-04-03 10:47 UTC, cstuncsik commented on packages/editor-ui/tailwind.config.js
> +	theme: {
That could be the next step. First, we should make sure none of the tailwind tokens collide with ours, and then we can start using them.
If I understood correctly, it would not add anything to the built bundle if you don't use anything from Tailwind.

I want to leverage its layout helpers in the first place because they are missing from our design system.
For typography, colors, and spacing, we can still use ours, and later, we can integrate.

2024-04-03 11:56 UTC, cstuncsik commented on packages/editor-ui/tailwind.config.js
> +	theme: {
I don't know how many colors we're using and haven't yet gone deep into customizing Tailwind with CSS variables (I know it's also using them)

1 way would be to overwrite existing tokens with our colors, they have quite a thorough palette and I don't think we use more shades than them (we shouldn't at least).
10-11 variants is more than enough for each color

The other way would be to give all of our own design system colors a meaningful CSS class name and just add them the the tailwind config

https://tailwindcss.com/docs/customizing-colors

Quite the same goes for spacing, luckily we don't have much of them

https://tailwindcss.com/docs/customizing-spacing

I'd say 1-3 days would be enough but verifying and testing is another question (especially without visual regression tests)

2024-04-03 12:00 UTC, mutdmour commented on packages/editor-ui/tailwind.config.js
> +	theme: {
okay, might be too much effort then to ask of you now.

in my head it's simply adding the mapped tokens to our existing css colors.

<img width="498" alt="Screenshot 2024-04-03 at 14 58 27" src="https://github.com/n8n-io/n8n/assets/4711238/7541c8b5-fc48-4cf2-89c6-f072356e41c8">

why do we need regression tests though? I am only asking to add the tokens like this, maybe update a small component to use the tailwind classes to validate..

2024-04-03 12:00 UTC, netroy requested changes, later dismissed

2024-04-03 12:01 UTC, mutdmour commented on packages/editor-ui/tailwind.config.js
> +	theme: {
we should not touch our current css variables..

2024-04-03 12:07 UTC, cstuncsik commented on packages/editor-ui/tailwind.config.js
> +	theme: {
Ok, I see. We just add these and start to use them as CSS classes on the elements rather than the CSS variables in the style tags.

I would be much calmer if we had a regression test to see if nothing was changed visually after introducing tailwind

2024-04-03 12:12 UTC, mutdmour commented on packages/editor-ui/tailwind.config.js
> +	theme: {
Okay. Ya you only need to touch a small component as a POC..

Happy to help with testing in any way. I ran it locally and tested and everything seemed fine.

Do you agree to add colors/spacing tokens within this PR then? Happy to approve if you still think otherwise.

2024-04-03 12:14 UTC, cstuncsik commented on packages/design-system/package.json
> +    "autoprefixer": "^10.4.19",
thanks, moved all into `devDependencies`

2024-04-03 12:20 UTC, cstuncsik commented on packages/editor-ui/tailwind.config.js
> +	theme: {
If nothing is broken I suggest add colors and spacing in a separate PR

2024-04-03 12:23 UTC, mutdmour submitted a review, later dismissed

2024-04-25 05:02 UTC, alexgrozav approved these changes, later dismissed

2024-05-09 07:13 UTC, alexgrozav approved these changes
Thank you for addressing all the feedback, Csaba!

2024-05-09 12:12 UTC, merged

2024-05-15 10:40 UTC, janober commented
Got released with [`n8n@1.42.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.42.0)