fix(editor): Fix parameter reset on credential change in Discord node
n8n-io/n8n pull request #9137
Opened 2024-04-12 12:39 UTC by elsmr

## Summary

Resource and operation parameters should not reset when credentials is changed.

The code that is looking for mismatched collection parameter options was also resetting options parameters.

Related to https://github.com/n8n-io/n8n/pull/8114

## Related tickets and issues
https://linear.app/n8n/issue/NODE-1089/discord-actions-not-being-seleted-after-selecting-them-in-nodes-panel

## Review / Merge checklist
- [ ] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included.
   > A bug is not considered fixed, unless a test is added to prevent it from happening again.
   > A feature is not complete without tests.

2024-04-12 14:29 UTC, MiloradFilipovic requested changes
Code looks ok but I have two comments on the solution:
1. This doesn't solve the issue from the linear ticket (which I cannot reproduce so if the issue is not valid anymore it would be good to update the ticket or create a new one just so we keep linear tickets and PR in sync)
2. I'm still encountering the issue where parameters are reset after changing the credentials:


https://github.com/n8n-io/n8n/assets/2598782/f2f4d54c-2a2a-411e-86e4-980d5097acf5

2024-04-12 14:58 UTC, elsmr commented
@MiloradFilipovic Updated the linear issue description. The original issue is indeed no longer reproducible, see comment thread in Linear with Jon and Niklas.

I think I missed the operation also being reset because I was testing with Message/Send (Send being the default operation), fixed now! 🎉

2024-04-17 12:45 UTC, MiloradFilipovic approved these changes
Looking good 🚀

2024-04-18 12:56 UTC, merged

2024-04-18 15:31 UTC, janober commented
Got released with [`n8n@1.38.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.38.1)