fix(Splunk Node): Retry attempts if no response from API call, better error with suggestion to use Retry On Fail
n8n-io/n8n pull request #9176
Opened 2024-04-19 11:39 UTC by michael-radency

## Summary
Splunk node: toString() method throwing errors when using with sid

- added recovery attempts if no response

## Related tickets and issues
https://community.n8n.io/t/splunk-retrieve-result-error/30145
https://linear.app/n8n/issue/NODE-753/splunk-node-tostring-method-throwing-errors-when-using-with-sid

2024-04-23 14:48 UTC, elsmr requested changes

2024-04-23 14:48 UTC, elsmr commented on packages/nodes-base/nodes/Splunk/Splunk.node.ts
> +		return [responseData];
I think this should be `returnData`

```suggestion
		return [returnData];
```

2024-04-24 06:08 UTC, michael-radency commented on packages/nodes-base/nodes/Splunk/Splunk.node.ts
> +		return [responseData];
thanks!

2024-04-24 07:50 UTC, elsmr approved these changes

2024-04-24 08:05 UTC, merged

2024-04-24 13:38 UTC, janober commented
Got released with [`n8n@1.39.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.39.0)