fix(core): Prevent node param resolution from failing telemetry graph generation
n8n-io/n8n pull request #9257
Opened 2024-04-30 08:05 UTC by ivov

https://linear.app/n8n/issue/PAY-1529/property-option-missing-when-creating-telemetry-payload

2024-04-30 08:16 UTC, despairblue approved these changes
~~LGTM~~

2024-04-30 08:22 UTC, despairblue requested changes

2024-04-30 08:31 UTC, despairblue commented on packages/workflow/test/TelemetryHelpers.test.ts
> +		const workflow = mock<IWorkflowBase>({ nodes: [] });
```suggestion
		const workflow = mock<IWorkflowBase>({ nodes: [{ type: STICKY_NODE_TYPE }] });
```

This seems to do it.

2024-04-30 08:32 UTC, despairblue commented on packages/workflow/test/TelemetryHelpers.test.ts
> +		const workflow = mock<IWorkflowBase>({ nodes: [] });
The import still needs to be adjusted.

2024-04-30 09:06 UTC, despairblue approved these changes
LGTM

2024-04-30 09:39 UTC, merged

2024-05-02 12:52 UTC, janober commented
Got released with [`n8n@1.40.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.40.0)