refactor(core): Rename `ActiveWorkflowRunner` to `ActiveWorkflowManager` (no-changelog)
n8n-io/n8n pull request #9280
Opened 2024-05-02 07:35 UTC by ivov

We have `WorkflowService`, `ExecutionService`, `WorkflowExecutionService`, `WorkflowRunner`, `ActiveExecutions`, `ActiveWorkflows`, and `ActiveWorkflowRunner` - the overlap in semantics and responsibilities makes the workflow execution lifecycle hard to follow.

This PR is the first of a series:
- Rename `ActiveWorkflowRunner` to `ActiveWorkflowManager`
- Combine `WorkflowExecutionService` with `WorkflowRunner` as `RunnerService`
- Move execution stopping logic from `ExecutionService` to `RunnerService`

2024-05-03 07:44 UTC, despairblue requested changes
I checked how much conflicts this would cause with feature/rbac, but it's manageable. 

I found some variables that still mention `Runner`. I saw that you renamed most of the others to be called `...Manager`, maybe we can rename the remaining ones as well to have this consistent. What do you think?

2024-05-03 07:44 UTC, despairblue commented on packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
> +			const workflowRunner = Container.get(ActiveWorkflowManager);
```suggestion
			const workflowManager = Container.get(ActiveWorkflowManager);
```

Should we rename this as well? Or would that make the PR too big?

2024-05-03 07:44 UTC, despairblue commented on packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
> +			const workflowRunner = Container.get(ActiveWorkflowManager);
```suggestion
			const workflowManager = Container.get(ActiveWorkflowManager);
```

2024-05-03 07:44 UTC, despairblue commented on packages/cli/test/integration/active-workflow-manager.test.ts
> +	runner = Container.get(ActiveWorkflowManager);
```suggestion
	manager = Container.get(ActiveWorkflowManager);
```

Maybe 🤔

2024-05-03 08:08 UTC, ivov commented
Thanks for reviewing!

> how much conflicts 

Happy to wait! I'll leave it up to you.

> some variables that still mention

Fixed!

2024-05-06 08:22 UTC, despairblue approved these changes, later dismissed
> Happy to wait! I'll leave it up to you.

No need to wait. The merge should be easy enough.

2024-05-06 15:37 UTC, despairblue approved these changes

2024-05-06 15:54 UTC, merged