refactor(google): Correct spelling mistake
n8n-io/n8n pull request #9305
Opened 2024-05-04 12:31 UTC by n8n-ninja

## Summary
Correct spelling mistake "dimesion" to "dimension" in Google node. 

## Related tickets and issues
none

## Review / Merge checklist
- [x] PR title and summary are descriptive.

2024-05-04 12:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/n8n-io/n8n?pullRequest=9305) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/n8n-io/n8n?pullRequest=9305) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/n8n-io/n8n?pullRequest=9305) it.</sub>

2024-06-19 19:10 UTC, netroy approved these changes

2024-06-19 19:20 UTC, netroy requested changes
Thanks for fixing this, but can you please merge the latest upstream in to trigger the CI job. We can't merge PRs until the CI passes.
Usually I can do this myself, but since your branch has push protection in place, I'm not allowed to push to this PR.

2024-06-20 09:31 UTC, n8n-ninja commented
Thanks @netroy, I updated my branch with the latest version. 
It should be ok now. Let me know if I missed something :)

2024-06-20 09:32 UTC, netroy approved these changes

2024-06-20 12:10 UTC, merged