Taiga Integration
n8n-io/n8n pull request #939
Opened 2020-09-08 03:35 UTC by RicardoE105

Improvements to #937

2020-09-08 22:25 UTC, renanfilipe requested changes
Thanks for improving the nodes, I've tested the self-hosted connection and it works as expected.

2020-09-08 22:25 UTC, renanfilipe commented on packages/nodes-base/nodes/Taiga/Taiga.node.ts
> +				const types = await taigaApiRequest.call(this, 'GET', `/issue-types?project=${project}`);
Here I was filtering the issue types by the project id, so in order to use `projectSlug` we'll have to fetch the project id using it. To create the method `getProjectId` please see: https://taigaio.github.io/taiga-doc/dist/api.html#projects-get-by-slug
```suggestion
				const projectSlug = this.getCurrentNodeParameter('projectSlug') as string;
				const returnData: INodePropertyOptions[] = [];

				const project = await getProjectId(this, projectSlug);
				const types = await taigaApiRequest.call(this, 'GET', `/issue-types?project=${project}`);
```

2020-09-08 22:25 UTC, renanfilipe commented on packages/nodes-base/nodes/Taiga/issueOperationFields.ts
> +						'project',
Please update it to `projectSlug`.

2020-09-08 22:25 UTC, renanfilipe commented on packages/nodes-base/nodes/Taiga/issueOperationFields.ts
> +						'project',
Please update it to `projectSlug`

2020-09-08 23:30 UTC, RicardoE105 commented on packages/nodes-base/nodes/Taiga/issueOperationFields.ts
> +		description: 'Project ID',
Yeah, I change the description but there is not much I can do here until we develop the proper documentation for the node and have screenshots ([example](https://docs.n8n.io/nodes/n8n-nodes-base.httpRequest/#node-reference)) for the non-technical users so they can easily find the project slug.  If you are interested in contributing with the docs for this node we have a repository for that here https://github.com/n8n-io/n8n-docs.

2020-09-08 23:32 UTC, RicardoE105 commented
@renanfilipe thanks for the feedback.

2020-09-09 11:21 UTC, MatheusRV commented
LGFM. Could some one merge this? I need it inside N8N ASAP.

2020-09-09 11:47 UTC, janober commented
@MatheusRV it will probably be merged the next days and then released with a new n8n version next week.

We do not simply merge code without properly testing, reviewing it and making sure that everything works consistently. If we would not, then the n8n code would become a mess and also the way the node works (as it would be totally inconsistent). I know that can be annoying as it takes longer but for us, it is much more important to release a new integration correctly than simply fast. Only like that can we make sure that n8n actually gets actually better instead of worst over time.

2020-09-17 21:20 UTC, merged

2020-09-17 21:20 UTC, janober commented
Thanks a lot. Got merged.

2020-09-18 08:16 UTC, janober commented
Got released with n8n@0.83.0

2021-04-20 22:15 UTC, cmprmsd commented
@RicardoE105 Thank you for creating this node!
I noticed it currently only supports only issues. However Taiga has many more types to offer e.g. tasks, user storys etc. 

Do you have any plans integrating these as well?
Maybe there would even be a sponsor for the effort (mentioned here: https://community.n8n.io/t/taiga-project-management-partly-created/2138)

Thanks in advance!