fix(RabbitMQ Node): Fix issue with arguments not being to queues
n8n-io/n8n pull request #9397
Opened 2024-05-14 15:57 UTC by Joffcom

## Summary
Arguments set were ignored, this adds them and assumes they will be in the amqplib `Options.Publish` format, Tested with RMQ 3.12.11 using `contentType` and `persistent` as test values.

![image](https://github.com/n8n-io/n8n/assets/4688521/eea45c59-2c08-4260-8a9d-55eec90386d8)

RMQ Management UI
![image](https://github.com/n8n-io/n8n/assets/4688521/ed72ffba-d98a-4324-b365-3f0c1dbad4f6)

## Related tickets and issues
https://github.com/n8n-io/n8n/issues/2806
https://linear.app/n8n/issue/NODE-1031

2024-05-31 11:33 UTC, michael-radency requested changes

2024-05-31 11:33 UTC, michael-radency commented on packages/nodes-base/nodes/RabbitMQ/RabbitMQ.node.ts
> +						}),
this will throw error if `options.arguments` undefined

2024-05-31 11:33 UTC, michael-radency commented on packages/nodes-base/nodes/RabbitMQ/RabbitMQ.node.ts
> +						}),
same here, we need to guard this

2024-07-07 19:04 UTC, Joffcom commented
@michael-radency fancy giving it another bash, Have updated and given it a quick test with and without options being set and all is good.

2024-07-19 08:06 UTC, michael-radency approved these changes
LGTM

2024-07-19 10:04 UTC, merged

2024-07-24 12:39 UTC, janober commented
Got released with [`n8n@1.52.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.52.0)