feat(Custom n8n Workflow Tool Node): Add support for tool input schema
n8n-io/n8n pull request #9470
Opened 2024-05-20 14:52 UTC by OlegIvaniv

## Summary
This PR introduces a new feature that allows you to specify the input schema for the `Custom n8n Workflow Tool` node. When used with Tools/OpenAI Functions Agent or Open AI Assistant, this enhancement enables the creation of more robust agents that can handle multiple parameters. Additionally, it also includes an option to generate the schema in the background based on a provided JSON object. The `Generate a schema from an example JSON object` option has been added to Structured Output Parser.

## Related tickets and issues
> Include links to **Linear ticket** or Github issue or Community forum post. Necessary to close *automatically* and provide context to reviewers.

## Review / Merge checklist
- [ ] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included.
   > A bug is not considered fixed unless a test is added to prevent it from happening again.
   > A feature is only complete with tests.

2024-05-21 11:16 UTC, michael-radency requested changes
@OlegIvaniv  looking good, there are some complains from linter and added some comments regarding duplication

2024-05-21 11:16 UTC, michael-radency commented on packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ReActAgent/execute.ts
> +			}
maybe could be extracted to some helper, as it's duplicated 3 times

2024-05-21 11:16 UTC, michael-radency commented on packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/ToolWorkflow.node.ts
> +			},
`specifyInputSchema`, `schemaType`, `jsonSchemaExample`, `inputSchema` are duplicated in few places maybe worth extract to common descriptions in `packages/@n8n/nodes-langchain/utils/descriptions.ts`

2024-05-21 11:16 UTC, michael-radency commented on packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/ToolWorkflow.node.ts
> +				default: false,
should we consider adding some description here explaining user what is it for and why he may want to toggle this?

2024-05-22 10:00 UTC, OlegIvaniv commented
Appreciate the suggestions, @michael-radency! I've implemented them and pushed my changes, can you have another look, please?

2024-05-22 10:55 UTC, michael-radency submitted a review, later dismissed
LGTM

2024-05-22 11:44 UTC, michael-radency approved these changes

2024-05-22 12:29 UTC, merged

2024-05-22 16:09 UTC, janober commented
Got released with [`n8n@1.43.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.43.0)