fix: Do not show [object Object] in error message when validating type (no-changelog)
n8n-io/n8n pull request #9591
Opened 2024-06-03 06:59 UTC by michael-radency

## Summary
in case a value is an object show 'object' or 'array' accordingly instead of '[object Object]'
![image](https://github.com/n8n-io/n8n/assets/88898367/2c615867-ccbd-4733-af1e-62671d63a808)

## Related tickets and issues
https://linear.app/n8n/issue/NODE-1349/type-errors-in-filter-component-dont-work-when-value-is-array-or

2024-06-03 07:12 UTC, netroy requested changes

2024-06-03 07:12 UTC, netroy commented on packages/workflow/src/TypeValidation.ts
> +export const getValueDescription = <T>(value: T, stringify = false): string => {
`stringify` doesn't seem to be passed in anywhere so far. We should remove it, and also remove line 151, until they are actually needed.

2024-06-03 08:54 UTC, netroy approved these changes
🙇🏽

2024-06-03 09:09 UTC, merged

2024-06-05 15:47 UTC, janober commented
Got released with [`n8n@1.45.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.45.0)