feat(editor): Update sticky content when checkbox state changes
n8n-io/n8n pull request #9596
Opened 2024-06-03 10:40 UTC by MiloradFilipovic

## Summary
After adding checkbox support to markdown (#9549), this PR will sync underlying markdown on checkbox changes

## Review / Merge checklist
- [ ] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included.
   > A bug is not considered fixed, unless a test is added to prevent it from happening again.
   > A feature is not complete without tests.

2024-06-03 11:15 UTC, netroy requested changes

2024-06-03 11:19 UTC, netroy requested changes

2024-06-03 11:19 UTC, netroy commented on packages/design-system/src/components/N8nSticky/__tests__/Sticky.spec.ts
> +import { N8nMarkdown } from '@/main';
To avoid loading the entire package in this test:

```suggestion
import N8nMarkdown from '../../N8nMarkdown/Markdown.vue';
```

2024-06-03 12:38 UTC, netroy approved these changes, later dismissed

2024-06-04 15:20 UTC, netroy approved these changes
🎉

2024-06-05 07:01 UTC, merged

2024-06-05 15:47 UTC, janober commented
Got released with [`n8n@1.45.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.45.0)