feat: Do not show errors not processed by n8n (no-changelog)
n8n-io/n8n pull request #9598
Opened 2024-06-03 11:32 UTC by michael-radency

## Summary
When there is an unhanded exception in n8n's execution code, we currently display the inner workings of n8n too prominently

## Related tickets and issues
https://linear.app/n8n/issue/NODE-1338/tidy-up-internal-node-errors

2024-06-03 11:36 UTC, netroy requested changes
Instead of completely overwriting the original error message, we should wrap the error (passing the original error as a `cause` in the outer error), and put the original error either behind a collapsed section on the frontend, or not render it at all. But, we should at all cost avoid modifying `error.message` or any other error properties.

2024-06-03 11:36 UTC, netroy commented on packages/workflow/src/errors/node-operation.error.ts
> +			error.message = OBFUSCATED_ERROR_MESSAGE;
We should stop overwriting error properties like this, as that remove context on errors that get reported to Sentry.

2024-06-19 18:08 UTC, netroy approved these changes

2024-06-20 05:45 UTC, merged

2024-06-20 19:32 UTC, janober commented
Got released with [`n8n@1.47.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.47.0)