Ado 2269 prevent saving saved workflows
n8n-io/n8n pull request #9670
Opened 2024-06-07 13:04 UTC by MiloradFilipovic

## Summary
Prevent `cmd`+`s` keyboard shortcut to send save requests if workflow is already saved.

## Related tickets and issues
Fixes ADO-2269

## Review / Merge checklist
- [ ] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included.
   > A bug is not considered fixed, unless a test is added to prevent it from happening again.
   > A feature is not complete without tests.

2024-06-10 07:49 UTC, OlegIvaniv requested changes

2024-06-10 07:49 UTC, OlegIvaniv commented on cypress/e2e/7-workflow-actions.cy.ts
> +	it.only('should not save already saved workflow', () => {
👁️ it.only

2024-06-10 08:33 UTC, MiloradFilipovic commented on cypress/e2e/7-workflow-actions.cy.ts
> +	it.only('should not save already saved workflow', () => {
🤦‍♂️

2024-06-10 08:35 UTC, OlegIvaniv approved these changes

2024-06-10 13:36 UTC, OlegIvaniv approved these changes

2024-06-10 14:00 UTC, merged

2024-06-12 14:06 UTC, janober commented
Got released with [`n8n@1.46.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.46.0)