fix: Fix sending pin data twice causing payload too large errors
n8n-io/n8n pull request #9710
Opened 2024-06-12 10:24 UTC by tomi

## Summary

For manual executions the pin data is sent to the backend in the execute request. At the moment it is included twice. Once in the `.pinData` and once in the `.workflowData.pinData`. The data is identical. This can cause 413 payload too large errors for workflows for which it is still possible to pin the data.

This change removes the `.pinData` parameter from the POST /:id/run endpoint, requiring the pin data to be defined in the `.workflowData.pinData` property. In the `IWorkflowExecutionDataProcess` interface the pin data is kept in both `.pinData` and `.workflowData.pinData` properties for backwards compatibility.

## Related tickets and issues

https://linear.app/n8n/issue/ADO-1731/bug-pinned-data-still-causing-413-errors

## Review / Merge checklist
- [ ] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included.
   > A bug is not considered fixed, unless a test is added to prevent it from happening again.
   > A feature is not complete without tests.

2024-06-12 10:32 UTC, netroy submitted a review, later dismissed
🎉

2024-06-12 11:07 UTC, netroy requested changes

2024-06-12 11:07 UTC, netroy commented on cypress/e2e/19-execution.cy.ts
> +			expect(interception.request.body).not.to.have.property('pinData').that.is.an('object');
do we really need this assertion? I'd say this is only needed if there is a risk that someone might add the `pinData` field back. Which I don't think we need to put a check for.

2024-06-12 11:16 UTC, netroy approved these changes

2024-06-12 12:11 UTC, merged

2024-06-20 19:25 UTC, janober commented
Got released with [`n8n@1.47.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.47.0)

2024-06-20 19:31 UTC, janober commented
Got released with [`n8n@1.47.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.47.0)