migrate `userHelpers` mixing to composable
n8n-io/n8n pull request #9737
Opened 2024-06-14 06:26 UTC by RicardoE105

## Summary

## Related Linear tickets, Github issues, and Community forum posts

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-06-14 07:46 UTC, alexgrozav requested changes

2024-06-14 07:46 UTC, alexgrozav commented on packages/editor-ui/src/composables/useUserHelpers.ts
> +	const route = useRoute();
To follow the pattern we have in the other composables, can you add the router and route as composable arguments? See `usePushConnection`.

2024-06-15 06:06 UTC, alexgrozav approved these changes

2024-06-15 13:41 UTC, merged

2024-06-20 19:25 UTC, janober commented
Got released with [`n8n@1.47.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.47.0)

2024-06-20 19:31 UTC, janober commented
Got released with [`n8n@1.47.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.47.0)