fix(core): `$(...).[last,first,all]()` defaulting to the first output instead of the output that connects the nodes
n8n-io/n8n pull request #9760
Opened 2024-06-14 15:51 UTC by despairblue

## Summary

This PR makes `$(...).[last|first|all]()` default to the the output the node was connected to.

Before it would default to the first output.

TK: add Photos

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/PAY-1400/bug-dollarlast-uses-wrong-branch

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included. 
- [ ] ~PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)~

2024-06-18 10:08 UTC, krynble submitted a review, later dismissed
Thanks for addressing this bug and adding the tests! Great work!

2024-06-18 10:57 UTC, ivov requested changes
Thank you for fixing this! If this is a breaking change, let's please update the [breaking changes doc](https://github.com/n8n-io/n8n/blob/master/packages/cli/BREAKING-CHANGES.md) as well. Else let's remove `!` from the title.

2024-06-18 10:57 UTC, ivov commented
Follow-up: https://linear.app/n8n/issue/PAY-1692

2024-06-18 13:58 UTC, ivov commented on packages/cli/BREAKING-CHANGES.md
> +## 1.46.0
Next version will be 1.47.0

2024-06-19 09:26 UTC, ivov approved these changes

2024-06-19 13:10 UTC, merged

2024-06-20 19:25 UTC, janober commented
Got released with [`n8n@1.47.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.47.0)

2024-06-20 19:32 UTC, janober commented
Got released with [`n8n@1.47.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.47.0)