Fix equals sign encoding in "Import from cURL" form
n8n-io/n8n pull request #9769
Opened 2024-06-15 10:50 UTC by restyler

## Summary
`=` sign is encoded incorrectly on JSON import due to outdated `curlconverter` dependency. I verified that newer `curlconverter` versions are working correctly. (I am new to n8n development so I apologize if I missed something in this PR) 

## Related Linear tickets, Github issues, and Community forum posts
https://github.com/n8n-io/n8n/issues/9768

2024-06-15 10:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/n8n-io/n8n?pullRequest=9769) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/n8n-io/n8n?pullRequest=9769) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/n8n-io/n8n?pullRequest=9769) it.</sub>

2024-06-15 14:42 UTC, netroy requested changes
From what I can tell curlconverter@4 is an ESM only package, and n8n can't use ESM right now.
To solve this we either need to update n8n, and all its dependencies to be ESM, or ask curlconverter to publish a package that works with CJS and ESM both.
The third option would be find the actual fix in curlconverter@4, back-port it to 3.x, send them a PR, ask them to publish a 3.x version, and then update that version here.

2024-06-17 08:41 UTC, ivov commented
Tracking: https://linear.app/n8n/issue/PAY-1681

2024-07-05 15:35 UTC, restyler commented
It turned out that the problem is in query-string package which is used in `generators/json.js` dependency of the curlconverter.
https://github.com/curlconverter/curlconverter/blob/v3.21.0/generators/json.js#L48

this is where the string gets corrupted.
The funny thing is that latest `query-string@7` contains the error, and `query-string@8` is ESM-only, pretty much like latest `curlconverter`.


I can get the latest version of this `json` generator from `v4` branch:
https://github.com/curlconverter/curlconverter/blob/v4.10.1/src/generators/json.ts - and  convert it to Javascript (since curlconverter@3 is JS, not TS) but this is definitely not a 3 or 5 line change - do you think this would make sense to back-port?

2024-07-05 15:46 UTC, netroy commented
> do you think this would make sense to back-port

Do you mean back-port the fix in curlconverter? I think that's the decision for the maintainers of curlconverter.

2026-04-08 14:29 UTC, garritfra commented
I believe this one is stale. (See https://github.com/n8n-io/n8n/issues/9768)

2026-04-08 14:29 UTC, closed without merging