migrate tags.store to composition API
n8n-io/n8n pull request #9891
Opened 2024-06-28 17:26 UTC by RicardoE105

## Summary

## Related Linear tickets, Github issues, and Community forum posts

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-07-01 09:49 UTC, alexgrozav requested changes
Looking good! Small issue with the computed getter.

2024-07-01 09:49 UTC, alexgrozav commented on packages/editor-ui/src/stores/tags.store.ts
> +	const tags = ref<{ [id: string]: ITag }>({});
nit: Typically `Record<string, ITag>` is the preferred way to type key value pairs.

2024-07-01 09:49 UTC, alexgrozav commented on packages/editor-ui/src/stores/tags.store.ts
> +	});
Computed getters will break in composition API if used within another computed value. We should just rename `tags` to `tagsById`, and reference the value directly instead (i.e. `tagsStore.tagsById[id]`).

2024-07-01 09:49 UTC, alexgrozav commented on packages/editor-ui/src/stores/tags.store.ts
> +		tags.value = loadedTags.reduce((accu: { [id: string]: ITag }, tag: ITag) => {
nit: Would prefer `Record<string, ITag>` instead

2024-07-02 09:00 UTC, alexgrozav approved these changes
Awesome! Thank you for making the changes!

2024-07-02 18:02 UTC, alexgrozav approved these changes

2024-07-02 18:15 UTC, merged

2024-07-03 13:49 UTC, janober commented
Got released with [`n8n@1.49.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.49.0)