feat(Zammad Node): Add reply_to and sender fields to article on ticket creation
n8n-io/n8n pull request #9911
Opened 2024-07-02 09:38 UTC by envy

## Summary

Add two new fields to Zammad articles during Zammad ticket creation:

![grafik](https://github.com/n8n-io/n8n/assets/241552/ea32e782-c595-4e3d-a692-a3fdc14279af)

The new `sender` field allows setting which side has created the article, which always defaulted to `Agent` previously.
The new `reply_to` field allows setting a email address for replies that is different from the email address of the user that created the article. This is needed when using a single account to create tickets and articles as otherwise that accounts email address is used for replies.

## Related Linear tickets, Github issues, and Community forum posts

This PR addresses the FR part of #9807 but not the bug reported in the ticket.

## Review / Merge checklist

- [X] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-07-02 09:49 UTC, Joffcom commented on packages/nodes-base/nodes/Zammad/descriptions/TicketDescription.ts
> +						// Yes, zammad uses capitalized values here.
This comment isn't needed

2024-07-02 09:49 UTC, Joffcom requested changes
Mostly looks good, Did you also run the linter?

2024-07-02 11:22 UTC, envy commented
> Mostly looks good, Did you also run the linter?

I followed the steps from CONTRIBUTING.md which dos not say anything about linting. I did use VSCode with the ESLint plugin and it does not complain with my changes. I have now also run `pnpm lint` which did complain in the langchain node which I did not touch. So I guess my answer is maybe yes? :D

2024-07-02 14:51 UTC, Joffcom approved these changes
This looks good, Thanks for doing this.

2024-07-03 07:55 UTC, merged

2024-07-03 13:49 UTC, janober commented
Got released with [`n8n@1.49.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.49.0)