migrate outputPanel.vue to composition API
n8n-io/n8n pull request #9958
Opened 2024-07-06 15:28 UTC by RicardoE105

## Summary

## Related Linear tickets, Github issues, and Community forum posts

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

2024-07-08 14:14 UTC, alexgrozav requested changes
Great work! Caught a small issue with translations.

2024-07-08 14:14 UTC, alexgrozav commented on packages/editor-ui/src/components/OutputPanel.vue
> +	{ label: 'ndv.output.outType.regular', value: OUTPUT_TYPE.REGULAR },
These two `label` values should be translated here.

2024-07-08 15:05 UTC, alexgrozav approved these changes

2024-07-08 15:19 UTC, merged

2024-07-10 15:57 UTC, janober commented
Got released with [`n8n@1.50.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.50.0)